In [1]:
# explanation of variables
# popularity: score from the moviedb API that factors in the following: (1)Number of votes for the day, (2) Number of views for the day, (3) Number of users who marked it as a "favourite" for the day, (4) Number of users who added it to their "watchlist" for the day, (5) Release date, (6) Number of total votes, (7) Previous days score

### Pull in the raw data from the API

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import seaborn as sns
import datetime as dt
import time
# from urllib.request import urlretrieve
%matplotlib inline

In [3]:
# Import API key
from api_keys import api_key

In [4]:
# define Kaggle dataset and get list of movie ids
movie_data_to_load = "Resources/tmdb_5000_credits.csv"
movies_df = pd.read_csv(movie_data_to_load)
movies_df.drop(columns=["cast","crew"],inplace=True)
list_of_movie_id = [id for id in movies_df["movie_id"]]

In [5]:
# establish column names for the dataframe
column_names = ["ID","Title","Adult","Budget","Genres","Language","Overview","Popularity","Production Countries","Release Date","Revenue","Runtime","Spoken Languages","Status","Video","Average Vote","Vote Count"]
movies_df = pd.DataFrame(columns = column_names)

In [6]:
# set ID equal to the list of movie IDs and drop any duplicates
movies_df["ID"] = list_of_movie_id
movies_df.drop_duplicates(keep="first",inplace=True)

In [7]:
# establish the base URL
base_url = "https://api.themoviedb.org/3/movie/"
# define different variables that iterate (to be used as controls to make sure we know how many rows are getting pulled and to avoid infinite loops)
record_number = 0
iteration = 0 

print("Beginning Data Detrieval...")
# create the loop to fill out all the columns in the dataframe
for index, row in movies_df.iterrows():
    movie_id = row["ID"]
    target_url = base_url+str(movie_id)+"?api_key="+api_key+"&language=en-US"
    try:
        response = requests.get(target_url).json()
        if iteration < 6500:
            movies_df.set_value(index,"Title",response["title"])
            movies_df.set_value(index,"Adult",response["adult"])
            movies_df.set_value(index,"Budget",response["budget"])
            movies_df.set_value(index,"Genres",response["genres"])
            movies_df.set_value(index,"Language",response["original_language"])
            movies_df.set_value(index,"Overview",response["overview"])
            movies_df.set_value(index,"Popularity",response["popularity"])
            movies_df.set_value(index,"Production Countries",response["production_countries"])
            movies_df.set_value(index,"Release Date",response["release_date"])
            movies_df.set_value(index,"Revenue",response["revenue"])
            movies_df.set_value(index,"Spoken Languages",response["spoken_languages"])
            movies_df.set_value(index,"Status",response["status"])
            movies_df.set_value(index,"Video",response["video"])
            movies_df.set_value(index,"Average Vote",response["vote_average"])
            movies_df.set_value(index,"Vote Count",response["vote_count"])
            movies_df.set_value(index,"Runtime",response["runtime"])
            
            time.sleep(1)
            record_number += 1
            iteration += 1
            print("Processed record #" + str(record_number))
        else:
            break
    except KeyError:
        print("Did not work. Skipping...")
        pass

Beginning Data Detrieval...

C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  from ipykernel import kernelapp as app
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  app.launch_new_instance()
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:28: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:29: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:30: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

Processed record #1
Processed record #2
Processed record #3
Processed record #4
Processed record #5
Processed record #6
Processed record #7
Processed record #8
Processed record #9
Processed record #10
Processed record #11
Processed record #12
Processed record #13
Processed record #14
Processed record #15
Processed record #16
Processed record #17
Processed record #18
Processed record #19
Processed record #20
Processed record #21
Processed record #22
Processed record #23
Processed record #24
Processed record #25
Processed record #26
Processed record #27
Processed record #28
Processed record #29
Processed record #30
Processed record #31
Processed record #32
Processed record #33
Processed record #34
Processed record #35
Processed record #36
Processed record #37
Processed record #38
Processed record #39
Processed record #40
Processed record #41
Processed record #42
Processed record #43
Processed record #44
Processed record #45
Processed record #46
Processed record #47
Processed record #48
Processed record #49
Processed record #50
Processed record #51
Processed record #52
Processed record #53
Processed record #54
Processed record #55
Processed record #56
Processed record #57
Processed record #58
Processed record #59
Processed record #60
Processed record #61
Processed record #62
Processed record #63
Processed record #64
Processed record #65
Processed record #66
Processed record #67
Processed record #68
Processed record #69
Processed record #70
Processed record #71
Processed record #72
Processed record #73
Processed record #74
Processed record #75
Processed record #76
Processed record #77
Processed record #78
Processed record #79
Processed record #80
Processed record #81
Processed record #82
Processed record #83
Processed record #84
Processed record #85
Processed record #86
Processed record #87
Processed record #88
Processed record #89
Processed record #90
Processed record #91
Processed record #92
Processed record #93
Processed record #94
Processed record #95
Processed record #96
Processed record #97
Processed record #98
Processed record #99
Processed record #100
Processed record #101
Processed record #102
Processed record #103
Processed record #104
Processed record #105
Processed record #106
Processed record #107
Processed record #108
Processed record #109
Processed record #110
Processed record #111
Processed record #112
Processed record #113
Processed record #114
Processed record #115
Processed record #116
Processed record #117
Processed record #118
Processed record #119
Processed record #120
Processed record #121
Processed record #122
Processed record #123
Processed record #124
Processed record #125
Processed record #126
Processed record #127
Processed record #128
Processed record #129
Processed record #130
Processed record #131
Processed record #132
Processed record #133
Processed record #134
Processed record #135
Processed record #136
Processed record #137
Processed record #138
Processed record #139
Processed record #140
Processed record #141
Processed record #142
Processed record #143
Processed record #144
Processed record #145
Processed record #146
Processed record #147
Processed record #148
Processed record #149
Processed record #150
Processed record #151
Processed record #152
Processed record #153
Processed record #154
Processed record #155
Processed record #156
Processed record #157
Processed record #158
Processed record #159
Processed record #160
Processed record #161
Processed record #162
Processed record #163
Processed record #164
Processed record #165
Processed record #166
Processed record #167
Processed record #168
Processed record #169
Processed record #170
Processed record #171
Processed record #172
Processed record #173
Processed record #174
Processed record #175
Processed record #176
Processed record #177
Processed record #178
Processed record #179
Processed record #180
Processed record #181
Processed record #182
Processed record #183
Processed record #184
Processed record #185
Processed record #186
Processed record #187
Processed record #188
Processed record #189
Processed record #190
Processed record #191
Processed record #192
Processed record #193
Processed record #194
Processed record #195
Processed record #196
Processed record #197
Processed record #198
Processed record #199
Processed record #200
Processed record #201
Processed record #202
Processed record #203
Processed record #204
Processed record #205
Processed record #206
Processed record #207
Processed record #208
Processed record #209
Processed record #210
Processed record #211
Processed record #212
Processed record #213
Processed record #214
Processed record #215
Processed record #216
Processed record #217
Processed record #218
Processed record #219
Processed record #220
Processed record #221
Processed record #222
Processed record #223
Processed record #224
Processed record #225
Processed record #226
Processed record #227
Processed record #228
Processed record #229
Processed record #230
Processed record #231
Processed record #232
Processed record #233
Processed record #234
Processed record #235
Processed record #236
Processed record #237
Processed record #238
Processed record #239
Processed record #240
Processed record #241
Processed record #242
Processed record #243
Processed record #244
Processed record #245
Processed record #246
Processed record #247
Processed record #248
Processed record #249
Processed record #250
Processed record #251
Processed record #252
Processed record #253
Processed record #254
Processed record #255
Processed record #256
Processed record #257
Processed record #258
Processed record #259
Processed record #260
Processed record #261
Processed record #262
Processed record #263
Processed record #264
Processed record #265
Processed record #266
Processed record #267
Processed record #268
Processed record #269
Processed record #270
Processed record #271
Processed record #272
Processed record #273
Processed record #274
Processed record #275
Processed record #276
Processed record #277
Processed record #278
Processed record #279
Processed record #280
Processed record #281
Processed record #282
Processed record #283
Processed record #284
Processed record #285
Processed record #286
Processed record #287
Processed record #288
Processed record #289
Processed record #290
Processed record #291
Processed record #292
Processed record #293
Processed record #294
Processed record #295
Processed record #296
Processed record #297
Processed record #298
Processed record #299
Processed record #300
Processed record #301
Processed record #302
Processed record #303
Processed record #304
Processed record #305
Processed record #306
Processed record #307
Processed record #308
Processed record #309
Processed record #310
Processed record #311
Processed record #312
Processed record #313
Processed record #314
Processed record #315
Processed record #316
Processed record #317
Processed record #318
Processed record #319
Processed record #320
Processed record #321
Processed record #322
Processed record #323
Processed record #324
Processed record #325
Processed record #326
Processed record #327
Processed record #328
Processed record #329
Processed record #330
Processed record #331
Processed record #332
Processed record #333
Processed record #334
Processed record #335
Processed record #336
Processed record #337
Processed record #338
Processed record #339
Processed record #340
Processed record #341
Processed record #342
Processed record #343
Processed record #344
Processed record #345
Processed record #346
Processed record #347
Processed record #348
Processed record #349
Processed record #350
Processed record #351
Processed record #352
Processed record #353
Processed record #354
Processed record #355
Processed record #356
Processed record #357
Processed record #358
Processed record #359
Processed record #360
Processed record #361
Processed record #362
Processed record #363
Processed record #364
Processed record #365
Processed record #366
Processed record #367
Processed record #368
Processed record #369
Processed record #370
Processed record #371
Processed record #372
Processed record #373
Processed record #374
Processed record #375
Processed record #376
Processed record #377
Processed record #378

Processed record #379
Processed record #380
Processed record #381
Processed record #382
Processed record #383
Processed record #384
Processed record #385
Processed record #386
Processed record #387
Processed record #388
Processed record #389
Processed record #390
Processed record #391
Processed record #392
Processed record #393
Processed record #394
Processed record #395
Processed record #396
Processed record #397
Processed record #398
Processed record #399
Processed record #400
Processed record #401
Processed record #402
Processed record #403
Processed record #404
Processed record #405
Processed record #406
Processed record #407
Processed record #408
Processed record #409
Processed record #410
Processed record #411
Processed record #412
Processed record #413
Processed record #414
Processed record #415
Processed record #416
Processed record #417
Processed record #418
Processed record #419
Processed record #420
Processed record #421
Processed record #422
Processed record #423
Processed record #424
Processed record #425
Processed record #426
Processed record #427
Processed record #428
Processed record #429
Processed record #430
Processed record #431
Processed record #432
Processed record #433
Processed record #434
Processed record #435
Processed record #436
Processed record #437
Processed record #438
Processed record #439
Processed record #440
Processed record #441
Processed record #442
Processed record #443
Processed record #444
Processed record #445
Processed record #446
Processed record #447
Processed record #448
Processed record #449
Processed record #450
Processed record #451
Processed record #452
Processed record #453
Processed record #454
Processed record #455
Processed record #456
Processed record #457
Processed record #458
Processed record #459
Processed record #460
Processed record #461
Processed record #462
Processed record #463
Processed record #464
Processed record #465
Processed record #466
Processed record #467
Processed record #468
Processed record #469
Processed record #470
Processed record #471
Processed record #472
Processed record #473
Processed record #474
Processed record #475
Processed record #476
Processed record #477
Processed record #478
Processed record #479
Processed record #480
Processed record #481
Processed record #482
Processed record #483
Processed record #484
Processed record #485
Processed record #486
Processed record #487
Processed record #488
Processed record #489
Processed record #490
Processed record #491
Processed record #492
Processed record #493
Processed record #494
Processed record #495
Processed record #496
Processed record #497
Processed record #498
Processed record #499
Processed record #500
Processed record #501
Processed record #502
Processed record #503
Processed record #504
Processed record #505
Processed record #506
Processed record #507
Processed record #508
Processed record #509
Processed record #510
Processed record #511
Processed record #512
Processed record #513
Processed record #514
Processed record #515
Processed record #516
Processed record #517
Processed record #518
Processed record #519
Processed record #520
Processed record #521
Processed record #522
Processed record #523
Processed record #524
Processed record #525
Processed record #526
Processed record #527
Processed record #528
Processed record #529
Processed record #530
Processed record #531
Processed record #532
Processed record #533
Processed record #534
Processed record #535
Processed record #536
Processed record #537
Processed record #538
Processed record #539
Processed record #540
Processed record #541
Processed record #542
Processed record #543
Processed record #544
Processed record #545
Processed record #546
Processed record #547
Processed record #548
Processed record #549
Processed record #550
Processed record #551
Processed record #552
Processed record #553
Processed record #554
Processed record #555
Processed record #556
Processed record #557
Processed record #558
Processed record #559
Processed record #560
Processed record #561
Processed record #562
Processed record #563
Processed record #564
Processed record #565
Processed record #566
Processed record #567
Processed record #568
Processed record #569
Processed record #570
Processed record #571
Processed record #572
Processed record #573
Processed record #574
Processed record #575
Processed record #576
Processed record #577
Processed record #578
Processed record #579
Processed record #580
Processed record #581
Processed record #582
Processed record #583
Processed record #584
Processed record #585
Processed record #586
Processed record #587
Processed record #588
Processed record #589
Processed record #590
Processed record #591
Processed record #592
Processed record #593
Processed record #594
Processed record #595
Processed record #596
Processed record #597
Processed record #598
Processed record #599
Processed record #600
Processed record #601
Processed record #602
Processed record #603
Processed record #604
Processed record #605
Processed record #606
Processed record #607
Processed record #608
Processed record #609
Processed record #610
Processed record #611
Processed record #612
Processed record #613
Processed record #614
Processed record #615
Processed record #616
Processed record #617
Processed record #618
Processed record #619
Processed record #620
Processed record #621
Processed record #622
Processed record #623
Processed record #624
Processed record #625
Processed record #626
Processed record #627
Processed record #628
Processed record #629
Processed record #630
Processed record #631
Processed record #632
Processed record #633
Processed record #634
Processed record #635
Processed record #636
Processed record #637
Processed record #638
Processed record #639
Processed record #640
Processed record #641
Processed record #642
Processed record #643
Processed record #644
Processed record #645
Processed record #646
Processed record #647
Processed record #648
Processed record #649
Processed record #650
Processed record #651
Processed record #652
Processed record #653
Processed record #654
Processed record #655
Processed record #656
Processed record #657
Processed record #658
Processed record #659
Processed record #660
Processed record #661
Processed record #662
Processed record #663
Processed record #664
Processed record #665
Processed record #666
Processed record #667
Processed record #668
Processed record #669
Processed record #670
Processed record #671
Processed record #672
Processed record #673
Processed record #674
Processed record #675
Processed record #676
Processed record #677
Processed record #678
Processed record #679
Processed record #680
Processed record #681
Processed record #682
Processed record #683
Processed record #684
Processed record #685
Processed record #686
Processed record #687
Processed record #688
Processed record #689
Processed record #690
Processed record #691
Processed record #692
Processed record #693
Processed record #694
Processed record #695
Processed record #696
Processed record #697
Processed record #698
Processed record #699
Processed record #700
Processed record #701
Processed record #702
Processed record #703
Processed record #704
Processed record #705
Processed record #706
Processed record #707
Processed record #708
Processed record #709
Processed record #710
Processed record #711
Processed record #712
Processed record #713
Processed record #714
Processed record #715
Processed record #716
Processed record #717
Processed record #718
Processed record #719
Processed record #720
Processed record #721
Processed record #722
Processed record #723
Processed record #724
Processed record #725
Processed record #726
Processed record #727
Processed record #728
Processed record #729
Processed record #730
Processed record #731
Processed record #732
Processed record #733
Processed record #734
Processed record #735
Processed record #736
Processed record #737
Processed record #738
Processed record #739
Processed record #740
Processed record #741
Processed record #742
Processed record #743
Processed record #744
Processed record #745
Processed record #746
Processed record #747
Processed record #748
Processed record #749
Processed record #750
Processed record #751

Processed record #752
Processed record #753
Processed record #754
Processed record #755
Processed record #756
Processed record #757
Processed record #758
Processed record #759
Processed record #760
Processed record #761
Processed record #762
Processed record #763
Processed record #764
Processed record #765
Processed record #766
Processed record #767
Processed record #768
Processed record #769
Processed record #770
Processed record #771
Processed record #772
Processed record #773
Processed record #774
Processed record #775
Processed record #776
Processed record #777
Processed record #778
Processed record #779
Processed record #780
Processed record #781
Processed record #782
Processed record #783
Processed record #784
Processed record #785
Processed record #786
Processed record #787
Processed record #788
Processed record #789
Processed record #790
Processed record #791
Processed record #792
Processed record #793
Processed record #794
Processed record #795
Processed record #796
Processed record #797
Processed record #798
Processed record #799
Processed record #800
Processed record #801
Processed record #802
Processed record #803
Processed record #804
Processed record #805
Processed record #806
Processed record #807
Processed record #808
Processed record #809
Processed record #810
Processed record #811
Processed record #812
Processed record #813
Processed record #814
Processed record #815
Processed record #816
Processed record #817
Processed record #818
Processed record #819
Processed record #820
Processed record #821
Processed record #822
Processed record #823
Processed record #824
Processed record #825
Processed record #826
Processed record #827
Processed record #828
Processed record #829
Processed record #830
Processed record #831
Processed record #832
Processed record #833
Processed record #834
Processed record #835
Processed record #836
Processed record #837
Processed record #838
Processed record #839
Processed record #840
Processed record #841
Processed record #842
Processed record #843
Processed record #844
Processed record #845
Processed record #846
Processed record #847
Processed record #848
Processed record #849
Processed record #850
Processed record #851
Processed record #852
Processed record #853
Processed record #854
Processed record #855
Processed record #856
Processed record #857
Processed record #858
Processed record #859
Processed record #860
Processed record #861
Processed record #862
Processed record #863
Processed record #864
Processed record #865
Processed record #866
Processed record #867
Processed record #868
Processed record #869
Processed record #870
Processed record #871
Processed record #872
Processed record #873
Processed record #874
Processed record #875
Processed record #876
Processed record #877
Processed record #878
Processed record #879
Processed record #880
Processed record #881
Processed record #882
Processed record #883
Processed record #884
Processed record #885
Processed record #886
Processed record #887
Processed record #888
Processed record #889
Processed record #890
Processed record #891
Processed record #892
Processed record #893
Processed record #894
Processed record #895
Processed record #896
Processed record #897
Processed record #898
Processed record #899
Processed record #900
Processed record #901
Processed record #902
Processed record #903
Processed record #904
Processed record #905
Processed record #906
Processed record #907
Processed record #908
Processed record #909
Processed record #910
Processed record #911
Processed record #912
Processed record #913
Processed record #914
Processed record #915
Processed record #916
Processed record #917
Processed record #918
Processed record #919
Processed record #920
Processed record #921
Processed record #922
Processed record #923
Processed record #924
Processed record #925
Processed record #926
Processed record #927
Processed record #928
Processed record #929
Processed record #930
Processed record #931
Processed record #932
Processed record #933
Processed record #934
Processed record #935
Processed record #936
Processed record #937
Processed record #938
Processed record #939
Processed record #940
Processed record #941
Processed record #942
Processed record #943
Processed record #944
Processed record #945
Processed record #946
Processed record #947
Processed record #948
Processed record #949
Processed record #950
Processed record #951
Processed record #952
Processed record #953
Processed record #954
Processed record #955
Processed record #956
Processed record #957
Processed record #958
Processed record #959
Processed record #960
Processed record #961
Processed record #962
Processed record #963
Processed record #964
Processed record #965
Processed record #966
Processed record #967
Processed record #968
Processed record #969
Processed record #970
Processed record #971
Processed record #972
Processed record #973
Processed record #974
Processed record #975
Processed record #976
Processed record #977
Processed record #978
Processed record #979
Processed record #980
Processed record #981
Processed record #982
Processed record #983
Processed record #984
Processed record #985
Processed record #986
Processed record #987
Processed record #988
Processed record #989
Processed record #990
Processed record #991
Processed record #992
Processed record #993
Processed record #994
Processed record #995
Processed record #996
Processed record #997
Processed record #998
Processed record #999
Processed record #1000
Processed record #1001
Processed record #1002
Processed record #1003
Processed record #1004
Processed record #1005
Processed record #1006
Processed record #1007
Processed record #1008
Processed record #1009
Processed record #1010
Processed record #1011
Processed record #1012
Processed record #1013
Processed record #1014
Processed record #1015
Processed record #1016
Processed record #1017
Processed record #1018
Processed record #1019
Processed record #1020
Processed record #1021
Processed record #1022
Processed record #1023
Processed record #1024
Processed record #1025
Processed record #1026
Processed record #1027
Processed record #1028
Processed record #1029
Processed record #1030
Processed record #1031
Processed record #1032
Processed record #1033
Processed record #1034
Processed record #1035
Processed record #1036
Processed record #1037
Processed record #1038
Processed record #1039
Processed record #1040
Processed record #1041
Processed record #1042
Processed record #1043
Processed record #1044
Processed record #1045
Processed record #1046
Processed record #1047
Processed record #1048
Processed record #1049
Processed record #1050
Processed record #1051
Processed record #1052
Processed record #1053
Processed record #1054
Processed record #1055
Processed record #1056
Processed record #1057
Processed record #1058
Processed record #1059
Processed record #1060
Processed record #1061
Processed record #1062
Processed record #1063
Processed record #1064
Processed record #1065
Processed record #1066
Processed record #1067
Processed record #1068
Processed record #1069
Processed record #1070
Processed record #1071
Processed record #1072
Processed record #1073
Processed record #1074
Processed record #1075
Processed record #1076
Processed record #1077
Processed record #1078
Processed record #1079
Processed record #1080
Processed record #1081
Processed record #1082
Processed record #1083
Processed record #1084
Processed record #1085
Processed record #1086
Processed record #1087
Processed record #1088
Processed record #1089
Processed record #1090
Processed record #1091
Processed record #1092
Processed record #1093
Processed record #1094
Processed record #1095
Processed record #1096
Processed record #1097
Processed record #1098
Processed record #1099
Processed record #1100
Processed record #1101
Processed record #1102
Processed record #1103
Processed record #1104
Processed record #1105
Processed record #1106
Processed record #1107
Processed record #1108
Processed record #1109
Processed record #1110
Processed record #1111
Processed record #1112
Processed record #1113
Processed record #1114
Processed record #1115
Processed record #1116
Processed record #1117
Processed record #1118

Processed record #1119
Processed record #1120
Processed record #1121
Processed record #1122
Processed record #1123
Processed record #1124
Processed record #1125
Processed record #1126
Processed record #1127
Processed record #1128
Processed record #1129
Processed record #1130
Processed record #1131
Processed record #1132
Processed record #1133
Processed record #1134
Processed record #1135
Processed record #1136
Processed record #1137
Processed record #1138
Processed record #1139
Processed record #1140
Processed record #1141
Processed record #1142
Processed record #1143
Processed record #1144
Processed record #1145
Processed record #1146
Processed record #1147
Processed record #1148
Processed record #1149
Processed record #1150
Processed record #1151
Processed record #1152
Processed record #1153
Processed record #1154
Processed record #1155
Processed record #1156
Processed record #1157
Processed record #1158
Processed record #1159
Processed record #1160
Processed record #1161
Processed record #1162
Processed record #1163
Processed record #1164
Processed record #1165
Processed record #1166
Processed record #1167
Processed record #1168
Processed record #1169
Processed record #1170
Processed record #1171
Processed record #1172
Processed record #1173
Processed record #1174
Processed record #1175
Processed record #1176
Processed record #1177
Processed record #1178
Processed record #1179
Processed record #1180
Processed record #1181
Processed record #1182
Processed record #1183
Processed record #1184
Processed record #1185
Processed record #1186
Processed record #1187
Processed record #1188
Processed record #1189
Processed record #1190
Processed record #1191
Processed record #1192
Processed record #1193
Processed record #1194
Processed record #1195
Processed record #1196
Processed record #1197
Processed record #1198
Processed record #1199
Processed record #1200
Processed record #1201
Processed record #1202
Processed record #1203
Processed record #1204
Processed record #1205
Processed record #1206
Processed record #1207
Processed record #1208
Processed record #1209
Processed record #1210
Processed record #1211
Processed record #1212
Processed record #1213
Processed record #1214
Processed record #1215
Processed record #1216
Processed record #1217
Processed record #1218
Processed record #1219
Processed record #1220
Processed record #1221
Processed record #1222
Processed record #1223
Processed record #1224
Processed record #1225
Processed record #1226
Processed record #1227
Processed record #1228
Processed record #1229
Processed record #1230
Processed record #1231
Processed record #1232
Processed record #1233
Processed record #1234
Processed record #1235
Processed record #1236
Processed record #1237
Processed record #1238
Processed record #1239
Processed record #1240
Processed record #1241
Processed record #1242
Processed record #1243
Processed record #1244
Processed record #1245
Processed record #1246
Processed record #1247
Processed record #1248
Processed record #1249
Processed record #1250
Processed record #1251
Processed record #1252
Processed record #1253
Processed record #1254
Processed record #1255
Processed record #1256
Processed record #1257
Processed record #1258
Processed record #1259
Processed record #1260
Processed record #1261
Processed record #1262
Processed record #1263
Processed record #1264
Processed record #1265
Processed record #1266
Processed record #1267
Processed record #1268
Processed record #1269
Processed record #1270
Processed record #1271
Processed record #1272
Processed record #1273
Processed record #1274
Processed record #1275
Processed record #1276
Processed record #1277
Processed record #1278
Processed record #1279
Processed record #1280
Processed record #1281
Processed record #1282
Processed record #1283
Processed record #1284
Processed record #1285
Processed record #1286
Processed record #1287
Processed record #1288
Processed record #1289
Processed record #1290
Processed record #1291
Processed record #1292
Processed record #1293
Processed record #1294
Processed record #1295
Processed record #1296
Processed record #1297
Processed record #1298
Processed record #1299
Processed record #1300
Processed record #1301
Processed record #1302
Processed record #1303
Processed record #1304
Processed record #1305
Processed record #1306
Processed record #1307
Processed record #1308
Processed record #1309
Processed record #1310
Processed record #1311
Processed record #1312
Processed record #1313
Processed record #1314
Processed record #1315
Processed record #1316
Processed record #1317
Processed record #1318
Processed record #1319
Processed record #1320
Processed record #1321
Processed record #1322
Processed record #1323
Processed record #1324
Processed record #1325
Processed record #1326
Processed record #1327
Processed record #1328
Processed record #1329
Processed record #1330
Processed record #1331
Processed record #1332
Processed record #1333
Processed record #1334
Processed record #1335
Processed record #1336
Processed record #1337
Processed record #1338
Processed record #1339
Processed record #1340
Processed record #1341
Processed record #1342
Processed record #1343
Processed record #1344
Processed record #1345
Processed record #1346
Processed record #1347
Processed record #1348
Processed record #1349
Processed record #1350
Processed record #1351
Processed record #1352
Processed record #1353
Processed record #1354
Processed record #1355
Processed record #1356
Processed record #1357
Processed record #1358
Processed record #1359
Processed record #1360
Processed record #1361
Processed record #1362
Processed record #1363
Processed record #1364
Processed record #1365
Processed record #1366
Processed record #1367
Processed record #1368
Processed record #1369
Processed record #1370
Processed record #1371
Processed record #1372
Processed record #1373
Processed record #1374
Processed record #1375
Processed record #1376
Processed record #1377
Processed record #1378
Processed record #1379
Processed record #1380
Processed record #1381
Processed record #1382
Processed record #1383
Processed record #1384
Processed record #1385
Processed record #1386
Processed record #1387
Processed record #1388
Processed record #1389
Processed record #1390
Processed record #1391
Processed record #1392
Processed record #1393
Processed record #1394
Processed record #1395
Processed record #1396
Processed record #1397
Processed record #1398
Processed record #1399
Processed record #1400
Processed record #1401
Processed record #1402
Processed record #1403
Processed record #1404
Processed record #1405
Processed record #1406
Processed record #1407
Processed record #1408
Processed record #1409
Processed record #1410
Processed record #1411
Processed record #1412
Processed record #1413
Processed record #1414
Processed record #1415
Processed record #1416
Processed record #1417
Processed record #1418
Processed record #1419
Processed record #1420
Processed record #1421
Processed record #1422
Processed record #1423
Processed record #1424
Processed record #1425
Processed record #1426
Processed record #1427
Processed record #1428
Processed record #1429
Processed record #1430
Processed record #1431
Processed record #1432
Processed record #1433
Processed record #1434
Processed record #1435
Processed record #1436
Processed record #1437
Processed record #1438
Processed record #1439
Processed record #1440
Processed record #1441
Processed record #1442
Processed record #1443
Processed record #1444
Processed record #1445
Processed record #1446
Processed record #1447
Processed record #1448
Processed record #1449
Processed record #1450
Processed record #1451
Processed record #1452
Processed record #1453
Processed record #1454
Processed record #1455
Processed record #1456
Processed record #1457
Processed record #1458
Processed record #1459
Processed record #1460
Processed record #1461
Processed record #1462
Processed record #1463
Processed record #1464
Processed record #1465
Processed record #1466
Processed record #1467
Processed record #1468
Processed record #1469
Processed record #1470
Processed record #1471
Processed record #1472
Processed record #1473
Processed record #1474
Processed record #1475

Processed record #1476
Processed record #1477
Processed record #1478
Processed record #1479
Processed record #1480
Processed record #1481
Processed record #1482
Processed record #1483
Processed record #1484
Processed record #1485
Processed record #1486
Processed record #1487
Processed record #1488
Processed record #1489
Processed record #1490
Processed record #1491
Processed record #1492
Processed record #1493
Processed record #1494
Processed record #1495
Processed record #1496
Processed record #1497
Processed record #1498
Processed record #1499
Processed record #1500
Processed record #1501
Processed record #1502
Processed record #1503
Processed record #1504
Processed record #1505
Processed record #1506
Processed record #1507
Processed record #1508
Processed record #1509
Processed record #1510
Processed record #1511
Processed record #1512
Processed record #1513
Processed record #1514
Processed record #1515
Processed record #1516
Processed record #1517
Processed record #1518
Processed record #1519
Processed record #1520
Processed record #1521
Processed record #1522
Processed record #1523
Processed record #1524
Processed record #1525
Processed record #1526
Processed record #1527
Processed record #1528
Processed record #1529
Processed record #1530
Processed record #1531
Processed record #1532
Processed record #1533
Processed record #1534
Processed record #1535
Processed record #1536
Processed record #1537
Processed record #1538
Processed record #1539
Processed record #1540
Processed record #1541
Processed record #1542
Processed record #1543
Processed record #1544
Processed record #1545
Processed record #1546
Processed record #1547
Processed record #1548
Processed record #1549
Processed record #1550
Processed record #1551
Processed record #1552
Processed record #1553
Processed record #1554
Processed record #1555
Processed record #1556
Processed record #1557
Processed record #1558
Processed record #1559
Processed record #1560
Processed record #1561
Processed record #1562
Processed record #1563
Processed record #1564
Processed record #1565
Processed record #1566
Processed record #1567
Processed record #1568
Processed record #1569
Processed record #1570
Processed record #1571
Processed record #1572
Processed record #1573
Processed record #1574
Processed record #1575
Processed record #1576
Processed record #1577
Processed record #1578
Processed record #1579
Processed record #1580
Processed record #1581
Processed record #1582
Processed record #1583
Processed record #1584
Processed record #1585
Processed record #1586
Processed record #1587
Processed record #1588
Processed record #1589
Processed record #1590
Processed record #1591
Processed record #1592
Processed record #1593
Processed record #1594
Processed record #1595
Processed record #1596
Processed record #1597
Processed record #1598
Processed record #1599
Processed record #1600
Processed record #1601
Processed record #1602
Processed record #1603
Processed record #1604
Processed record #1605
Processed record #1606
Processed record #1607
Processed record #1608
Processed record #1609
Processed record #1610
Processed record #1611
Processed record #1612
Processed record #1613
Processed record #1614
Processed record #1615
Processed record #1616
Processed record #1617
Processed record #1618
Processed record #1619
Processed record #1620
Processed record #1621
Processed record #1622
Processed record #1623
Processed record #1624
Processed record #1625
Processed record #1626
Processed record #1627
Processed record #1628
Processed record #1629
Processed record #1630
Processed record #1631
Processed record #1632
Processed record #1633
Processed record #1634
Processed record #1635
Processed record #1636
Processed record #1637
Processed record #1638
Processed record #1639
Processed record #1640
Processed record #1641
Processed record #1642
Processed record #1643
Processed record #1644
Processed record #1645
Processed record #1646
Processed record #1647
Processed record #1648
Processed record #1649
Processed record #1650
Processed record #1651
Processed record #1652
Processed record #1653
Processed record #1654
Processed record #1655
Processed record #1656
Processed record #1657
Processed record #1658
Processed record #1659
Processed record #1660
Processed record #1661
Processed record #1662
Processed record #1663
Processed record #1664
Processed record #1665
Processed record #1666
Processed record #1667
Processed record #1668
Processed record #1669
Processed record #1670
Processed record #1671
Processed record #1672
Processed record #1673
Processed record #1674
Processed record #1675
Processed record #1676
Processed record #1677
Processed record #1678
Processed record #1679
Processed record #1680
Processed record #1681
Processed record #1682
Processed record #1683
Processed record #1684
Processed record #1685
Processed record #1686
Processed record #1687
Processed record #1688
Processed record #1689
Processed record #1690
Processed record #1691
Processed record #1692
Processed record #1693
Processed record #1694
Processed record #1695
Processed record #1696
Processed record #1697
Processed record #1698
Processed record #1699
Processed record #1700
Processed record #1701
Processed record #1702
Processed record #1703
Processed record #1704
Processed record #1705
Processed record #1706
Processed record #1707
Processed record #1708
Processed record #1709
Processed record #1710
Processed record #1711
Processed record #1712
Processed record #1713
Processed record #1714
Processed record #1715
Processed record #1716
Processed record #1717
Processed record #1718
Processed record #1719
Processed record #1720
Processed record #1721
Processed record #1722
Processed record #1723
Processed record #1724
Processed record #1725
Processed record #1726
Processed record #1727
Processed record #1728
Processed record #1729
Processed record #1730
Processed record #1731
Processed record #1732
Processed record #1733
Processed record #1734
Processed record #1735
Processed record #1736
Processed record #1737
Processed record #1738
Processed record #1739
Processed record #1740
Processed record #1741
Processed record #1742
Processed record #1743
Processed record #1744
Processed record #1745
Processed record #1746
Processed record #1747
Processed record #1748
Processed record #1749
Processed record #1750
Processed record #1751
Processed record #1752
Processed record #1753
Processed record #1754
Processed record #1755
Processed record #1756
Processed record #1757
Processed record #1758
Processed record #1759
Processed record #1760
Processed record #1761
Processed record #1762
Processed record #1763
Processed record #1764
Processed record #1765
Processed record #1766
Processed record #1767
Processed record #1768
Processed record #1769
Processed record #1770
Processed record #1771
Processed record #1772
Processed record #1773
Processed record #1774
Processed record #1775
Processed record #1776
Processed record #1777
Processed record #1778
Processed record #1779
Processed record #1780
Processed record #1781
Processed record #1782
Processed record #1783
Processed record #1784
Processed record #1785
Processed record #1786
Processed record #1787
Processed record #1788
Processed record #1789
Processed record #1790
Processed record #1791
Processed record #1792
Processed record #1793
Processed record #1794
Processed record #1795
Processed record #1796
Processed record #1797
Processed record #1798
Processed record #1799
Processed record #1800
Processed record #1801
Processed record #1802
Processed record #1803
Processed record #1804
Processed record #1805
Processed record #1806
Processed record #1807
Processed record #1808
Processed record #1809
Processed record #1810
Processed record #1811
Processed record #1812
Processed record #1813
Processed record #1814
Processed record #1815
Processed record #1816
Processed record #1817
Processed record #1818
Processed record #1819
Processed record #1820
Processed record #1821
Processed record #1822
Processed record #1823
Processed record #1824
Processed record #1825
Processed record #1826
Processed record #1827
Processed record #1828
Processed record #1829
Processed record #1830
Processed record #1831
Processed record #1832

Processed record #1833
Processed record #1834
Processed record #1835
Processed record #1836
Processed record #1837
Processed record #1838
Processed record #1839
Processed record #1840
Processed record #1841
Processed record #1842
Processed record #1843
Processed record #1844
Processed record #1845
Processed record #1846
Processed record #1847
Processed record #1848
Processed record #1849
Processed record #1850
Processed record #1851
Processed record #1852
Processed record #1853
Processed record #1854
Processed record #1855
Processed record #1856
Processed record #1857
Processed record #1858
Processed record #1859
Processed record #1860
Processed record #1861
Processed record #1862
Processed record #1863
Processed record #1864
Processed record #1865
Processed record #1866
Processed record #1867
Processed record #1868
Processed record #1869
Processed record #1870
Processed record #1871
Processed record #1872
Processed record #1873
Processed record #1874
Processed record #1875
Processed record #1876
Processed record #1877
Processed record #1878
Processed record #1879
Processed record #1880
Processed record #1881
Processed record #1882
Processed record #1883
Processed record #1884
Processed record #1885
Processed record #1886
Processed record #1887
Processed record #1888
Processed record #1889
Processed record #1890
Processed record #1891
Processed record #1892
Processed record #1893
Processed record #1894
Processed record #1895
Processed record #1896
Processed record #1897
Processed record #1898
Processed record #1899
Processed record #1900
Processed record #1901
Processed record #1902
Processed record #1903
Processed record #1904
Processed record #1905
Processed record #1906
Processed record #1907
Processed record #1908
Processed record #1909
Processed record #1910
Processed record #1911
Processed record #1912
Processed record #1913
Processed record #1914
Processed record #1915
Processed record #1916
Processed record #1917
Processed record #1918
Processed record #1919
Processed record #1920
Processed record #1921
Processed record #1922
Processed record #1923
Processed record #1924
Processed record #1925
Processed record #1926
Processed record #1927
Processed record #1928
Processed record #1929
Processed record #1930
Processed record #1931
Processed record #1932
Processed record #1933
Processed record #1934
Processed record #1935
Processed record #1936
Processed record #1937
Processed record #1938
Processed record #1939
Processed record #1940
Processed record #1941
Processed record #1942
Processed record #1943
Processed record #1944
Processed record #1945
Processed record #1946
Processed record #1947
Processed record #1948
Processed record #1949
Processed record #1950
Processed record #1951
Processed record #1952
Processed record #1953
Processed record #1954
Processed record #1955
Processed record #1956
Processed record #1957
Processed record #1958
Processed record #1959
Processed record #1960
Processed record #1961
Processed record #1962
Processed record #1963
Processed record #1964
Processed record #1965
Processed record #1966
Processed record #1967
Processed record #1968
Processed record #1969
Processed record #1970
Processed record #1971
Processed record #1972
Processed record #1973
Processed record #1974
Processed record #1975
Processed record #1976
Processed record #1977
Processed record #1978
Processed record #1979
Processed record #1980
Processed record #1981
Processed record #1982
Processed record #1983
Processed record #1984
Processed record #1985
Processed record #1986
Processed record #1987
Processed record #1988
Processed record #1989
Processed record #1990
Processed record #1991
Processed record #1992
Processed record #1993
Processed record #1994
Processed record #1995
Processed record #1996
Processed record #1997
Processed record #1998
Processed record #1999
Processed record #2000
Processed record #2001
Processed record #2002
Processed record #2003
Processed record #2004
Processed record #2005
Processed record #2006
Processed record #2007
Processed record #2008
Processed record #2009
Processed record #2010
Processed record #2011
Processed record #2012
Processed record #2013
Processed record #2014
Processed record #2015
Processed record #2016
Processed record #2017
Processed record #2018
Processed record #2019
Processed record #2020
Processed record #2021
Processed record #2022
Processed record #2023
Processed record #2024
Processed record #2025
Processed record #2026
Processed record #2027
Processed record #2028
Processed record #2029
Processed record #2030
Processed record #2031
Processed record #2032
Processed record #2033
Processed record #2034
Processed record #2035
Processed record #2036
Processed record #2037
Processed record #2038
Processed record #2039
Processed record #2040
Processed record #2041
Processed record #2042
Processed record #2043
Processed record #2044
Processed record #2045
Processed record #2046
Processed record #2047
Processed record #2048
Processed record #2049
Processed record #2050
Processed record #2051
Processed record #2052
Processed record #2053
Processed record #2054
Processed record #2055
Processed record #2056
Processed record #2057
Processed record #2058
Processed record #2059
Processed record #2060
Processed record #2061
Processed record #2062
Processed record #2063
Processed record #2064
Processed record #2065
Processed record #2066
Processed record #2067
Processed record #2068
Processed record #2069
Processed record #2070
Processed record #2071
Processed record #2072
Processed record #2073
Processed record #2074
Processed record #2075
Processed record #2076
Processed record #2077
Processed record #2078
Processed record #2079
Processed record #2080
Processed record #2081
Processed record #2082
Processed record #2083
Processed record #2084
Processed record #2085
Processed record #2086
Processed record #2087
Processed record #2088
Processed record #2089
Processed record #2090
Processed record #2091
Processed record #2092
Processed record #2093
Processed record #2094
Processed record #2095
Processed record #2096
Processed record #2097
Processed record #2098
Processed record #2099
Processed record #2100
Processed record #2101
Processed record #2102
Processed record #2103
Processed record #2104
Processed record #2105
Processed record #2106
Processed record #2107
Processed record #2108
Processed record #2109
Processed record #2110
Processed record #2111
Processed record #2112
Processed record #2113
Processed record #2114
Processed record #2115
Processed record #2116
Processed record #2117
Processed record #2118
Processed record #2119
Processed record #2120
Processed record #2121
Processed record #2122
Processed record #2123
Processed record #2124
Processed record #2125
Processed record #2126
Processed record #2127
Processed record #2128
Processed record #2129
Processed record #2130
Processed record #2131
Processed record #2132
Processed record #2133
Processed record #2134
Processed record #2135
Processed record #2136
Processed record #2137
Processed record #2138
Processed record #2139
Processed record #2140
Processed record #2141
Processed record #2142
Processed record #2143
Processed record #2144
Processed record #2145
Processed record #2146
Processed record #2147
Processed record #2148
Processed record #2149
Processed record #2150
Processed record #2151
Processed record #2152
Processed record #2153
Processed record #2154
Processed record #2155
Processed record #2156
Processed record #2157
Processed record #2158
Processed record #2159
Processed record #2160
Processed record #2161
Processed record #2162
Processed record #2163
Processed record #2164
Processed record #2165
Processed record #2166
Processed record #2167
Processed record #2168
Processed record #2169
Processed record #2170
Processed record #2171
Processed record #2172
Processed record #2173
Processed record #2174
Processed record #2175
Processed record #2176
Processed record #2177
Processed record #2178
Processed record #2179
Processed record #2180
Processed record #2181
Processed record #2182
Processed record #2183
Processed record #2184
Processed record #2185
Processed record #2186
Processed record #2187
Processed record #2188
Processed record #2189

Processed record #2190
Processed record #2191
Processed record #2192
Processed record #2193
Processed record #2194
Processed record #2195
Processed record #2196
Processed record #2197
Processed record #2198
Processed record #2199
Processed record #2200
Processed record #2201
Processed record #2202
Processed record #2203
Processed record #2204
Processed record #2205
Processed record #2206
Processed record #2207
Processed record #2208
Processed record #2209
Processed record #2210
Processed record #2211
Processed record #2212
Processed record #2213
Processed record #2214
Processed record #2215
Processed record #2216
Processed record #2217
Processed record #2218
Processed record #2219
Processed record #2220
Processed record #2221
Processed record #2222
Processed record #2223
Processed record #2224
Processed record #2225
Processed record #2226
Processed record #2227
Processed record #2228
Processed record #2229
Processed record #2230
Processed record #2231
Processed record #2232
Processed record #2233
Processed record #2234
Processed record #2235
Processed record #2236
Processed record #2237
Processed record #2238
Processed record #2239
Processed record #2240
Processed record #2241
Processed record #2242
Processed record #2243
Processed record #2244
Processed record #2245
Processed record #2246
Processed record #2247
Processed record #2248
Processed record #2249
Processed record #2250
Processed record #2251
Processed record #2252
Processed record #2253
Processed record #2254
Processed record #2255
Processed record #2256
Processed record #2257
Processed record #2258
Processed record #2259
Processed record #2260
Processed record #2261
Processed record #2262
Processed record #2263
Processed record #2264
Processed record #2265
Processed record #2266
Processed record #2267
Processed record #2268
Processed record #2269
Processed record #2270
Processed record #2271
Processed record #2272
Processed record #2273
Processed record #2274
Processed record #2275
Processed record #2276
Processed record #2277
Processed record #2278
Processed record #2279
Processed record #2280
Processed record #2281
Processed record #2282
Processed record #2283
Processed record #2284
Processed record #2285
Processed record #2286
Processed record #2287
Processed record #2288
Processed record #2289
Processed record #2290
Processed record #2291
Processed record #2292
Processed record #2293
Processed record #2294
Processed record #2295
Processed record #2296
Processed record #2297
Processed record #2298
Processed record #2299
Processed record #2300
Processed record #2301
Processed record #2302
Processed record #2303
Processed record #2304
Processed record #2305
Processed record #2306
Processed record #2307
Processed record #2308
Processed record #2309
Processed record #2310
Processed record #2311
Processed record #2312
Processed record #2313
Processed record #2314
Processed record #2315
Processed record #2316
Processed record #2317
Processed record #2318
Processed record #2319
Processed record #2320
Processed record #2321
Processed record #2322
Processed record #2323
Processed record #2324
Processed record #2325
Processed record #2326
Processed record #2327
Processed record #2328
Processed record #2329
Processed record #2330
Processed record #2331
Processed record #2332
Processed record #2333
Processed record #2334
Processed record #2335
Processed record #2336
Processed record #2337
Processed record #2338
Processed record #2339
Processed record #2340
Processed record #2341
Processed record #2342
Processed record #2343
Processed record #2344
Processed record #2345
Processed record #2346
Processed record #2347
Processed record #2348
Processed record #2349
Processed record #2350
Processed record #2351
Processed record #2352
Processed record #2353
Processed record #2354
Processed record #2355
Processed record #2356
Processed record #2357
Processed record #2358
Processed record #2359
Processed record #2360
Processed record #2361
Processed record #2362
Processed record #2363
Processed record #2364
Processed record #2365
Processed record #2366
Processed record #2367
Processed record #2368
Processed record #2369
Processed record #2370
Processed record #2371
Processed record #2372
Processed record #2373
Processed record #2374
Processed record #2375
Processed record #2376
Processed record #2377
Processed record #2378
Processed record #2379
Processed record #2380
Processed record #2381
Processed record #2382
Processed record #2383
Processed record #2384
Processed record #2385
Processed record #2386
Processed record #2387
Processed record #2388
Processed record #2389
Processed record #2390
Processed record #2391
Processed record #2392
Processed record #2393
Processed record #2394
Processed record #2395
Processed record #2396
Processed record #2397
Processed record #2398
Processed record #2399
Processed record #2400
Processed record #2401
Processed record #2402
Processed record #2403
Processed record #2404
Processed record #2405
Processed record #2406
Processed record #2407
Processed record #2408
Processed record #2409
Processed record #2410
Processed record #2411
Processed record #2412
Processed record #2413
Processed record #2414
Processed record #2415
Processed record #2416
Processed record #2417
Processed record #2418
Processed record #2419
Processed record #2420
Processed record #2421
Processed record #2422
Processed record #2423
Processed record #2424
Processed record #2425
Processed record #2426
Processed record #2427
Processed record #2428
Processed record #2429
Processed record #2430
Processed record #2431
Processed record #2432
Processed record #2433
Processed record #2434
Processed record #2435
Processed record #2436
Processed record #2437
Processed record #2438
Processed record #2439
Processed record #2440
Processed record #2441
Processed record #2442
Processed record #2443
Processed record #2444
Processed record #2445
Processed record #2446
Processed record #2447
Processed record #2448
Processed record #2449
Processed record #2450
Processed record #2451
Processed record #2452
Processed record #2453
Processed record #2454
Processed record #2455
Processed record #2456
Processed record #2457
Processed record #2458
Processed record #2459
Processed record #2460
Processed record #2461
Processed record #2462
Processed record #2463
Processed record #2464
Processed record #2465
Processed record #2466
Processed record #2467
Processed record #2468
Processed record #2469
Processed record #2470
Processed record #2471
Processed record #2472
Processed record #2473
Processed record #2474
Processed record #2475
Processed record #2476
Processed record #2477
Processed record #2478
Processed record #2479
Processed record #2480
Processed record #2481
Processed record #2482
Processed record #2483
Processed record #2484
Processed record #2485
Processed record #2486
Processed record #2487
Processed record #2488
Processed record #2489
Processed record #2490
Processed record #2491
Processed record #2492
Processed record #2493
Processed record #2494
Processed record #2495
Processed record #2496
Processed record #2497
Processed record #2498
Processed record #2499
Processed record #2500
Processed record #2501
Processed record #2502
Processed record #2503
Processed record #2504
Processed record #2505
Processed record #2506
Processed record #2507
Processed record #2508
Processed record #2509
Processed record #2510
Processed record #2511
Processed record #2512
Processed record #2513
Processed record #2514
Processed record #2515
Processed record #2516
Processed record #2517
Processed record #2518
Processed record #2519
Processed record #2520
Processed record #2521
Processed record #2522
Processed record #2523
Processed record #2524
Processed record #2525
Processed record #2526
Processed record #2527
Processed record #2528
Processed record #2529
Processed record #2530
Processed record #2531
Processed record #2532
Processed record #2533
Processed record #2534
Processed record #2535
Processed record #2536
Processed record #2537
Processed record #2538
Processed record #2539
Processed record #2540
Processed record #2541
Processed record #2542
Processed record #2543
Processed record #2544
Processed record #2545
Processed record #2546

Processed record #2547
Processed record #2548
Processed record #2549
Processed record #2550
Processed record #2551
Processed record #2552
Processed record #2553
Processed record #2554
Processed record #2555
Processed record #2556
Processed record #2557
Processed record #2558
Processed record #2559
Processed record #2560
Processed record #2561
Processed record #2562
Processed record #2563
Processed record #2564
Processed record #2565
Processed record #2566
Processed record #2567
Processed record #2568
Processed record #2569
Processed record #2570
Processed record #2571
Processed record #2572
Processed record #2573
Processed record #2574
Processed record #2575
Processed record #2576
Processed record #2577
Processed record #2578
Processed record #2579
Processed record #2580
Processed record #2581
Processed record #2582
Processed record #2583
Processed record #2584
Processed record #2585
Processed record #2586
Processed record #2587
Processed record #2588
Processed record #2589
Processed record #2590
Processed record #2591
Processed record #2592
Processed record #2593
Processed record #2594
Processed record #2595
Processed record #2596
Processed record #2597
Processed record #2598
Processed record #2599
Processed record #2600
Processed record #2601
Processed record #2602
Processed record #2603
Processed record #2604
Processed record #2605
Processed record #2606
Processed record #2607
Processed record #2608
Processed record #2609
Processed record #2610
Processed record #2611
Processed record #2612
Processed record #2613
Processed record #2614
Processed record #2615
Processed record #2616
Processed record #2617
Processed record #2618
Processed record #2619
Processed record #2620
Processed record #2621
Processed record #2622
Processed record #2623
Processed record #2624
Processed record #2625
Processed record #2626
Processed record #2627
Processed record #2628
Processed record #2629
Processed record #2630
Processed record #2631
Did not work. Skipping...
Processed record #2632
Processed record #2633
Processed record #2634
Processed record #2635
Processed record #2636
Processed record #2637
Processed record #2638
Processed record #2639
Processed record #2640
Processed record #2641
Processed record #2642
Processed record #2643
Processed record #2644
Processed record #2645
Processed record #2646
Processed record #2647
Processed record #2648
Processed record #2649
Processed record #2650
Processed record #2651
Processed record #2652
Processed record #2653
Processed record #2654
Processed record #2655
Processed record #2656
Processed record #2657
Processed record #2658
Processed record #2659
Processed record #2660
Processed record #2661
Processed record #2662
Processed record #2663
Processed record #2664
Processed record #2665
Processed record #2666
Processed record #2667
Processed record #2668
Processed record #2669
Processed record #2670
Processed record #2671
Processed record #2672
Processed record #2673
Processed record #2674
Processed record #2675
Processed record #2676
Processed record #2677
Processed record #2678
Processed record #2679
Processed record #2680
Processed record #2681
Processed record #2682
Processed record #2683
Processed record #2684
Processed record #2685
Processed record #2686
Processed record #2687
Processed record #2688
Processed record #2689
Processed record #2690
Processed record #2691
Processed record #2692
Processed record #2693
Processed record #2694
Processed record #2695
Processed record #2696
Processed record #2697
Processed record #2698
Processed record #2699
Processed record #2700
Processed record #2701
Processed record #2702
Processed record #2703
Processed record #2704
Processed record #2705
Processed record #2706
Processed record #2707
Processed record #2708
Processed record #2709
Processed record #2710
Processed record #2711
Processed record #2712
Processed record #2713
Processed record #2714
Processed record #2715
Processed record #2716
Processed record #2717
Processed record #2718
Processed record #2719
Processed record #2720
Processed record #2721
Processed record #2722
Processed record #2723
Processed record #2724
Processed record #2725
Processed record #2726
Processed record #2727
Processed record #2728
Processed record #2729
Processed record #2730
Processed record #2731
Processed record #2732
Processed record #2733
Processed record #2734
Processed record #2735
Processed record #2736
Processed record #2737
Processed record #2738
Processed record #2739
Processed record #2740
Processed record #2741
Processed record #2742
Processed record #2743
Processed record #2744
Processed record #2745
Processed record #2746
Processed record #2747
Processed record #2748
Processed record #2749
Processed record #2750
Processed record #2751
Processed record #2752
Processed record #2753
Processed record #2754
Processed record #2755
Processed record #2756
Processed record #2757
Processed record #2758
Processed record #2759
Processed record #2760
Processed record #2761
Processed record #2762
Processed record #2763
Processed record #2764
Processed record #2765
Processed record #2766
Processed record #2767
Processed record #2768
Processed record #2769
Processed record #2770
Processed record #2771
Processed record #2772
Processed record #2773
Processed record #2774
Processed record #2775
Processed record #2776
Processed record #2777
Processed record #2778
Processed record #2779
Processed record #2780
Processed record #2781
Processed record #2782
Processed record #2783
Processed record #2784
Processed record #2785
Processed record #2786
Processed record #2787
Processed record #2788
Processed record #2789
Processed record #2790
Processed record #2791
Processed record #2792
Processed record #2793
Processed record #2794
Processed record #2795
Processed record #2796
Processed record #2797
Processed record #2798
Processed record #2799
Processed record #2800
Processed record #2801
Processed record #2802
Processed record #2803
Processed record #2804
Processed record #2805
Processed record #2806
Processed record #2807
Processed record #2808
Processed record #2809
Processed record #2810
Processed record #2811
Processed record #2812
Processed record #2813
Processed record #2814
Processed record #2815
Processed record #2816
Processed record #2817
Processed record #2818
Processed record #2819
Processed record #2820
Processed record #2821
Processed record #2822
Processed record #2823
Processed record #2824
Processed record #2825
Processed record #2826
Processed record #2827
Processed record #2828
Processed record #2829
Processed record #2830
Processed record #2831
Processed record #2832
Processed record #2833
Processed record #2834
Processed record #2835
Processed record #2836
Processed record #2837
Processed record #2838
Processed record #2839
Processed record #2840
Processed record #2841
Processed record #2842
Processed record #2843
Processed record #2844
Processed record #2845
Processed record #2846
Processed record #2847
Processed record #2848
Processed record #2849
Processed record #2850
Processed record #2851
Processed record #2852
Processed record #2853
Processed record #2854
Processed record #2855
Processed record #2856
Processed record #2857
Processed record #2858
Processed record #2859
Processed record #2860
Processed record #2861
Processed record #2862
Processed record #2863
Processed record #2864
Processed record #2865
Processed record #2866
Processed record #2867
Processed record #2868
Processed record #2869
Processed record #2870
Processed record #2871
Processed record #2872
Processed record #2873
Processed record #2874
Processed record #2875
Processed record #2876
Processed record #2877
Processed record #2878
Processed record #2879
Processed record #2880
Processed record #2881
Processed record #2882
Processed record #2883
Processed record #2884
Processed record #2885
Processed record #2886
Processed record #2887
Processed record #2888
Processed record #2889
Processed record #2890
Processed record #2891
Processed record #2892
Processed record #2893
Processed record #2894
Processed record #2895
Processed record #2896
Processed record #2897
Processed record #2898
Processed record #2899
Processed record #2900
Processed record #2901
Processed record #2902

Processed record #2903
Processed record #2904
Processed record #2905
Processed record #2906
Processed record #2907
Processed record #2908
Processed record #2909
Processed record #2910
Processed record #2911
Processed record #2912
Processed record #2913
Processed record #2914
Processed record #2915
Processed record #2916
Processed record #2917
Processed record #2918
Processed record #2919
Processed record #2920
Processed record #2921
Processed record #2922
Processed record #2923
Processed record #2924
Processed record #2925
Processed record #2926
Processed record #2927
Processed record #2928
Processed record #2929
Processed record #2930
Processed record #2931
Processed record #2932
Processed record #2933
Processed record #2934
Processed record #2935
Processed record #2936
Processed record #2937
Processed record #2938
Processed record #2939
Processed record #2940
Processed record #2941
Processed record #2942
Processed record #2943
Processed record #2944
Processed record #2945
Processed record #2946
Processed record #2947
Processed record #2948
Processed record #2949
Processed record #2950
Processed record #2951
Processed record #2952
Processed record #2953
Processed record #2954
Processed record #2955
Processed record #2956
Processed record #2957
Processed record #2958
Processed record #2959
Processed record #2960
Processed record #2961
Processed record #2962
Processed record #2963
Processed record #2964
Processed record #2965
Processed record #2966
Processed record #2967
Processed record #2968
Processed record #2969
Processed record #2970
Processed record #2971
Processed record #2972
Processed record #2973
Processed record #2974
Processed record #2975
Processed record #2976
Processed record #2977
Processed record #2978
Processed record #2979
Processed record #2980
Processed record #2981
Processed record #2982
Processed record #2983
Processed record #2984
Processed record #2985
Processed record #2986
Processed record #2987
Processed record #2988
Processed record #2989
Processed record #2990
Processed record #2991
Processed record #2992
Processed record #2993
Processed record #2994
Processed record #2995
Processed record #2996
Processed record #2997
Processed record #2998
Processed record #2999
Processed record #3000
Processed record #3001
Processed record #3002
Processed record #3003
Processed record #3004
Processed record #3005
Processed record #3006
Processed record #3007
Processed record #3008
Processed record #3009
Processed record #3010
Processed record #3011
Processed record #3012
Processed record #3013
Processed record #3014
Processed record #3015
Processed record #3016
Processed record #3017
Processed record #3018
Processed record #3019
Processed record #3020
Processed record #3021
Processed record #3022
Processed record #3023
Processed record #3024
Processed record #3025
Processed record #3026
Processed record #3027
Processed record #3028
Processed record #3029
Processed record #3030
Processed record #3031
Processed record #3032
Processed record #3033
Processed record #3034
Processed record #3035
Processed record #3036
Processed record #3037
Processed record #3038
Processed record #3039
Processed record #3040
Processed record #3041
Processed record #3042
Processed record #3043
Processed record #3044
Processed record #3045
Processed record #3046
Processed record #3047
Processed record #3048
Processed record #3049
Processed record #3050
Processed record #3051
Processed record #3052
Processed record #3053
Processed record #3054
Processed record #3055
Processed record #3056
Processed record #3057
Processed record #3058
Processed record #3059
Processed record #3060
Processed record #3061
Processed record #3062
Processed record #3063
Processed record #3064
Processed record #3065
Processed record #3066
Processed record #3067
Processed record #3068
Processed record #3069
Processed record #3070
Processed record #3071
Processed record #3072
Processed record #3073
Processed record #3074
Processed record #3075
Processed record #3076
Processed record #3077
Processed record #3078
Processed record #3079
Processed record #3080
Processed record #3081
Processed record #3082
Processed record #3083
Processed record #3084
Processed record #3085
Processed record #3086
Processed record #3087
Processed record #3088
Processed record #3089
Processed record #3090
Processed record #3091
Processed record #3092
Processed record #3093
Processed record #3094
Processed record #3095
Processed record #3096
Processed record #3097
Processed record #3098
Processed record #3099
Processed record #3100
Processed record #3101
Processed record #3102
Processed record #3103
Processed record #3104
Processed record #3105
Processed record #3106
Processed record #3107
Processed record #3108
Processed record #3109
Processed record #3110
Processed record #3111
Processed record #3112
Processed record #3113
Processed record #3114
Processed record #3115
Processed record #3116
Processed record #3117
Processed record #3118
Processed record #3119
Processed record #3120
Processed record #3121
Processed record #3122
Processed record #3123
Processed record #3124
Processed record #3125
Processed record #3126
Processed record #3127
Processed record #3128
Processed record #3129
Processed record #3130
Processed record #3131
Processed record #3132
Processed record #3133
Processed record #3134
Processed record #3135
Processed record #3136
Processed record #3137
Processed record #3138
Processed record #3139
Processed record #3140
Processed record #3141
Processed record #3142
Processed record #3143
Processed record #3144
Processed record #3145
Processed record #3146
Processed record #3147
Processed record #3148
Processed record #3149
Processed record #3150
Processed record #3151
Processed record #3152
Processed record #3153
Processed record #3154
Processed record #3155
Processed record #3156
Processed record #3157
Processed record #3158
Processed record #3159
Processed record #3160
Processed record #3161
Processed record #3162
Processed record #3163
Processed record #3164
Processed record #3165
Processed record #3166
Processed record #3167
Processed record #3168
Processed record #3169
Processed record #3170
Processed record #3171
Processed record #3172
Processed record #3173
Processed record #3174
Processed record #3175
Processed record #3176
Processed record #3177
Processed record #3178
Processed record #3179
Processed record #3180
Processed record #3181
Processed record #3182
Processed record #3183
Processed record #3184
Processed record #3185
Processed record #3186
Processed record #3187
Processed record #3188
Processed record #3189
Processed record #3190
Processed record #3191
Processed record #3192
Processed record #3193
Processed record #3194
Processed record #3195
Processed record #3196
Processed record #3197
Processed record #3198
Processed record #3199
Processed record #3200
Processed record #3201
Processed record #3202
Processed record #3203
Processed record #3204
Processed record #3205
Processed record #3206
Processed record #3207
Did not work. Skipping...
Processed record #3208
Processed record #3209
Processed record #3210
Processed record #3211
Processed record #3212
Processed record #3213
Processed record #3214
Processed record #3215
Processed record #3216
Processed record #3217
Processed record #3218
Processed record #3219
Processed record #3220
Processed record #3221
Processed record #3222
Processed record #3223
Processed record #3224
Processed record #3225
Processed record #3226
Processed record #3227
Processed record #3228
Processed record #3229
Processed record #3230
Processed record #3231
Processed record #3232
Processed record #3233
Processed record #3234
Processed record #3235
Processed record #3236
Processed record #3237
Processed record #3238
Processed record #3239
Processed record #3240
Processed record #3241
Processed record #3242
Processed record #3243
Processed record #3244
Processed record #3245
Processed record #3246
Processed record #3247
Processed record #3248
Processed record #3249
Processed record #3250
Processed record #3251
Processed record #3252
Processed record #3253
Processed record #3254
Processed record #3255
Processed record #3256
Processed record #3257
Processed record #3258

Processed record #3259
Processed record #3260
Processed record #3261
Processed record #3262
Processed record #3263
Processed record #3264
Processed record #3265
Processed record #3266
Processed record #3267
Processed record #3268
Processed record #3269
Processed record #3270
Processed record #3271
Processed record #3272
Processed record #3273
Processed record #3274
Processed record #3275
Processed record #3276
Processed record #3277
Processed record #3278
Processed record #3279
Processed record #3280
Processed record #3281
Processed record #3282
Processed record #3283
Did not work. Skipping...
Processed record #3284
Processed record #3285
Processed record #3286
Processed record #3287
Processed record #3288
Processed record #3289
Did not work. Skipping...
Processed record #3290
Processed record #3291
Processed record #3292
Processed record #3293
Processed record #3294
Processed record #3295
Processed record #3296
Processed record #3297
Processed record #3298
Processed record #3299
Processed record #3300
Processed record #3301
Processed record #3302
Processed record #3303
Processed record #3304
Processed record #3305
Processed record #3306
Processed record #3307
Processed record #3308
Processed record #3309
Processed record #3310
Processed record #3311
Processed record #3312
Processed record #3313
Processed record #3314
Processed record #3315
Processed record #3316
Processed record #3317
Processed record #3318
Processed record #3319
Processed record #3320
Processed record #3321
Processed record #3322
Processed record #3323
Processed record #3324
Processed record #3325
Processed record #3326
Processed record #3327
Processed record #3328
Processed record #3329
Processed record #3330
Processed record #3331
Processed record #3332
Processed record #3333
Processed record #3334
Processed record #3335
Processed record #3336
Processed record #3337
Processed record #3338
Processed record #3339
Processed record #3340
Processed record #3341
Processed record #3342
Processed record #3343
Processed record #3344
Processed record #3345
Processed record #3346
Processed record #3347
Processed record #3348
Processed record #3349
Processed record #3350
Processed record #3351
Processed record #3352
Processed record #3353
Processed record #3354
Processed record #3355
Processed record #3356
Processed record #3357
Processed record #3358
Processed record #3359
Processed record #3360
Processed record #3361
Processed record #3362
Processed record #3363
Processed record #3364
Processed record #3365
Processed record #3366
Processed record #3367
Processed record #3368
Processed record #3369
Processed record #3370
Processed record #3371
Processed record #3372
Processed record #3373
Processed record #3374
Processed record #3375
Processed record #3376
Processed record #3377
Processed record #3378
Processed record #3379
Processed record #3380
Processed record #3381
Processed record #3382
Processed record #3383
Processed record #3384
Processed record #3385
Processed record #3386
Processed record #3387
Processed record #3388
Processed record #3389
Processed record #3390
Processed record #3391
Processed record #3392
Processed record #3393
Processed record #3394
Processed record #3395
Processed record #3396
Processed record #3397
Processed record #3398
Processed record #3399
Processed record #3400
Processed record #3401
Processed record #3402
Processed record #3403
Processed record #3404
Processed record #3405
Processed record #3406
Processed record #3407
Processed record #3408
Processed record #3409
Processed record #3410
Processed record #3411
Processed record #3412
Processed record #3413
Processed record #3414
Processed record #3415
Processed record #3416
Processed record #3417
Processed record #3418
Processed record #3419
Processed record #3420
Processed record #3421
Processed record #3422
Processed record #3423
Processed record #3424
Processed record #3425
Processed record #3426
Processed record #3427
Processed record #3428
Processed record #3429
Processed record #3430
Processed record #3431
Processed record #3432
Processed record #3433
Processed record #3434
Processed record #3435
Processed record #3436
Processed record #3437
Processed record #3438
Processed record #3439
Processed record #3440
Processed record #3441
Processed record #3442
Processed record #3443
Processed record #3444
Processed record #3445
Processed record #3446
Processed record #3447
Processed record #3448
Processed record #3449
Processed record #3450
Processed record #3451
Processed record #3452
Processed record #3453
Processed record #3454
Processed record #3455
Processed record #3456
Processed record #3457
Processed record #3458
Processed record #3459
Processed record #3460
Processed record #3461
Processed record #3462
Processed record #3463
Processed record #3464
Processed record #3465
Processed record #3466
Processed record #3467
Processed record #3468
Processed record #3469
Processed record #3470
Processed record #3471
Processed record #3472
Processed record #3473
Processed record #3474
Processed record #3475
Processed record #3476
Processed record #3477
Processed record #3478
Processed record #3479
Processed record #3480
Processed record #3481
Processed record #3482
Processed record #3483
Processed record #3484
Processed record #3485
Processed record #3486
Processed record #3487
Processed record #3488
Processed record #3489
Processed record #3490
Processed record #3491
Processed record #3492
Processed record #3493
Processed record #3494
Processed record #3495
Processed record #3496
Processed record #3497
Processed record #3498
Processed record #3499
Processed record #3500
Processed record #3501
Processed record #3502
Processed record #3503
Processed record #3504
Processed record #3505
Processed record #3506
Did not work. Skipping...
Processed record #3507
Processed record #3508
Processed record #3509
Processed record #3510
Processed record #3511
Processed record #3512
Processed record #3513
Processed record #3514
Processed record #3515
Processed record #3516
Processed record #3517
Processed record #3518
Processed record #3519
Processed record #3520
Processed record #3521
Processed record #3522
Processed record #3523
Processed record #3524
Processed record #3525
Processed record #3526
Processed record #3527
Processed record #3528
Processed record #3529
Processed record #3530
Processed record #3531
Processed record #3532
Processed record #3533
Processed record #3534
Processed record #3535
Processed record #3536
Processed record #3537
Processed record #3538
Processed record #3539
Processed record #3540
Processed record #3541
Processed record #3542
Processed record #3543
Processed record #3544
Processed record #3545
Processed record #3546
Processed record #3547
Processed record #3548
Processed record #3549
Processed record #3550
Processed record #3551
Processed record #3552
Processed record #3553
Processed record #3554
Processed record #3555
Processed record #3556
Processed record #3557
Processed record #3558
Processed record #3559
Processed record #3560
Processed record #3561
Processed record #3562
Processed record #3563
Processed record #3564
Processed record #3565
Processed record #3566
Processed record #3567
Processed record #3568
Processed record #3569
Processed record #3570
Processed record #3571
Processed record #3572
Processed record #3573
Processed record #3574
Processed record #3575
Processed record #3576
Processed record #3577
Processed record #3578
Processed record #3579
Processed record #3580
Processed record #3581
Processed record #3582
Processed record #3583
Processed record #3584
Processed record #3585
Processed record #3586
Processed record #3587
Processed record #3588
Processed record #3589
Processed record #3590
Processed record #3591
Processed record #3592
Processed record #3593
Processed record #3594
Processed record #3595
Processed record #3596
Processed record #3597
Processed record #3598
Processed record #3599
Processed record #3600
Processed record #3601
Processed record #3602
Processed record #3603
Processed record #3604
Processed record #3605
Processed record #3606
Processed record #3607
Processed record #3608
Processed record #3609
Processed record #3610
Processed record #3611

Processed record #3612
Processed record #3613
Processed record #3614
Processed record #3615
Processed record #3616
Processed record #3617
Processed record #3618
Processed record #3619
Processed record #3620
Processed record #3621
Processed record #3622
Processed record #3623
Processed record #3624
Processed record #3625
Processed record #3626
Processed record #3627
Processed record #3628
Processed record #3629
Processed record #3630
Processed record #3631
Processed record #3632
Processed record #3633
Processed record #3634
Processed record #3635
Processed record #3636
Processed record #3637
Processed record #3638
Processed record #3639
Processed record #3640
Processed record #3641
Processed record #3642
Processed record #3643
Processed record #3644
Processed record #3645
Processed record #3646
Processed record #3647
Processed record #3648
Processed record #3649
Processed record #3650
Processed record #3651
Processed record #3652
Processed record #3653
Processed record #3654
Processed record #3655
Processed record #3656
Processed record #3657
Processed record #3658
Processed record #3659
Processed record #3660
Processed record #3661
Processed record #3662
Processed record #3663
Processed record #3664
Processed record #3665
Processed record #3666
Processed record #3667
Processed record #3668
Processed record #3669
Processed record #3670
Processed record #3671
Processed record #3672
Processed record #3673
Processed record #3674
Processed record #3675
Processed record #3676
Processed record #3677
Processed record #3678
Processed record #3679
Processed record #3680
Processed record #3681
Processed record #3682
Processed record #3683
Processed record #3684
Processed record #3685
Processed record #3686
Processed record #3687
Processed record #3688
Processed record #3689
Processed record #3690
Processed record #3691
Processed record #3692
Processed record #3693
Processed record #3694
Processed record #3695
Processed record #3696
Processed record #3697
Processed record #3698
Processed record #3699
Processed record #3700
Processed record #3701
Processed record #3702
Processed record #3703
Processed record #3704
Processed record #3705
Processed record #3706
Processed record #3707
Processed record #3708
Processed record #3709
Processed record #3710
Processed record #3711
Processed record #3712
Processed record #3713
Processed record #3714
Processed record #3715
Processed record #3716
Processed record #3717
Processed record #3718
Processed record #3719
Processed record #3720
Processed record #3721
Processed record #3722
Processed record #3723
Processed record #3724
Processed record #3725
Processed record #3726
Processed record #3727
Processed record #3728
Processed record #3729
Processed record #3730
Processed record #3731
Processed record #3732
Processed record #3733
Processed record #3734
Processed record #3735
Processed record #3736
Processed record #3737
Processed record #3738
Processed record #3739
Processed record #3740
Processed record #3741
Processed record #3742
Processed record #3743
Processed record #3744
Processed record #3745
Processed record #3746
Processed record #3747
Processed record #3748
Processed record #3749
Processed record #3750
Processed record #3751
Processed record #3752
Processed record #3753
Processed record #3754
Processed record #3755
Processed record #3756
Processed record #3757
Processed record #3758
Processed record #3759
Processed record #3760
Processed record #3761
Processed record #3762
Processed record #3763
Processed record #3764
Processed record #3765
Processed record #3766
Processed record #3767
Processed record #3768
Processed record #3769
Processed record #3770
Processed record #3771
Processed record #3772
Processed record #3773
Processed record #3774
Processed record #3775
Processed record #3776
Processed record #3777
Processed record #3778
Processed record #3779
Processed record #3780
Processed record #3781
Processed record #3782
Processed record #3783
Processed record #3784
Processed record #3785
Processed record #3786
Processed record #3787
Processed record #3788
Processed record #3789
Processed record #3790
Processed record #3791
Processed record #3792
Processed record #3793
Processed record #3794
Processed record #3795
Processed record #3796
Processed record #3797
Processed record #3798
Processed record #3799
Processed record #3800
Processed record #3801
Processed record #3802
Processed record #3803
Processed record #3804
Processed record #3805
Processed record #3806
Processed record #3807
Processed record #3808
Processed record #3809
Processed record #3810
Processed record #3811
Processed record #3812
Processed record #3813
Processed record #3814
Processed record #3815
Processed record #3816
Processed record #3817
Processed record #3818
Processed record #3819
Processed record #3820
Processed record #3821
Processed record #3822
Processed record #3823
Processed record #3824
Processed record #3825
Processed record #3826
Processed record #3827
Processed record #3828
Processed record #3829
Processed record #3830
Processed record #3831
Processed record #3832
Processed record #3833
Processed record #3834
Processed record #3835
Processed record #3836
Processed record #3837
Processed record #3838
Processed record #3839
Processed record #3840
Processed record #3841
Processed record #3842
Processed record #3843
Processed record #3844
Processed record #3845
Processed record #3846
Processed record #3847
Did not work. Skipping...
Processed record #3848
Processed record #3849
Processed record #3850
Processed record #3851
Processed record #3852
Processed record #3853
Processed record #3854
Processed record #3855
Processed record #3856
Processed record #3857
Processed record #3858
Processed record #3859
Processed record #3860
Processed record #3861
Processed record #3862
Processed record #3863
Processed record #3864
Processed record #3865
Processed record #3866
Processed record #3867
Processed record #3868
Processed record #3869
Processed record #3870
Processed record #3871
Processed record #3872
Processed record #3873
Processed record #3874
Processed record #3875
Processed record #3876
Processed record #3877
Processed record #3878
Processed record #3879
Processed record #3880
Processed record #3881
Processed record #3882
Processed record #3883
Processed record #3884
Processed record #3885
Processed record #3886
Processed record #3887
Processed record #3888
Processed record #3889
Processed record #3890
Processed record #3891
Processed record #3892
Processed record #3893
Processed record #3894
Processed record #3895
Processed record #3896
Processed record #3897
Processed record #3898
Processed record #3899
Processed record #3900
Processed record #3901
Processed record #3902
Processed record #3903
Processed record #3904
Processed record #3905
Processed record #3906
Processed record #3907
Processed record #3908
Processed record #3909
Processed record #3910
Processed record #3911
Processed record #3912
Processed record #3913
Processed record #3914
Processed record #3915
Processed record #3916
Processed record #3917
Processed record #3918
Processed record #3919
Processed record #3920
Processed record #3921
Processed record #3922
Processed record #3923
Processed record #3924
Processed record #3925
Processed record #3926
Processed record #3927
Processed record #3928
Processed record #3929
Processed record #3930
Processed record #3931
Processed record #3932
Processed record #3933
Processed record #3934
Processed record #3935
Processed record #3936
Processed record #3937
Processed record #3938
Processed record #3939
Processed record #3940
Processed record #3941
Processed record #3942
Did not work. Skipping...
Processed record #3943
Processed record #3944
Processed record #3945
Processed record #3946
Processed record #3947
Processed record #3948
Processed record #3949
Processed record #3950
Processed record #3951
Processed record #3952
Processed record #3953
Processed record #3954
Processed record #3955
Processed record #3956
Processed record #3957
Processed record #3958
Processed record #3959
Processed record #3960
Processed record #3961
Processed record #3962
Processed record #3963
Processed record #3964
Processed record #3965

Processed record #3966
Processed record #3967
Processed record #3968
Processed record #3969
Processed record #3970
Processed record #3971
Processed record #3972
Processed record #3973
Processed record #3974
Processed record #3975
Processed record #3976
Processed record #3977
Processed record #3978
Processed record #3979
Processed record #3980
Processed record #3981
Processed record #3982
Processed record #3983
Processed record #3984
Processed record #3985
Processed record #3986
Processed record #3987
Processed record #3988
Processed record #3989
Processed record #3990
Processed record #3991
Processed record #3992
Processed record #3993
Processed record #3994
Processed record #3995
Processed record #3996
Processed record #3997
Processed record #3998
Processed record #3999
Processed record #4000
Processed record #4001
Processed record #4002
Processed record #4003
Processed record #4004
Processed record #4005
Processed record #4006
Processed record #4007
Processed record #4008
Processed record #4009
Processed record #4010
Processed record #4011
Processed record #4012
Processed record #4013
Processed record #4014
Processed record #4015
Processed record #4016
Processed record #4017
Processed record #4018
Processed record #4019
Processed record #4020
Processed record #4021
Processed record #4022
Processed record #4023
Processed record #4024
Processed record #4025
Processed record #4026
Processed record #4027
Processed record #4028
Processed record #4029
Processed record #4030
Processed record #4031
Processed record #4032
Processed record #4033
Processed record #4034
Processed record #4035
Processed record #4036
Processed record #4037
Processed record #4038
Processed record #4039
Processed record #4040
Processed record #4041
Processed record #4042
Processed record #4043
Processed record #4044
Processed record #4045
Processed record #4046
Processed record #4047
Processed record #4048
Processed record #4049
Processed record #4050
Processed record #4051
Processed record #4052
Processed record #4053
Processed record #4054
Processed record #4055
Processed record #4056
Processed record #4057
Processed record #4058
Processed record #4059
Processed record #4060
Processed record #4061
Processed record #4062
Processed record #4063
Processed record #4064
Processed record #4065
Processed record #4066
Processed record #4067
Processed record #4068
Processed record #4069
Processed record #4070
Processed record #4071
Processed record #4072
Processed record #4073
Processed record #4074
Processed record #4075
Processed record #4076
Processed record #4077
Processed record #4078
Processed record #4079
Processed record #4080
Processed record #4081
Processed record #4082
Processed record #4083
Processed record #4084
Processed record #4085
Processed record #4086
Processed record #4087
Processed record #4088
Processed record #4089
Processed record #4090
Processed record #4091
Processed record #4092
Processed record #4093
Processed record #4094
Processed record #4095
Processed record #4096
Processed record #4097
Processed record #4098
Processed record #4099
Processed record #4100
Processed record #4101
Processed record #4102
Processed record #4103
Processed record #4104
Processed record #4105
Processed record #4106
Processed record #4107
Processed record #4108
Processed record #4109
Processed record #4110
Processed record #4111
Processed record #4112
Processed record #4113
Processed record #4114
Processed record #4115
Processed record #4116
Processed record #4117
Processed record #4118
Processed record #4119
Processed record #4120
Processed record #4121
Processed record #4122
Processed record #4123
Processed record #4124
Processed record #4125
Processed record #4126
Processed record #4127
Processed record #4128
Processed record #4129
Processed record #4130
Processed record #4131
Processed record #4132
Processed record #4133
Processed record #4134
Processed record #4135
Processed record #4136
Processed record #4137
Processed record #4138
Processed record #4139
Processed record #4140
Processed record #4141
Processed record #4142
Processed record #4143
Processed record #4144
Processed record #4145
Processed record #4146
Processed record #4147
Processed record #4148
Processed record #4149
Processed record #4150
Processed record #4151
Processed record #4152
Processed record #4153
Processed record #4154
Processed record #4155
Processed record #4156
Processed record #4157
Processed record #4158
Processed record #4159
Processed record #4160
Processed record #4161
Processed record #4162
Processed record #4163
Processed record #4164
Processed record #4165
Processed record #4166
Processed record #4167
Processed record #4168
Processed record #4169
Processed record #4170
Processed record #4171
Processed record #4172
Processed record #4173
Processed record #4174
Processed record #4175
Processed record #4176
Processed record #4177
Processed record #4178
Processed record #4179
Processed record #4180
Processed record #4181
Processed record #4182
Processed record #4183
Processed record #4184
Processed record #4185
Processed record #4186
Processed record #4187
Processed record #4188
Processed record #4189
Processed record #4190
Processed record #4191
Processed record #4192
Processed record #4193
Processed record #4194
Processed record #4195
Processed record #4196
Processed record #4197
Processed record #4198
Processed record #4199
Processed record #4200
Processed record #4201
Processed record #4202
Processed record #4203
Processed record #4204
Processed record #4205
Processed record #4206
Processed record #4207
Processed record #4208
Processed record #4209
Processed record #4210
Processed record #4211
Processed record #4212
Processed record #4213
Processed record #4214
Processed record #4215
Processed record #4216
Processed record #4217
Processed record #4218
Processed record #4219
Processed record #4220
Processed record #4221
Processed record #4222
Processed record #4223
Processed record #4224
Processed record #4225
Processed record #4226
Processed record #4227
Processed record #4228
Processed record #4229
Processed record #4230
Processed record #4231
Processed record #4232
Processed record #4233
Processed record #4234
Processed record #4235
Processed record #4236
Processed record #4237
Processed record #4238
Processed record #4239
Processed record #4240
Processed record #4241
Processed record #4242
Processed record #4243
Processed record #4244
Processed record #4245
Processed record #4246
Processed record #4247
Processed record #4248
Processed record #4249
Processed record #4250
Processed record #4251
Processed record #4252
Processed record #4253
Processed record #4254
Processed record #4255
Processed record #4256
Processed record #4257
Processed record #4258
Processed record #4259
Processed record #4260
Processed record #4261
Processed record #4262
Processed record #4263
Processed record #4264
Processed record #4265
Processed record #4266
Processed record #4267
Processed record #4268
Processed record #4269
Processed record #4270
Processed record #4271
Processed record #4272
Processed record #4273
Processed record #4274
Processed record #4275
Processed record #4276
Processed record #4277
Processed record #4278
Processed record #4279
Processed record #4280
Processed record #4281
Processed record #4282
Processed record #4283
Processed record #4284
Processed record #4285
Processed record #4286
Processed record #4287
Processed record #4288
Processed record #4289
Processed record #4290
Processed record #4291
Processed record #4292
Processed record #4293
Processed record #4294
Processed record #4295
Processed record #4296
Processed record #4297
Processed record #4298
Processed record #4299
Processed record #4300
Processed record #4301
Processed record #4302
Processed record #4303
Processed record #4304
Processed record #4305
Processed record #4306
Processed record #4307
Processed record #4308
Processed record #4309
Processed record #4310
Processed record #4311
Processed record #4312
Processed record #4313
Processed record #4314
Processed record #4315
Processed record #4316
Processed record #4317
Processed record #4318
Processed record #4319
Processed record #4320
Processed record #4321
Processed record #4322

Processed record #4323
Processed record #4324
Processed record #4325
Processed record #4326
Processed record #4327
Processed record #4328
Processed record #4329
Processed record #4330
Processed record #4331
Processed record #4332
Processed record #4333
Processed record #4334
Processed record #4335
Processed record #4336
Processed record #4337
Processed record #4338
Processed record #4339
Processed record #4340
Processed record #4341
Processed record #4342
Processed record #4343
Processed record #4344
Processed record #4345
Processed record #4346
Processed record #4347
Processed record #4348
Processed record #4349
Processed record #4350
Processed record #4351
Processed record #4352
Processed record #4353
Processed record #4354
Processed record #4355
Processed record #4356
Processed record #4357
Processed record #4358
Processed record #4359
Processed record #4360
Processed record #4361
Processed record #4362
Processed record #4363
Processed record #4364
Processed record #4365
Processed record #4366
Processed record #4367
Processed record #4368
Processed record #4369
Processed record #4370
Processed record #4371
Processed record #4372
Processed record #4373
Processed record #4374
Processed record #4375
Processed record #4376
Processed record #4377
Processed record #4378
Processed record #4379
Processed record #4380
Processed record #4381
Processed record #4382
Processed record #4383
Processed record #4384
Processed record #4385
Processed record #4386
Processed record #4387
Processed record #4388
Processed record #4389
Processed record #4390
Processed record #4391
Processed record #4392
Processed record #4393
Processed record #4394
Processed record #4395
Processed record #4396
Processed record #4397
Processed record #4398
Processed record #4399
Processed record #4400
Processed record #4401
Processed record #4402
Processed record #4403
Processed record #4404
Processed record #4405
Processed record #4406
Processed record #4407
Processed record #4408
Processed record #4409
Processed record #4410
Processed record #4411
Processed record #4412
Processed record #4413
Processed record #4414
Processed record #4415
Processed record #4416
Processed record #4417
Processed record #4418
Processed record #4419
Processed record #4420
Processed record #4421
Processed record #4422
Processed record #4423
Processed record #4424
Processed record #4425
Processed record #4426
Processed record #4427
Processed record #4428
Processed record #4429
Processed record #4430
Processed record #4431
Processed record #4432
Processed record #4433
Processed record #4434
Processed record #4435
Processed record #4436
Processed record #4437
Processed record #4438
Processed record #4439
Processed record #4440
Processed record #4441
Processed record #4442
Processed record #4443
Processed record #4444
Processed record #4445
Processed record #4446
Processed record #4447
Processed record #4448
Processed record #4449
Processed record #4450
Processed record #4451
Processed record #4452
Processed record #4453
Processed record #4454
Processed record #4455
Processed record #4456
Processed record #4457
Processed record #4458
Processed record #4459
Processed record #4460
Processed record #4461
Processed record #4462
Processed record #4463
Processed record #4464
Processed record #4465
Processed record #4466
Processed record #4467
Processed record #4468
Processed record #4469
Processed record #4470
Processed record #4471
Processed record #4472
Processed record #4473
Processed record #4474
Processed record #4475
Processed record #4476
Processed record #4477
Processed record #4478
Processed record #4479
Processed record #4480
Processed record #4481
Processed record #4482
Processed record #4483
Processed record #4484
Processed record #4485
Processed record #4486
Processed record #4487
Processed record #4488
Processed record #4489
Processed record #4490
Processed record #4491
Processed record #4492
Processed record #4493
Processed record #4494
Processed record #4495
Processed record #4496
Processed record #4497
Processed record #4498
Processed record #4499
Processed record #4500
Processed record #4501
Processed record #4502
Processed record #4503
Processed record #4504
Processed record #4505
Processed record #4506
Processed record #4507
Processed record #4508
Processed record #4509
Processed record #4510
Processed record #4511
Processed record #4512
Processed record #4513
Processed record #4514
Processed record #4515
Processed record #4516
Processed record #4517
Processed record #4518
Processed record #4519
Processed record #4520
Processed record #4521
Processed record #4522
Processed record #4523
Processed record #4524
Processed record #4525
Processed record #4526
Processed record #4527
Processed record #4528
Processed record #4529
Processed record #4530
Processed record #4531
Processed record #4532
Processed record #4533
Processed record #4534
Processed record #4535
Processed record #4536
Processed record #4537
Processed record #4538
Processed record #4539
Processed record #4540
Processed record #4541
Processed record #4542
Processed record #4543
Processed record #4544
Processed record #4545
Processed record #4546
Processed record #4547
Processed record #4548
Processed record #4549
Processed record #4550
Processed record #4551
Processed record #4552
Processed record #4553
Processed record #4554
Processed record #4555
Processed record #4556
Processed record #4557
Processed record #4558
Processed record #4559
Processed record #4560
Processed record #4561
Processed record #4562
Processed record #4563
Processed record #4564
Processed record #4565
Processed record #4566
Processed record #4567
Processed record #4568
Processed record #4569
Processed record #4570
Processed record #4571
Processed record #4572
Processed record #4573
Processed record #4574
Processed record #4575
Processed record #4576
Processed record #4577
Processed record #4578
Processed record #4579
Processed record #4580
Processed record #4581
Processed record #4582
Processed record #4583
Processed record #4584
Processed record #4585
Processed record #4586
Processed record #4587
Processed record #4588
Processed record #4589
Processed record #4590
Processed record #4591
Processed record #4592
Processed record #4593
Processed record #4594
Processed record #4595
Processed record #4596
Processed record #4597
Processed record #4598
Processed record #4599
Processed record #4600
Processed record #4601
Processed record #4602
Processed record #4603
Processed record #4604
Processed record #4605
Processed record #4606
Processed record #4607
Processed record #4608
Processed record #4609
Processed record #4610
Processed record #4611
Processed record #4612
Processed record #4613
Processed record #4614
Processed record #4615
Processed record #4616
Processed record #4617
Processed record #4618
Processed record #4619
Processed record #4620
Processed record #4621
Processed record #4622
Processed record #4623
Processed record #4624
Processed record #4625
Processed record #4626
Processed record #4627
Processed record #4628
Processed record #4629
Processed record #4630
Processed record #4631
Processed record #4632
Processed record #4633
Processed record #4634
Processed record #4635
Processed record #4636
Processed record #4637
Processed record #4638
Processed record #4639
Processed record #4640
Processed record #4641
Processed record #4642
Processed record #4643
Processed record #4644
Processed record #4645
Processed record #4646
Processed record #4647
Processed record #4648
Processed record #4649
Processed record #4650
Processed record #4651
Processed record #4652
Processed record #4653
Processed record #4654
Processed record #4655
Processed record #4656
Processed record #4657
Processed record #4658
Processed record #4659
Processed record #4660
Processed record #4661
Processed record #4662
Processed record #4663
Processed record #4664
Processed record #4665
Processed record #4666
Processed record #4667
Processed record #4668
Processed record #4669
Processed record #4670
Processed record #4671
Processed record #4672
Processed record #4673
Processed record #4674
Processed record #4675
Processed record #4676
Processed record #4677
Processed record #4678
Processed record #4679

Processed record #4680
Processed record #4681
Processed record #4682
Processed record #4683
Processed record #4684
Processed record #4685
Processed record #4686
Processed record #4687
Processed record #4688
Processed record #4689
Processed record #4690
Processed record #4691
Processed record #4692
Processed record #4693
Processed record #4694
Processed record #4695
Processed record #4696
Processed record #4697
Processed record #4698
Processed record #4699
Processed record #4700
Processed record #4701
Processed record #4702
Processed record #4703
Processed record #4704
Processed record #4705
Processed record #4706
Processed record #4707
Processed record #4708
Processed record #4709
Processed record #4710
Processed record #4711
Processed record #4712
Processed record #4713
Processed record #4714
Processed record #4715
Processed record #4716
Processed record #4717
Processed record #4718
Processed record #4719
Processed record #4720
Processed record #4721
Processed record #4722
Processed record #4723
Processed record #4724
Processed record #4725
Processed record #4726
Processed record #4727
Processed record #4728
Processed record #4729
Processed record #4730
Processed record #4731
Processed record #4732
Processed record #4733
Processed record #4734
Processed record #4735
Processed record #4736
Processed record #4737
Processed record #4738
Processed record #4739
Processed record #4740
Processed record #4741
Processed record #4742
Processed record #4743
Processed record #4744
Processed record #4745
Processed record #4746
Processed record #4747
Processed record #4748
Processed record #4749
Processed record #4750
Processed record #4751
Processed record #4752
Processed record #4753
Processed record #4754
Processed record #4755
Processed record #4756
Processed record #4757
Processed record #4758
Processed record #4759
Processed record #4760
Processed record #4761
Processed record #4762
Processed record #4763
Processed record #4764
Processed record #4765
Processed record #4766
Processed record #4767
Processed record #4768
Processed record #4769
Processed record #4770
Processed record #4771
Processed record #4772
Processed record #4773
Processed record #4774
Processed record #4775
Processed record #4776
Processed record #4777
Processed record #4778
Processed record #4779
Processed record #4780
Processed record #4781
Processed record #4782
Processed record #4783
Processed record #4784
Processed record #4785
Processed record #4786
Processed record #4787
Processed record #4788
Processed record #4789
Processed record #4790
Processed record #4791
Processed record #4792
Processed record #4793
Processed record #4794
Processed record #4795
Processed record #4796

In [8]:
# check what dataframe looks like
movies_df.head()

,ID,Title,Adult,Budget,Genres,Language,Overview,Popularity,Production Countries,Release Date,Revenue,Runtime,Spoken Languages,Status,Video,Average Vote,Vote Count
0,19995,Avatar,False,237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,"In the 22nd century, a paraplegic Marine is di...",30.906,"[{'iso_3166_1': 'US', 'name': 'United States o...",2009-12-10,2787965087,162,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.4,17835
1,285,Pirates of the Caribbean: At World's End,False,300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,"Captain Barbossa, long believed to be dead, ha...",20.818,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-05-19,961000000,169,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.1,7879
2,206647,Spectre,False,245000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,A cryptic message from Bond’s past sends him o...,22.83,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2015-10-26,880674609,148,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,False,6.4,6465
3,49026,The Dark Knight Rises,False,250000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",en,Following the death of District Attorney Harve...,28.266,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-07-16,1084939099,165,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.7,13306
4,49529,John Carter,False,250000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,"John Carter is a war-weary, former military ca...",13.317,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-03-07,284139100,132,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.1,3171

In [9]:
# output dataframe to CSV
movies_df.to_csv("Output/movie_raw_df.csv")

### Clean the raw data

In [10]:
# START HERE
# load csv
movie_data_to_load = "Output/movie_raw_df.csv"
movies_df = pd.read_csv(movie_data_to_load,index_col = 0)

In [11]:
movies_df.head()

,ID,Title,Adult,Budget,Genres,Language,Overview,Popularity,Production Countries,Release Date,Revenue,Runtime,Spoken Languages,Status,Video,Average Vote,Vote Count
0,19995,Avatar,False,237000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,"In the 22nd century, a paraplegic Marine is di...",30.906,"[{'iso_3166_1': 'US', 'name': 'United States o...",2009-12-10,2.787965e+09,162.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.4,17835.0
1,285,Pirates of the Caribbean: At World's End,False,300000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,"Captain Barbossa, long believed to be dead, ha...",20.818,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-05-19,9.610000e+08,169.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.1,7879.0
2,206647,Spectre,False,245000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,A cryptic message from Bond’s past sends him o...,22.830,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2015-10-26,8.806746e+08,148.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,False,6.4,6465.0
3,49026,The Dark Knight Rises,False,250000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",en,Following the death of District Attorney Harve...,28.266,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-07-16,1.084939e+09,165.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.7,13306.0
4,49529,John Carter,False,250000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,"John Carter is a war-weary, former military ca...",13.317,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-03-07,2.841391e+08,132.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.1,3171.0

In [12]:
movies_df.dtypes

ID                        int64
Title                    object
Adult                    object
Budget                  float64
Genres                   object
Language                 object
Overview                 object
Popularity              float64
Production Countries     object
Release Date             object
Revenue                 float64
Runtime                 float64
Spoken Languages         object
Status                   object
Video                    object
Average Vote            float64
Vote Count              float64
dtype: object

In [13]:
# convert release date to datetime format
movies_df["Release Date"] = pd.to_datetime (movies_df["Release Date"])

In [14]:
# confirm change worked
movies_df.dtypes

ID                               int64
Title                           object
Adult                           object
Budget                         float64
Genres                          object
Language                        object
Overview                        object
Popularity                     float64
Production Countries            object
Release Date            datetime64[ns]
Revenue                        float64
Runtime                        float64
Spoken Languages                object
Status                          object
Video                           object
Average Vote                   float64
Vote Count                     float64
dtype: object

In [15]:
# check if adult is labeled "True". If so, eliminate Adult films
movies_df["Adult"].describe()

count      4796
unique        1
top       False
freq       4796
Name: Adult, dtype: object

In [16]:
movies_df.describe()

,ID,Budget,Popularity,Revenue,Runtime,Average Vote,Vote Count
count,4803.000000,4.796000e+03,4796.000000,4.796000e+03,4770.000000,4796.000000,4796.000000
mean,57165.484281,2.938087e+07,8.057848,8.336904e+07,107.558071,6.219495,1159.977898
std,88694.614033,4.061008e+07,5.590469,1.635538e+08,20.433622,1.108258,2043.410260
min,5.000000,0.000000e+00,0.600000,0.000000e+00,14.000000,0.000000,0.000000
25%,9014.500000,1.300000e+06,4.908750,0.000000e+00,94.000000,5.700000,88.000000
50%,14629.000000,1.500000e+07,7.265000,2.060598e+07,104.000000,6.300000,388.500000
75%,58610.500000,4.000000e+07,10.073000,9.410886e+07,118.000000,6.900000,1253.250000
max,459488.000000,3.800000e+08,55.032000,2.787965e+09,338.000000,10.000000,21081.000000

In [17]:
# find out how many null values we have
movies_df.isnull().sum()

ID                       0
Title                    7
Adult                    7
Budget                   7
Genres                   7
Language                 7
Overview                 9
Popularity               7
Production Countries     7
Release Date             8
Revenue                  7
Runtime                 33
Spoken Languages         7
Status                   7
Video                    7
Average Vote             7
Vote Count               7
dtype: int64

In [18]:
# slightly more nulls for runtimes -- investigate those values
movies_df[movies_df.Runtime.isnull()]

,ID,Title,Adult,Budget,Genres,Language,Overview,Popularity,Production Countries,Release Date,Revenue,Runtime,Spoken Languages,Status,Video,Average Vote,Vote Count
2631,112430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2656,370980,Chiamatemi Francesco - Il Papa della gente,False,15000000.0,"[{'id': 18, 'name': 'Drama'}]",it,NaN,1.187,"[{'iso_3166_1': 'IT', 'name': 'Italy'}]",2015-12-03,0.0,NaN,"[{'iso_639_1': 'es', 'name': 'Español'}]",Released,False,7.0,25.0
3112,41894,Blood Done Sign My Name,False,10000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",en,A drama based on the true story in which a bla...,0.744,[],2010-02-01,82739.0,NaN,[],Released,False,6.0,5.0
3208,333355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3285,153397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3292,36597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3510,183894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3669,113406,Should've Been Romeo,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,"A self-centered, middle-aged pitchman for a po...",0.690,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-04-28,0.0,NaN,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0
3809,158150,How to Fall in Love,False,4000000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en,"An accountant, who never quite grew out of his...",2.411,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-07-21,0.0,NaN,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,31.0
3852,395766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3948,50942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3953,281230,Fort McCoy,False,0.0,"[{'id': 10752, 'name': 'War'}, {'id': 18, 'nam...",en,Unable to serve in World War II because of a h...,0.600,[],2014-01-01,0.0,NaN,[],Released,False,6.3,2.0
3992,346081,Sardaarji,False,0.0,[],en,A ghost hunter uses bottles to capture trouble...,0.600,"[{'iso_3166_1': 'IN', 'name': 'India'}]",2015-06-26,0.0,NaN,[],Released,False,6.6,5.0
4118,325140,Hum To Mohabbat Karega,False,0.0,[],en,"Raju, a waiter, is in love with the famous TV ...",0.600,[],2000-05-26,0.0,NaN,[],Released,False,4.0,1.0
4205,66468,N-Secure,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",en,N-Secure is a no holds-barred thrilling drama ...,0.777,[],2010-10-15,2592808.0,NaN,[],Released,False,3.8,5.0
4210,74084,Dil Jo Bhi Kahey...,False,0.0,"[{'id': 10749, 'name': 'Romance'}]",hi,"During the British rule in India, several Indi...",0.656,"[{'iso_3166_1': 'IN', 'name': 'India'}]",2006-12-07,0.0,NaN,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,0.0,0.0
4241,51820,The Salon,False,1500000.0,"[{'id': 35, 'name': 'Comedy'}]",en,A Beauty shop owner finds romance as she strug...,1.015,[],2005-01-13,0.0,NaN,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,3.5,1.0
4313,107315,Below Zero,False,0.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...",en,When Jack (Edward Furlong) is in danger of mis...,1.239,"[{'iso_3166_1': 'CA', 'name': 'Canada'}]",2011-10-22,0.0,NaN,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.1,16.0
4318,310933,Bleeding Hearts,False,0.0,"[{'id': 27, 'name': 'Horror'}]",en,"Captured Hearts, an insane serial killer/horro...",0.707,[],2013-06-01,0.0,NaN,[],Released,False,6.0,2.0
4322,102840,Sex With Strangers,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,"For some married couples, sex is an obsession ...",0.600,[],2002-02-22,0.0,NaN,[],Released,False,5.0,1.0
4328,202604,The Vatican Exorcisms,False,0.0,"[{'id': 27, 'name': 'Horror'}, {'id': 99, 'nam...",en,Documentary following US film-maker Joe Marino...,0.767,[],2013-05-29,0.0,NaN,"[{'iso_639_1': 'it', 'name': 'Italiano'}, {'is...",Released,False,4.2,14.0
4435,323270,The Horror Network Vol. 1,False,0.0,"[{'id': 27, 'name': 'Horror'}]",en,"Serial killers, ghostly phone calls, inner dem...",0.600,[],2015-10-27,0.0,NaN,[],Released,False,5.0,3.0
4504,331493,Light from the Darkroom,False,0.0,[],en,Light in the Darkroom is the story of two best...,0.600,[],2014-01-01,0.0,NaN,[],Released,False,0.0,0.0
4553,380097,America Is Still the Place,False,0.0,[],en,1971 post civil rights San Francisco seemed li...,1.090,[],NaT,0.0,NaN,[],Released,False,0.0,0.0
4564,94072,Straight Out of Brooklyn,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,A Special Jury Award winner at the Sundance Fi...,0.740,[],1991-06-13,0.0,NaN,[],Released,False,6.0,5.0
4566,325579,Diamond Ruff,False,0.0,[],en,"Action - Orphan, con artist, crime boss and mi...",0.970,[],2015-01-01,0.0,NaN,[],Released,False,2.4,4.0
4571,328307,Rise of the Entrepreneur: The Search for a Bet...,False,0.0,[],en,The world is changing faster than ever. Techno...,0.600,[],2014-11-20,0.0,NaN,[],Released,False,8.0,1.0
4581,281189,Gory Gory Hallelujah,False,0.0,[],en,Four actors compete for the role of Jesus - a ...,0.600,[],2003-11-05,0.0,NaN,[],Released,False,3.0,2.0
4620,47534,Fighting Tommy Riley,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,"An aging trainer and a young fighter, both in ...",1.180,[],2005-05-06,0.0,NaN,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.4,5.0
4633,300327,Death Calls,False,0.0,[],en,An action-packed love story on the Mexican bor...,0.600,[],2010-09-01,0.0,NaN,[],Released,False,0.0,0.0
4657,320435,UnDivided,False,0.0,[],en,UnDivided documents the true story of how a su...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2013-02-01,0.0,NaN,[],Released,False,0.0,0.0
4662,40963,Little Big Top,False,0.0,"[{'id': 35, 'name': 'Comedy'}]",en,An aging out of work clown returns to his smal...,0.622,"[{'iso_3166_1': 'US', 'name': 'United States o...",2006-01-01,0.0,NaN,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,10.0,1.0
4729,272726,Dude Where's My Dog?,False,0.0,"[{'id': 10751, 'name': 'Family'}]",en,"Left home alone with his dog Harry, young Ray ...",1.129,[],2014-06-12,0.0,NaN,[],Released,False,7.0,1.0

In [19]:
# check what current dataframe shape looks like
movies_df.shape

(4803, 17)

In [20]:
# check what dataframe shape would look like if we removed all N/A rows
movies_df.dropna(how="any").shape

(4769, 17)

In [21]:
# no rows that are completely blank
movies_df.dropna(how="all").shape

(4803, 17)

In [22]:
# since there is a relatively small number of null values, I think it's fine to remove all rows with null in them
movies_df.dropna(how="any",inplace=True)

In [23]:
movies_df["Profit"] = movies_df["Revenue"] - movies_df["Budget"]

In [24]:
movies_df["Profitability"] = np.where(movies_df["Profit"]>0,"Profitable","Not Profitable")

In [25]:
movies_df.groupby("Profitability").Profitability.count()

Profitability
Not Profitable    2114
Profitable        2655
Name: Profitability, dtype: int64

In [26]:
movies_df["Days Out"] = (dt.datetime.today() - movies_df["Release Date"]).dt.days 
movies_df["Years Out"] = movies_df["Days Out"]/365

In [27]:
movies_df["Critical Acclaim"] = (movies_df["Average Vote"] * movies_df["Vote Count"]) / movies_df["Days Out"]

In [28]:
movies_df["Average Vote"].min()

0.0

In [29]:
# almost all english-speaking films
movies_df["Language"].describe()

count     4769
unique      38
top         en
freq      4452
Name: Language, dtype: object

In [30]:
movies_df["Runtime"].describe()

count    4769.000000
mean      107.563221
std        20.432669
min        14.000000
25%        94.000000
50%       104.000000
75%       118.000000
max       338.000000
Name: Runtime, dtype: float64

In [31]:
# see what the low runtime movies look like
movies_df.sort_values("Runtime",ascending = True)

,ID,Title,Adult,Budget,Genres,Language,Overview,Popularity,Production Countries,Release Date,...,Spoken Languages,Status,Video,Average Vote,Vote Count,Profit,Profitability,Days Out,Years Out,Critical Acclaim
4466,211557,Vessel,False,0.0,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",en,Vessel is the story of the passengers of Fligh...,1.190,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-10-28,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.3,13.0,0.000000e+00,Not Profitable,2317,6.347945,0.035347
4709,13187,A Charlie Brown Christmas,False,0.0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",en,When Charlie Brown complains about the overwhe...,8.938,"[{'iso_3166_1': 'US', 'name': 'United States o...",1965-12-09,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.6,258.0,0.000000e+00,Not Profitable,19442,53.265753,0.100854
3626,78394,Sea Rex 3D: Journey to a Prehistoric World,False,5000000.0,"[{'id': 99, 'name': 'Documentary'}]",en,"Through the power of IMAX 3D, experience a won...",1.940,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",2010-05-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.4,12.0,-9.259770e+05,Not Profitable,3215,8.808219,0.027621
3471,57612,Dolphins and Whales: Tribes of the Ocean,False,6000000.0,"[{'id': 99, 'name': 'Documentary'}]",en,This documentary goes to coral reefs of the Ba...,0.719,"[{'iso_3166_1': 'BS', 'name': 'Bahamas'}, {'is...",2008-02-15,...,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,False,8.0,3.0,1.518876e+06,Profitable,4034,11.052055,0.005949
3354,24977,Michael Jordan to the Max,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,This documentary showcases basketball player M...,1.312,"[{'iso_3166_1': 'US', 'name': 'United States o...",2000-05-05,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.4,11.0,2.126853e+07,Profitable,6876,18.838356,0.011838
4756,20981,The Call of Cthulhu,False,50000.0,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",en,A dying professor leaves his great-nephew a co...,3.271,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2005-01-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,61.0,-5.000000e+04,Not Profitable,5174,14.175342,0.082528
3403,294512,Alpha and Omega: The Legend of the Saw Tooth Cave,False,0.0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",en,The Alphas and Omegas share a thrilling advent...,1.477,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-07-21,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.0,8.0,0.000000e+00,Not Profitable,1686,4.619178,0.023725
4685,126141,The Case of the Grinning Cat,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,Paris 2002. Yellow cats appear on the walls. C...,0.600,"[{'iso_3166_1': 'FR', 'name': 'France'}]",2004-12-05,...,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,False,7.7,3.0,0.000000e+00,Not Profitable,5201,14.249315,0.004441
4785,287625,Stories of Our Lives,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,Created by the members of a Nairobi-based arts...,0.600,"[{'iso_3166_1': 'KE', 'name': 'Kenya'}, {'iso_...",2014-09-05,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,0.0,0.0,0.000000e+00,Not Profitable,1640,4.493151,0.000000
1620,51162,Winnie the Pooh,False,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",en,"During an ordinary day in Hundred Acre Wood, W...",7.521,"[{'iso_3166_1': 'US', 'name': 'United States o...",2011-04-13,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.9,419.0,-1.554000e+07,Not Profitable,2881,7.893151,1.003506
4774,42497,Pink Narcissus,False,27000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,An erotic poem set in the fantasies of a young...,1.630,"[{'iso_3166_1': 'US', 'name': 'United States o...",1971-01-01,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.3,14.0,-2.700000e+04,Not Profitable,17593,48.200000,0.005013
4673,43595,She Done Him Wrong,False,200000.0,"[{'id': 35, 'name': 'Comedy'}]",en,New York singer and nightclub owner Lady Lou h...,1.768,"[{'iso_3166_1': 'US', 'name': 'United States o...",1933-02-09,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.7,36.0,2.000000e+06,Profitable,31433,86.117808,0.006528
3663,292481,Henry & Me,False,5000000.0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",en,Henry &amp; Me tells the courageous story of J...,0.635,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-08-18,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.7,3.0,-5.000000e+06,Not Profitable,1658,4.542466,0.008504
4493,138976,Treachery,False,625000.0,"[{'id': 18, 'name': 'Drama'}]",en,Treachery centers on a man (Biehn) who is reun...,0.600,[],2013-05-16,...,[],Released,False,4.8,5.0,-6.250000e+05,Not Profitable,2117,5.800000,0.011337
2182,13682,Pooh's Heffalump Movie,False,20000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",en,Who or what exactly is a Heffalump? The lovabl...,9.397,"[{'iso_3166_1': 'US', 'name': 'United States o...",2005-02-11,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.5,187.0,3.290000e+07,Profitable,5133,14.063014,0.236801
4733,51130,Open Secret,False,0.0,"[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...",en,A couple discovers that their friend has gone ...,0.651,"[{'iso_3166_1': 'US', 'name': 'United States o...",1948-02-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,2.0,0.000000e+00,Not Profitable,25950,71.095890,0.000539
2805,12144,The Land Before Time,False,12300000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",en,An orphaned brontosaurus named Littlefoot sets...,14.492,"[{'iso_3166_1': 'IE', 'name': 'Ireland'}, {'is...",1988-11-18,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,1270.0,7.216085e+07,Profitable,11062,30.306849,0.803652
4668,70478,The Stewardesses,False,100000.0,"[{'id': 35, 'name': 'Comedy'}]",en,A single eventful night in the lives of a crew...,0.741,[],1969-07-25,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.3,5.0,2.690000e+07,Profitable,18118,49.638356,0.001187
4491,296943,The Hadza: Last of the First,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,A look at human origins in the very place of o...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-10-31,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.000000e+00,Not Profitable,1584,4.339726,0.000000
4441,3170,Bambi,False,858000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 18, '...",en,Bambi's tale unfolds from season to season as ...,16.426,"[{'iso_3166_1': 'US', 'name': 'United States o...",1942-08-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.9,2759.0,2.665892e+08,Profitable,27960,76.602740,0.680869
4721,266857,The Work and The Story,False,0.0,"[{'id': 35, 'name': 'Comedy'}]",en,"It is July, 2000 Richard Dutcher, the man who ...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2003-01-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.000000e+00,Not Profitable,5905,16.178082,0.000000
2116,14873,The Jungle Book 2,False,20000000.0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",en,Mowgli has been living in the man-village with...,9.014,"[{'iso_3166_1': 'US', 'name': 'United States o...",2003-02-07,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,544.0,1.156800e+08,Profitable,5868,16.076712,0.537696
2114,16690,Return to Never Land,False,20000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,"In 1940, the world is besieged by World War II...",10.535,"[{'iso_3166_1': 'AU', 'name': 'Australia'}, {'...",2002-02-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.2,670.0,8.986268e+07,Profitable,6226,17.057534,0.667202
1984,26672,The Thief and the Cobbler,False,28000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,It is written among the limitless constellatio...,4.053,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",1993-09-23,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,40.0,-2.733072e+07,Not Profitable,9292,25.457534,0.028842
4641,51942,I Married a Strange Person!,False,250.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 16, 'nam...",en,It's a heartwarming story of a newlywed couple...,1.449,"[{'iso_3166_1': 'US', 'name': 'United States o...",1998-08-28,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.6,16.0,-4.700000e+01,Not Profitable,7492,20.526027,0.016231
4710,335244,Antarctic Edge: 70° South,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,"In 2014, scientists declared West Antarctic ic...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-04-17,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,1.0,0.000000e+00,Not Profitable,1416,3.879452,0.004944
4642,1424,November,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",en,Sophie Jacobs is going through the most diffic...,2.049,"[{'iso_3166_1': 'US', 'name': 'United States o...",2004-07-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.4,17.0,0.000000e+00,Not Profitable,5337,14.621918,0.014015
4612,26518,Old Joy,False,300000.0,"[{'id': 18, 'name': 'Drama'}]",en,"Soon to be a father, Mark feels the pressure o...",2.512,"[{'iso_3166_1': 'US', 'name': 'United States o...",2006-01-20,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.2,47.0,-3.000000e+05,Not Profitable,4790,13.123288,0.060835
4711,178862,Aroused,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,Get up close and personal with 16 of the most ...,2.389,"[{'iso_3166_1': 'US', 'name': 'United States o...",2013-02-20,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.6,18.0,0.000000e+00,Not Profitable,2202,6.032877,0.053951
2427,16112,The Adventures of Elmo in Grouchland,False,0.0,"[{'id': 10402, 'name': 'Music'}, {'id': 10751,...",en,"Elmo loves his fuzzy, blue blanket, and would ...",1.989,"[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",1999-10-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.2,30.0,0.000000e+00,Not Profitable,7093,19.432877,0.026223
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,334,Magnolia,False,37000000.0,"[{'id': 18, 'name': 'Drama'}]",en,An epic mosaic of many interrelated characters...,11.178,"[{'iso_3166_1': 'US', 'name': 'United States o...",1999-12-10,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.7,1455.0,1.145180e+07,Profitable,7023,19.241096,1.595258
1181,820,JFK,False,40000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",en,New Orleans District Attorney Jim Garrison dis...,9.448,"[{'iso_3166_1': 'US', 'name': 'United States o...",1991-12-20,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.7,839.0,1.654055e+08,Profitable,9935,27.219178,0.650257
2024,783,Gandhi,False,22000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,"In the early years of the 20th century, Mohand...",8.563,"[{'iso_3166_1': 'IN', 'name': 'India'}, {'iso_...",1982-11-30,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.5,1117.0,5.573789e+07,Profitable,13242,36.279452,0.632646
880,285923,Grindhouse,False,67000000.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",en,Two full-length feature horror movies written ...,9.953,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-04-06,...,"[{'iso_639_1': 'es', 'name': 'Español'}, {'iso...",Released,False,6.9,815.0,-4.196210e+07,Not Profitable,4349,11.915068,1.293056
676,12160,Wyatt Earp,False,63000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",en,Covering the life and times of one of the West...,9.999,"[{'iso_3166_1': 'US', 'name': 'United States o...",1994-06-24,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.6,326.0,-3.794800e+07,Not Profitable,9018,24.706849,0.238589
3374,4251,Veer-Zaara,False,7000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",hi,The story of the love between Veer Pratap Sing...,5.311,"[{'iso_3166_1': 'IN', 'name': 'India'}]",2004-11-12,...,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,False,7.5,114.0,2.238532e+07,Profitable,5224,14.312329,0.163668
1091,10858,Nixon,False,44000000.0,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",en,An all-star cast powers this epic look at Amer...,6.376,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,123.0,-3.031824e+07,Not Profitable,8472,23.210959,0.101629
1759,9549,The Right Stuff,False,27000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,A chronicle of the original Mercury astronauts...,7.832,"[{'iso_3166_1': 'US', 'name': 'United States o...",1983-10-20,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.5,359.0,-5.500000e+06,Not Profitable,12918,35.391781,0.208430
2962,14395,Kabhi Alvida Naa Kehna,False,7400000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",hi,Dev and Maya are both married to different peo...,4.383,"[{'iso_3166_1': 'IN', 'name': 'India'}]",2006-08-11,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.8,76.0,9.600000e+06,Profitable,4587,12.567123,0.096098
25,597,Titanic,False,200000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,"84 years later, a 101-year-old woman named Ros...",29.092,"[{'iso_3166_1': 'US', 'name': 'United States o...",1997-11-18,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.8,13372.0,1.645034e+09,Profitable,7775,21.301370,13.414997
1477,18254,Reds,False,32000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,A radical American journalist becomes involved...,5.775,"[{'iso_3166_1': 'US', 'name': 'United States o...",1981-12-25,...,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,False,7.2,117.0,8.382659e+06,Profitable,13582,37.210959,0.062023
1818,424,Schindler's List,False,22000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,The true story of how businessman Oskar Schind...,26.674,"[{'iso_3166_1': 'US', 'name': 'United States o...",1993-12-15,...,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,False,8.5,7486.0,2.993656e+08,Profitable,9209,25.230137,6.909654
4592,3059,Intolerance: Love's Struggle Throughout the Ages,False,8394751.0,"[{'id': 18, 'name': 'Drama'}]",en,"The story of a poor young woman, separated by ...",5.597,"[{'iso_3166_1': 'US', 'name': 'United States o...",1916-09-04,...,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,False,7.4,106.0,-8.394751e+06,Not Profitable,37435,102.561644,0.020954
2192,2428,The Greatest Story Ever Told,False,20000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,From his birth in Bethlehem to his death and e...,4.700,"[{'iso_3166_1': 'US', 'name': 'United States o...",1965-02-15,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.4,61.0,-4.526667e+06,Not Profitable,19739,54.079452,0.019778
3723,17663,Anne of Green Gables,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",en,At the turn of the century on Prince Edward Is...,5.739,"[{'iso_3166_1': 'US', 'name': 'United States o...",1985-12-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,8.3,122.0,0.000000e+00,Not Profitable,12145,33.273973,0.083376
2914,907,Doctor Zhivago,False,11000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,Doctor Zhivago is the filmed adapation of the ...,7.933,"[{'iso_3166_1': 'IT', 'name': 'Italy'}, {'iso_...",1965-12-22,...,"[{'iso_639_1': 'ru', 'name': 'Pусский'}, {'iso...",Released,False,7.6,438.0,1.008584e+08,Profitable,19429,53.230137,0.171332
329,122,The Lord of the Rings: The Return of the King,False,94000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,Aragorn is revealed as the heir to the ancient...,36.022,"[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",2003-12-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,8.4,12476.0,1.024889e+09,Profitable,5571,15.263014,18.811416
2731,240,The Godfather: Part II,False,13000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",en,In the continuing saga of the Corleone crime f...,17.738,"[{'iso_3166_1': 'US', 'name': 'United States o...",1974-12-20,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,8.5,5525.0,8.960000e+07,Profitable,16144,44.230137,2.908975
1387,1883,Malcolm X,False,34000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,A tribute to the controversial black activist ...,5.903,"[{'iso_3166_1': 'US', 'name': 'United States o...",1992-11-18,...,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,False,7.5,641.0,1.416991e+07,Profitable,9601,26.304110,0.500729
4535,346,Seven Samurai,False,2000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",ja,A samurai answers a village's request for prot...,12.437,"[{'iso_3166_1': 'JP', 'name': 'Japan'}]",1954-04-26,...,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,False,8.4,1387.0,-1.728159e+06,Not Profitable,23687,64.895890,0.491865
855,16072,Gods and Generals,False,56000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,The film centers mostly around the personal an...,3.385,"[{'iso_3166_1': 'US', 'name': 'United States o...",2003-02-21,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.9,72.0,-4.307606e+07,Not Profitable,5854,16.038356,0.072566
2550,947,Lawrence of Arabia,False,15000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",en,The story of British officer T.E. Lawrence's m...,13.111,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",1962-12-10,...,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,False,8.0,1354.0,5.499538e+07,Profitable,20537,56.265753,0.527438
1109,10935,Heaven's Gate,False,44000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 37, 'name...",en,Harvard graduate James Averill (Kris Kristoffe...,6.241,"[{'iso_3166_1': 'US', 'name': 'United States o...",1980-11-19,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,104.0,-4.051567e+07,Not Profitable,13983,38.309589,0.049832
4497,9459,Woodstock,False,600000.0,"[{'id': 36, 'name': 'History'}, {'id': 99, 'na...",en,An intimate look at the Woodstock Music & Art ...,5.448,"[{'iso_3166_1': 'US', 'name': 'United States o...",1970-03-26,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.5,106.0,3.390511e+07,Profitable,17874,48.969863,0.044478
1663,311,Once Upon a Time in America,False,20000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",en,A former Prohibition-era Jewish gangster retur...,13.698,"[{'iso_3166_1': 'US', 'name': 'United States o...",1984-05-23,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,8.4,2083.0,-1.470000e+07,Not Profitable,12702,34.800000,1.377515
3813,770,Gone with the Wind,False,4000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,The spoiled daughter of a well-to-do plantatio...,11.382,"[{'iso_3166_1': 'US', 'name': 'United States o...",1939-12-15,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.9,1660.0,3.961765e+08,Profitable,28933,79.268493,0.453254
2373,10549,Hamlet,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,"Hamlet, Prince of Denmark, returns home to fin...",6.644,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",1996-12-25,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.5,206.0,0.000000e+00,Not Profitable,8103,22.200000,0.190670
1125,8095,Cleopatra,False,31115000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,"Winner of four Oscars, this epic saga of love,...",7.574,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",1963-06-12,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.9,251.0,3.988500e+07,Profitable,20353,55.761644,0.085093

In [32]:
# see what the high runtime movies look like
movies_df.sort_values("Runtime",ascending = False)

,ID,Title,Adult,Budget,Genres,Language,Overview,Popularity,Production Countries,Release Date,...,Spoken Languages,Status,Video,Average Vote,Vote Count,Profit,Profitability,Days Out,Years Out,Critical Acclaim
2384,43434,Carlos,False,18000000.0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",en,"The story of Venezuelan revolutionary, Ilich R...",4.611,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",2010-05-19,...,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,False,7.0,78.0,-1.712872e+07,Not Profitable,3210,8.794521,0.170093
1922,10655,Gettysburg,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,Summer 1863. The Confederacy pushes north into...,5.137,"[{'iso_3166_1': 'US', 'name': 'United States o...",1993-10-08,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.8,123.0,2.500000e+07,Profitable,9277,25.416438,0.090158
1125,8095,Cleopatra,False,31115000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,"Winner of four Oscars, this epic saga of love,...",7.574,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",1963-06-12,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.9,251.0,3.988500e+07,Profitable,20353,55.761644,0.085093
2373,10549,Hamlet,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,"Hamlet, Prince of Denmark, returns home to fin...",6.644,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",1996-12-25,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.5,206.0,0.000000e+00,Not Profitable,8103,22.200000,0.190670
3813,770,Gone with the Wind,False,4000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,The spoiled daughter of a well-to-do plantatio...,11.382,"[{'iso_3166_1': 'US', 'name': 'United States o...",1939-12-15,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.9,1660.0,3.961765e+08,Profitable,28933,79.268493,0.453254
1663,311,Once Upon a Time in America,False,20000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",en,A former Prohibition-era Jewish gangster retur...,13.698,"[{'iso_3166_1': 'US', 'name': 'United States o...",1984-05-23,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,8.4,2083.0,-1.470000e+07,Not Profitable,12702,34.800000,1.377515
4497,9459,Woodstock,False,600000.0,"[{'id': 36, 'name': 'History'}, {'id': 99, 'na...",en,An intimate look at the Woodstock Music & Art ...,5.448,"[{'iso_3166_1': 'US', 'name': 'United States o...",1970-03-26,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.5,106.0,3.390511e+07,Profitable,17874,48.969863,0.044478
1109,10935,Heaven's Gate,False,44000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 37, 'name...",en,Harvard graduate James Averill (Kris Kristoffe...,6.241,"[{'iso_3166_1': 'US', 'name': 'United States o...",1980-11-19,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,104.0,-4.051567e+07,Not Profitable,13983,38.309589,0.049832
2550,947,Lawrence of Arabia,False,15000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",en,The story of British officer T.E. Lawrence's m...,13.111,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",1962-12-10,...,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,False,8.0,1354.0,5.499538e+07,Profitable,20537,56.265753,0.527438
855,16072,Gods and Generals,False,56000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,The film centers mostly around the personal an...,3.385,"[{'iso_3166_1': 'US', 'name': 'United States o...",2003-02-21,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.9,72.0,-4.307606e+07,Not Profitable,5854,16.038356,0.072566
4535,346,Seven Samurai,False,2000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",ja,A samurai answers a village's request for prot...,12.437,"[{'iso_3166_1': 'JP', 'name': 'Japan'}]",1954-04-26,...,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,False,8.4,1387.0,-1.728159e+06,Not Profitable,23687,64.895890,0.491865
1387,1883,Malcolm X,False,34000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,A tribute to the controversial black activist ...,5.903,"[{'iso_3166_1': 'US', 'name': 'United States o...",1992-11-18,...,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,False,7.5,641.0,1.416991e+07,Profitable,9601,26.304110,0.500729
2731,240,The Godfather: Part II,False,13000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",en,In the continuing saga of the Corleone crime f...,17.738,"[{'iso_3166_1': 'US', 'name': 'United States o...",1974-12-20,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,8.5,5525.0,8.960000e+07,Profitable,16144,44.230137,2.908975
329,122,The Lord of the Rings: The Return of the King,False,94000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,Aragorn is revealed as the heir to the ancient...,36.022,"[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",2003-12-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,8.4,12476.0,1.024889e+09,Profitable,5571,15.263014,18.811416
2914,907,Doctor Zhivago,False,11000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,Doctor Zhivago is the filmed adapation of the ...,7.933,"[{'iso_3166_1': 'IT', 'name': 'Italy'}, {'iso_...",1965-12-22,...,"[{'iso_639_1': 'ru', 'name': 'Pусский'}, {'iso...",Released,False,7.6,438.0,1.008584e+08,Profitable,19429,53.230137,0.171332
3723,17663,Anne of Green Gables,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",en,At the turn of the century on Prince Edward Is...,5.739,"[{'iso_3166_1': 'US', 'name': 'United States o...",1985-12-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,8.3,122.0,0.000000e+00,Not Profitable,12145,33.273973,0.083376
2192,2428,The Greatest Story Ever Told,False,20000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,From his birth in Bethlehem to his death and e...,4.700,"[{'iso_3166_1': 'US', 'name': 'United States o...",1965-02-15,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.4,61.0,-4.526667e+06,Not Profitable,19739,54.079452,0.019778
4592,3059,Intolerance: Love's Struggle Throughout the Ages,False,8394751.0,"[{'id': 18, 'name': 'Drama'}]",en,"The story of a poor young woman, separated by ...",5.597,"[{'iso_3166_1': 'US', 'name': 'United States o...",1916-09-04,...,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,False,7.4,106.0,-8.394751e+06,Not Profitable,37435,102.561644,0.020954
1818,424,Schindler's List,False,22000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,The true story of how businessman Oskar Schind...,26.674,"[{'iso_3166_1': 'US', 'name': 'United States o...",1993-12-15,...,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,False,8.5,7486.0,2.993656e+08,Profitable,9209,25.230137,6.909654
1477,18254,Reds,False,32000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,A radical American journalist becomes involved...,5.775,"[{'iso_3166_1': 'US', 'name': 'United States o...",1981-12-25,...,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,False,7.2,117.0,8.382659e+06,Profitable,13582,37.210959,0.062023
25,597,Titanic,False,200000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,"84 years later, a 101-year-old woman named Ros...",29.092,"[{'iso_3166_1': 'US', 'name': 'United States o...",1997-11-18,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.8,13372.0,1.645034e+09,Profitable,7775,21.301370,13.414997
1759,9549,The Right Stuff,False,27000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,A chronicle of the original Mercury astronauts...,7.832,"[{'iso_3166_1': 'US', 'name': 'United States o...",1983-10-20,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.5,359.0,-5.500000e+06,Not Profitable,12918,35.391781,0.208430
2962,14395,Kabhi Alvida Naa Kehna,False,7400000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",hi,Dev and Maya are both married to different peo...,4.383,"[{'iso_3166_1': 'IN', 'name': 'India'}]",2006-08-11,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.8,76.0,9.600000e+06,Profitable,4587,12.567123,0.096098
3374,4251,Veer-Zaara,False,7000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",hi,The story of the love between Veer Pratap Sing...,5.311,"[{'iso_3166_1': 'IN', 'name': 'India'}]",2004-11-12,...,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,False,7.5,114.0,2.238532e+07,Profitable,5224,14.312329,0.163668
1091,10858,Nixon,False,44000000.0,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",en,An all-star cast powers this epic look at Amer...,6.376,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,123.0,-3.031824e+07,Not Profitable,8472,23.210959,0.101629
2024,783,Gandhi,False,22000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,"In the early years of the 20th century, Mohand...",8.563,"[{'iso_3166_1': 'IN', 'name': 'India'}, {'iso_...",1982-11-30,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.5,1117.0,5.573789e+07,Profitable,13242,36.279452,0.632646
676,12160,Wyatt Earp,False,63000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",en,Covering the life and times of one of the West...,9.999,"[{'iso_3166_1': 'US', 'name': 'United States o...",1994-06-24,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.6,326.0,-3.794800e+07,Not Profitable,9018,24.706849,0.238589
880,285923,Grindhouse,False,67000000.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",en,Two full-length feature horror movies written ...,9.953,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-04-06,...,"[{'iso_639_1': 'es', 'name': 'Español'}, {'iso...",Released,False,6.9,815.0,-4.196210e+07,Not Profitable,4349,11.915068,1.293056
1181,820,JFK,False,40000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",en,New Orleans District Attorney Jim Garrison dis...,9.448,"[{'iso_3166_1': 'US', 'name': 'United States o...",1991-12-20,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.7,839.0,1.654055e+08,Profitable,9935,27.219178,0.650257
1333,334,Magnolia,False,37000000.0,"[{'id': 18, 'name': 'Drama'}]",en,An epic mosaic of many interrelated characters...,11.178,"[{'iso_3166_1': 'US', 'name': 'United States o...",1999-12-10,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.7,1455.0,1.145180e+07,Profitable,7023,19.241096,1.595258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4642,1424,November,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",en,Sophie Jacobs is going through the most diffic...,2.049,"[{'iso_3166_1': 'US', 'name': 'United States o...",2004-07-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.4,17.0,0.000000e+00,Not Profitable,5337,14.621918,0.014015
2427,16112,The Adventures of Elmo in Grouchland,False,0.0,"[{'id': 10402, 'name': 'Music'}, {'id': 10751,...",en,"Elmo loves his fuzzy, blue blanket, and would ...",1.989,"[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",1999-10-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.2,30.0,0.000000e+00,Not Profitable,7093,19.432877,0.026223
4612,26518,Old Joy,False,300000.0,"[{'id': 18, 'name': 'Drama'}]",en,"Soon to be a father, Mark feels the pressure o...",2.512,"[{'iso_3166_1': 'US', 'name': 'United States o...",2006-01-20,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.2,47.0,-3.000000e+05,Not Profitable,4790,13.123288,0.060835
4711,178862,Aroused,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,Get up close and personal with 16 of the most ...,2.389,"[{'iso_3166_1': 'US', 'name': 'United States o...",2013-02-20,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.6,18.0,0.000000e+00,Not Profitable,2202,6.032877,0.053951
2114,16690,Return to Never Land,False,20000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,"In 1940, the world is besieged by World War II...",10.535,"[{'iso_3166_1': 'AU', 'name': 'Australia'}, {'...",2002-02-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.2,670.0,8.986268e+07,Profitable,6226,17.057534,0.667202
4710,335244,Antarctic Edge: 70° South,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,"In 2014, scientists declared West Antarctic ic...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-04-17,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,1.0,0.000000e+00,Not Profitable,1416,3.879452,0.004944
2116,14873,The Jungle Book 2,False,20000000.0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",en,Mowgli has been living in the man-village with...,9.014,"[{'iso_3166_1': 'US', 'name': 'United States o...",2003-02-07,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,544.0,1.156800e+08,Profitable,5868,16.076712,0.537696
4641,51942,I Married a Strange Person!,False,250.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 16, 'nam...",en,It's a heartwarming story of a newlywed couple...,1.449,"[{'iso_3166_1': 'US', 'name': 'United States o...",1998-08-28,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.6,16.0,-4.700000e+01,Not Profitable,7492,20.526027,0.016231
1984,26672,The Thief and the Cobbler,False,28000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,It is written among the limitless constellatio...,4.053,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",1993-09-23,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,40.0,-2.733072e+07,Not Profitable,9292,25.457534,0.028842
4491,296943,The Hadza: Last of the First,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,A look at human origins in the very place of o...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-10-31,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.000000e+00,Not Profitable,1584,4.339726,0.000000
4721,266857,The Work and The Story,False,0.0,"[{'id': 35, 'name': 'Comedy'}]",en,"It is July, 2000 Richard Dutcher, the man who ...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2003-01-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.000000e+00,Not Profitable,5905,16.178082,0.000000
4441,3170,Bambi,False,858000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 18, '...",en,Bambi's tale unfolds from season to season as ...,16.426,"[{'iso_3166_1': 'US', 'name': 'United States o...",1942-08-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.9,2759.0,2.665892e+08,Profitable,27960,76.602740,0.680869
2805,12144,The Land Before Time,False,12300000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",en,An orphaned brontosaurus named Littlefoot sets...,14.492,"[{'iso_3166_1': 'IE', 'name': 'Ireland'}, {'is...",1988-11-18,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,1270.0,7.216085e+07,Profitable,11062,30.306849,0.803652
4668,70478,The Stewardesses,False,100000.0,"[{'id': 35, 'name': 'Comedy'}]",en,A single eventful night in the lives of a crew...,0.741,[],1969-07-25,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.3,5.0,2.690000e+07,Profitable,18118,49.638356,0.001187
4493,138976,Treachery,False,625000.0,"[{'id': 18, 'name': 'Drama'}]",en,Treachery centers on a man (Biehn) who is reun...,0.600,[],2013-05-16,...,[],Released,False,4.8,5.0,-6.250000e+05,Not Profitable,2117,5.800000,0.011337
2182,13682,Pooh's Heffalump Movie,False,20000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",en,Who or what exactly is a Heffalump? The lovabl...,9.397,"[{'iso_3166_1': 'US', 'name': 'United States o...",2005-02-11,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.5,187.0,3.290000e+07,Profitable,5133,14.063014,0.236801
4733,51130,Open Secret,False,0.0,"[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...",en,A couple discovers that their friend has gone ...,0.651,"[{'iso_3166_1': 'US', 'name': 'United States o...",1948-02-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,2.0,0.000000e+00,Not Profitable,25950,71.095890,0.000539
3663,292481,Henry & Me,False,5000000.0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",en,Henry &amp; Me tells the courageous story of J...,0.635,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-08-18,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.7,3.0,-5.000000e+06,Not Profitable,1658,4.542466,0.008504
4673,43595,She Done Him Wrong,False,200000.0,"[{'id': 35, 'name': 'Comedy'}]",en,New York singer and nightclub owner Lady Lou h...,1.768,"[{'iso_3166_1': 'US', 'name': 'United States o...",1933-02-09,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.7,36.0,2.000000e+06,Profitable,31433,86.117808,0.006528
4774,42497,Pink Narcissus,False,27000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,An erotic poem set in the fantasies of a young...,1.630,"[{'iso_3166_1': 'US', 'name': 'United States o...",1971-01-01,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.3,14.0,-2.700000e+04,Not Profitable,17593,48.200000,0.005013
1620,51162,Winnie the Pooh,False,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",en,"During an ordinary day in Hundred Acre Wood, W...",7.521,"[{'iso_3166_1': 'US', 'name': 'United States o...",2011-04-13,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.9,419.0,-1.554000e+07,Not Profitable,2881,7.893151,1.003506
4785,287625,Stories of Our Lives,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,Created by the members of a Nairobi-based arts...,0.600,"[{'iso_3166_1': 'KE', 'name': 'Kenya'}, {'iso_...",2014-09-05,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,0.0,0.0,0.000000e+00,Not Profitable,1640,4.493151,0.000000
4685,126141,The Case of the Grinning Cat,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,Paris 2002. Yellow cats appear on the walls. C...,0.600,"[{'iso_3166_1': 'FR', 'name': 'France'}]",2004-12-05,...,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,False,7.7,3.0,0.000000e+00,Not Profitable,5201,14.249315,0.004441
3403,294512,Alpha and Omega: The Legend of the Saw Tooth Cave,False,0.0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",en,The Alphas and Omegas share a thrilling advent...,1.477,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-07-21,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.0,8.0,0.000000e+00,Not Profitable,1686,4.619178,0.023725
4756,20981,The Call of Cthulhu,False,50000.0,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",en,A dying professor leaves his great-nephew a co...,3.271,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2005-01-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,61.0,-5.000000e+04,Not Profitable,5174,14.175342,0.082528
3354,24977,Michael Jordan to the Max,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,This documentary showcases basketball player M...,1.312,"[{'iso_3166_1': 'US', 'name': 'United States o...",2000-05-05,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.4,11.0,2.126853e+07,Profitable,6876,18.838356,0.011838
3471,57612,Dolphins and Whales: Tribes of the Ocean,False,6000000.0,"[{'id': 99, 'name': 'Documentary'}]",en,This documentary goes to coral reefs of the Ba...,0.719,"[{'iso_3166_1': 'BS', 'name': 'Bahamas'}, {'is...",2008-02-15,...,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,False,8.0,3.0,1.518876e+06,Profitable,4034,11.052055,0.005949
3626,78394,Sea Rex 3D: Journey to a Prehistoric World,False,5000000.0,"[{'id': 99, 'name': 'Documentary'}]",en,"Through the power of IMAX 3D, experience a won...",1.940,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",2010-05-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.4,12.0,-9.259770e+05,Not Profitable,3215,8.808219,0.027621

In [33]:
movies_df.count()

ID                      4769
Title                   4769
Adult                   4769
Budget                  4769
Genres                  4769
Language                4769
Overview                4769
Popularity              4769
Production Countries    4769
Release Date            4769
Revenue                 4769
Runtime                 4769
Spoken Languages        4769
Status                  4769
Video                   4769
Average Vote            4769
Vote Count              4769
Profit                  4769
Profitability           4769
Days Out                4769
Years Out               4769
Critical Acclaim        4769
dtype: int64

In [34]:
# remove films under an hour and removes films longer than 4 hours
movies_df = movies_df[movies_df["Runtime"]>60]
movies_df = movies_df[movies_df["Runtime"]<240]

In [35]:
movies_df[movies_df["Average Vote"]==0]

,ID,Title,Adult,Budget,Genres,Language,Overview,Popularity,Production Countries,Release Date,...,Spoken Languages,Status,Video,Average Vote,Vote Count,Profit,Profitability,Days Out,Years Out,Critical Acclaim
3670,447027,Running Forever,False,0.0,"[{'id': 10751, 'name': 'Family'}]",en,After being estranged since her mother's death...,0.603,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-10-27,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,1223,3.350685,0.0
3960,170480,The Deported,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",en,An Italian-American actor is deported to Mexic...,0.604,[],2010-06-15,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,3183,8.720548,0.0
3967,79587,Four Single Fathers,False,3.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,A comedy/drama about four Italian single fathe...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2009-01-15,...,"[{'iso_639_1': 'it', 'name': 'Italiano'}, {'is...",Released,False,0.0,0.0,-3.0,Not Profitable,3699,10.134247,0.0
4065,364083,Mi America,False,2100000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",en,A hate-crime has been committed in a the small...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-10-16,...,"[{'iso_639_1': 'es', 'name': 'Español'}, {'iso...",Released,False,0.0,0.0,-2096670.0,Not Profitable,1234,3.380822,0.0
4068,371085,Sharkskin,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,The Post War II story of Manhattan born Mike E...,0.600,[],2015-01-01,...,[],Released,False,0.0,0.0,0.0,Not Profitable,1522,4.169863,0.0
4305,114065,Down & Out With The Dolls,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",en,"The raunchy, spunky tale of the rise and fall ...",0.600,[],2003-03-20,...,[],Released,False,0.0,0.0,0.0,Not Profitable,5827,15.964384,0.0
4400,219716,Sparkler,False,0.0,[],en,Melba is a Californian trailer-park girl who i...,0.600,[],1999-03-19,...,[],Released,False,0.0,0.0,0.0,Not Profitable,7289,19.969863,0.0
4462,146269,The Young Unknowns,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,"Charlie, his sexy girlfriend, and his moronic ...",0.600,[],2000-03-12,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,6930,18.986301,0.0
4486,302579,Naturally Native,False,700000.0,"[{'id': 18, 'name': 'Drama'}]",en,"Naturally Native follows the lives, loves, pai...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",1999-10-08,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,-689492.0,Not Profitable,7086,19.413699,0.0
4491,296943,The Hadza: Last of the First,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,A look at human origins in the very place of o...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-10-31,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,1584,4.339726,0.0
4500,181940,Carousel of Revenge,False,0.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",en,When strangers Frank Delano and his Uncle Bobb...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-07-20,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,4244,11.627397,0.0
4508,70875,The Harvest (La Cosecha),False,56000.0,"[{'id': 99, 'name': 'Documentary'}]",en,The story of the children who work 12-14 hour ...,0.600,[],2011-07-29,...,[],Released,False,0.0,0.0,-56000.0,Not Profitable,2774,7.600000,0.0
4559,362765,The Sound and the Shadow,False,0.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 35, 'n...",en,"An allergy-ridden, eavesdropping sound enginee...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-10-19,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,1596,4.372603,0.0
4569,198370,Mutual Friends,False,0.0,[],en,Surprise parties rarely go well. This one is n...,0.849,[],2014-04-15,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,1783,4.884932,0.0
4589,43743,Fabled,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",en,Joseph just broke up with his girlfriend and i...,0.600,[],2002-01-01,...,[],Released,False,0.0,0.0,0.0,Not Profitable,6270,17.178082,0.0
4625,426067,Midnight Cabaret,False,0.0,"[{'id': 27, 'name': 'Horror'}]",en,A Broadway producer puts on a play with a Devi...,0.626,[],1990-01-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,10653,29.186301,0.0
4638,378237,Amidst the Devil's Wings,False,300000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",en,"Prequel to ""5th of a Degree.""",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-12-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,-300000.0,Not Profitable,1553,4.254795,0.0
4665,376010,Western Religion,False,0.0,"[{'id': 37, 'name': 'Western'}]",en,The year is 1879. Gunfighters from the far rea...,0.603,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-10-09,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,1241,3.400000,0.0
4674,194588,Short Cut to Nirvana: Kumbh Mela,False,0.0,[],en,Every 12 years over 70 million pilgrims gather...,0.600,[],2004-05-11,...,[],Released,False,0.0,0.0,0.0,Not Profitable,5409,14.819178,0.0
4692,361398,Theresa Is a Mother,False,0.0,"[{'id': 10402, 'name': 'Music'}, {'id': 35, 'n...",en,Singer/songwriter and single mother Theresa Mc...,0.603,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-09-25,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,1255,3.438356,0.0
4694,288927,Archaeology of a Woman,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,A woman's dementia uncovers secrets of a 30-ye...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-09-12,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,1633,4.473973,0.0
4708,354624,Heroes of Dirt,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",en,"Passionate BMX dirt jumper, Phin Cooper, wants...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-09-04,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,1276,3.495890,0.0
4714,282128,An American in Hollywood,False,0.0,[],en,A talented young filmmaker from New York sets ...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-07-18,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,1689,4.627397,0.0
4716,38786,The Blood of My Brother: A Story of Death in Iraq,False,0.0,[],en,THE BLOOD OF MY BROTHER goes behind the scenes...,0.600,[],2005-11-25,...,[],Released,False,0.0,0.0,0.0,Not Profitable,4846,13.276712,0.0
4721,266857,The Work and The Story,False,0.0,"[{'id': 35, 'name': 'Comedy'}]",en,"It is July, 2000 Richard Dutcher, the man who ...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2003-01-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,5905,16.178082,0.0
4780,366967,Dutch Kills,False,0.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",en,A desperate ex-con is forced to gather his old...,0.615,[],2015-10-02,...,[],Released,False,0.0,0.0,0.0,Not Profitable,1248,3.419178,0.0
4794,286939,Sanctuary: Quite a Conundrum,False,0.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...",en,"It should have been just a normal day of sex, ...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-01-20,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,0.0,0.0,0.0,Not Profitable,2599,7.120548,0.0

In [36]:
# Average vote of 0 means there are 0 reviews. Therefore, we should remove all films with 0 reviews
movies_df = movies_df[movies_df["Average Vote"]>0]

In [37]:
# there are a lot of 0 Budgets
movies_df["ID"][movies_df["Budget"]==0].count()

877

In [38]:
# a lot of the 0 budget films seem to be large movies (Alvin and the Chipmunks, etc.)
movies_df[movies_df["Budget"]==0]

,ID,Title,Adult,Budget,Genres,Language,Overview,Popularity,Production Countries,Release Date,...,Spoken Languages,Status,Video,Average Vote,Vote Count,Profit,Profitability,Days Out,Years Out,Critical Acclaim
359,258509,Alvin and the Chipmunks: The Road Chip,False,0.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",en,"Through a series of misunderstandings, Alvin, ...",11.281,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-12-17,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,806.0,233755553.0,Profitable,1172,3.210959,3.988737
409,16858,All That Jazz,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,"Joe Gideon is at the top of the heap, one of t...",6.283,"[{'iso_3166_1': 'US', 'name': 'United States o...",1979-12-20,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.4,144.0,37823676.0,Profitable,14318,39.227397,0.074424
463,161795,Déjà Vu,False,0.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",en,L.A. shop owner Dana and Englishman Sean meet ...,1.063,"[{'iso_3166_1': 'US', 'name': 'United States o...",1998-04-22,...,"[{'iso_639_1': 'hu', 'name': 'Magyar'}, {'iso_...",Released,False,6.5,4.0,0.0,Not Profitable,7620,20.876712,0.003412
474,330770,Evolution,False,0.0,"[{'id': 9648, 'name': 'Mystery'}, {'id': 18, '...",fr,11-year-old Nicolas lives with his mother in a...,4.418,"[{'iso_3166_1': 'BE', 'name': 'Belgium'}, {'is...",2015-09-14,...,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,False,6.3,72.0,0.0,Not Profitable,1266,3.468493,0.358294
475,9433,The Edge,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,The plane carrying wealthy Charles Morse crash...,8.246,"[{'iso_3166_1': 'US', 'name': 'United States o...",1997-09-06,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.7,548.0,43312294.0,Profitable,7848,21.501370,0.467839
489,36970,Oceans,False,0.0,"[{'id': 99, 'name': 'Documentary'}, {'id': 107...",en,"An ecological drama/documentary, filmed throug...",6.416,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",2009-10-17,...,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,False,7.2,161.0,19406406.0,Profitable,3424,9.380822,0.338551
542,25769,Carriers,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",en,Four friends fleeing a viral pandemic soon lea...,6.597,"[{'iso_3166_1': 'US', 'name': 'United States o...",2009-09-04,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,437.0,5802422.0,Profitable,3467,9.498630,0.731064
601,11535,Rollerball,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",en,"In this fast action-packed thriller, Jonathan,...",6.661,"[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",2002-02-08,...,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,False,3.8,198.0,0.0,Not Profitable,6232,17.073973,0.120732
691,11199,Wild Hogs,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,"Restless and ready for adventure, four suburba...",7.308,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-03-02,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,1141.0,253625427.0,Profitable,4384,12.010959,1.509535
721,10628,Kangaroo Jack,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 12, 'nam...",en,"Two childhood friends, a New York hairstylist ...",6.527,"[{'iso_3166_1': 'AU', 'name': 'Australia'}, {'...",2003-01-17,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.4,326.0,0.0,Not Profitable,5889,16.134247,0.243573
745,10040,Miss Congeniality 2: Armed and Fabulous,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",en,After her triumph at the Miss United States pa...,10.390,"[{'iso_3166_1': 'US', 'name': 'United States o...",2005-03-11,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.6,886.0,0.0,Not Profitable,5105,13.986301,0.971910
757,87825,Trouble with the Curve,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,"Slowed by age and failing eyesight, crack base...",7.735,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-09-21,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,575.0,0.0,Not Profitable,2354,6.449315,1.636576
847,13260,Semi-Pro,False,0.0,"[{'id': 35, 'name': 'Comedy'}]",en,"Jackie Moon is the owner, promoter, coach, and...",6.244,"[{'iso_3166_1': 'US', 'name': 'United States o...",2008-02-28,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.5,394.0,33472850.0,Profitable,4021,11.016438,0.538921
881,39437,Beloved,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",en,After Paul D. finds his old slave friend Sethe...,3.182,"[{'iso_3166_1': 'US', 'name': 'United States o...",1998-10-16,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.7,41.0,0.0,Not Profitable,7443,20.391781,0.031399
882,1950,Lucky You,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,A professional poker player whose astounding l...,5.411,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-05-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.5,135.0,5761917.0,Profitable,4324,11.846575,0.171716
915,9441,Stepmom,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,Jackie is a divorced mother of two. Isabel is ...,8.673,"[{'iso_3166_1': 'US', 'name': 'United States o...",1998-12-25,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,571.0,0.0,Not Profitable,7373,20.200000,0.542113
1007,96724,Anna Karenina,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,"Trapped in a loveless marriage, aristocrat Ann...",9.742,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",2012-09-06,...,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,False,6.6,1180.0,68929150.0,Profitable,2369,6.490411,3.287463
1011,53953,The Tooth Fairy,False,0.0,"[{'id': 27, 'name': 'Horror'}]",de,A woman and her daughter (Nicole Muñoz) encoun...,1.557,[],2006-08-08,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,4.2,18.0,0.0,Not Profitable,4590,12.575342,0.016471
1016,11232,Kate & Leopold,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",en,When her scientist ex-boyfriend discovers a po...,8.580,"[{'iso_3166_1': 'US', 'name': 'United States o...",2001-12-25,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.1,680.0,0.0,Not Profitable,6277,17.197260,0.660825
1023,7504,Earth,False,0.0,"[{'id': 18, 'name': 'Drama'}]",hi,It's 1947 and the borderlines between India an...,1.230,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1998-09-16,...,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,False,6.7,11.0,528972.0,Profitable,7473,20.473973,0.009862
1028,593,Solaris,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",ru,A psychologist is sent to a space station orbi...,7.934,"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1972-03-20,...,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",Released,False,7.9,619.0,0.0,Not Profitable,17149,46.983562,0.285154
1032,11467,America's Sweethearts,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en,In the midst of a nasty public breakup of marr...,7.374,"[{'iso_3166_1': 'US', 'name': 'United States o...",2001-07-17,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.6,426.0,138191428.0,Profitable,6438,17.638356,0.370550
1066,27983,"Yours, Mine and Ours",False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,When a widower with 10 children marries a wido...,4.827,"[{'iso_3166_1': 'US', 'name': 'United States o...",1968-04-24,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.6,51.0,0.0,Not Profitable,18575,50.890411,0.018121
1080,4688,Across the Universe,False,0.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",en,When young dockworker Jude leaves Liverpool to...,7.977,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-09-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.3,717.0,0.0,Not Profitable,4188,11.473973,1.249785
1126,87826,Here Comes the Boom,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",en,A high school biology teacher moonlights as a ...,7.529,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-10-11,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.1,781.0,73100172.0,Profitable,2334,6.394521,2.041174
1142,280391,Why I Did (Not) Eat My Father,False,0.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 35, '...",fr,Based on the novel 'Evolution Man' by Roy Lewi...,6.786,"[{'iso_3166_1': 'FR', 'name': 'France'}]",2015-04-08,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.3,221.0,0.0,Not Profitable,1425,3.904110,0.821965
1202,9930,Legal Eagles,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",en,District Attorney Tom Logan is set for higher ...,4.870,"[{'iso_3166_1': 'US', 'name': 'United States o...",1986-06-18,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.9,81.0,0.0,Not Profitable,11946,32.728767,0.040005
1206,71864,The Odd Life of Timothy Green,False,0.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",en,A childless couple bury a box in their backyar...,7.129,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-08-15,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.7,578.0,51854875.0,Profitable,2391,6.550685,1.619657
1225,10154,Mickey Blue Eyes,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",en,An English auctioneer proposes to the daughter...,7.179,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",1999-08-16,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.4,217.0,0.0,Not Profitable,7139,19.558904,0.164141
1248,15556,At First Sight,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,A blind man has an operation to regain his sig...,8.433,"[{'iso_3166_1': 'US', 'name': 'United States o...",1999-01-15,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.9,97.0,0.0,Not Profitable,7352,20.142466,0.077843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4747,139998,Supporting Characters,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,Two New York film editors balance their person...,1.103,[],2012-01-23,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,13.0,0.0,Not Profitable,2596,7.112329,0.033552
4749,16388,The Brothers McMullen,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,Deals with the lives of the three Irish Cathol...,1.978,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-08-09,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.0,37.0,0.0,Not Profitable,8607,23.580822,0.025793
4751,42109,Gabriela,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",pt,"In 1925, Gabriela, a poor, uneducated, yet cha...",1.400,"[{'iso_3166_1': 'BR', 'name': 'Brazil'}]",1983-03-24,...,"[{'iso_639_1': 'pt', 'name': 'Português'}]",Released,False,6.2,5.0,0.0,Not Profitable,13128,35.967123,0.002361
4754,84659,The Naked Ape,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,The Naked Ape is a coming-of-age film followin...,0.600,[],2006-09-16,...,[],Released,False,4.0,2.0,0.0,Not Profitable,4551,12.468493,0.001758
4757,174362,Bending Steel,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,"The Cyclone, The Freakshow, The Mermaid Parade...",0.627,[],2013-04-20,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.0,1.0,0.0,Not Profitable,2143,5.871233,0.002333
4760,158895,This Is Martin Bonner,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,"Two men, at opposite ends of the social spectr...",1.391,"[{'iso_3166_1': 'US', 'name': 'United States o...",2013-06-28,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,8.0,0.0,Not Profitable,2074,5.682192,0.022372
4761,222250,A True Story,False,0.0,"[{'id': 35, 'name': 'Comedy'}]",en,Mike and Matt own nothing and share everything...,0.600,[],2013-09-20,...,[],Released,False,6.2,3.0,0.0,Not Profitable,1990,5.452055,0.009347
4763,125537,Smiling Fish & Goat On Fire,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en,Two brothers share a house in LA's Fairfax dis...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",1999-09-16,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,2.0,0.0,Not Profitable,7108,19.473973,0.001970
4764,326576,Dawn of the Crescent Moon,False,0.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",en,A group of college students travel to a small ...,0.600,[],2014-04-05,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,2.0,1.0,0.0,Not Profitable,1793,4.912329,0.001115
4765,228550,Raymond Did It,False,0.0,"[{'id': 27, 'name': 'Horror'}]",en,Mentally challenged Raymond Rourke gets blamed...,0.600,[],2011-03-27,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,3.7,8.0,0.0,Not Profitable,2898,7.939726,0.010214
4766,13963,The Last Waltz,False,0.0,"[{'id': 99, 'name': 'Documentary'}, {'id': 104...",en,Martin Scorsese's documentary intertwines foot...,4.797,"[{'iso_3166_1': 'US', 'name': 'United States o...",1978-05-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.8,95.0,321952.0,Profitable,14916,40.865753,0.049678
4768,44770,The Exploding Girl,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,"On a summer break from college, Ivy, a young e...",1.756,[],2009-04-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.0,20.0,0.0,Not Profitable,3602,9.868493,0.033315
4769,69382,The Legend of God's Gun,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...",en,A gun-slinging preacher returns to the debauch...,0.600,[],2007-07-08,...,[],Released,False,2.0,1.0,0.0,Not Profitable,4256,11.660274,0.000470
4771,220490,Her Cry: La Llorona Investigation,False,0.0,"[{'id': 27, 'name': 'Horror'}]",en,"Crew of ""Paranormal Legends"" went to film thei...",0.657,[],2013-04-19,...,[],Released,False,5.0,2.0,0.0,Not Profitable,2144,5.873973,0.004664
4775,33693,Funny Ha Ha,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,"Unsure of what to do next, 23-year-old Marnie ...",1.405,"[{'iso_3166_1': 'US', 'name': 'United States o...",2002-09-20,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.2,12.0,76901.0,Profitable,6008,16.460274,0.012383
4776,14585,In the Company of Men,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,Two business executives--one an avowed misogyn...,3.320,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1997-03-28,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,59.0,0.0,Not Profitable,8010,21.945205,0.051561
4777,185465,Manito,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,"Fifteen years ago, their Washington Heights ne...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2002-01-15,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.3,4.0,0.0,Not Profitable,6256,17.139726,0.003389
4778,38780,Rampage,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",en,The boredom of small town life is eating Bill ...,6.141,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",2009-08-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.9,190.0,0.0,Not Profitable,3488,9.556164,0.321388
4782,17345,Flywheel,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",en,"Jay Austin wants to sell you a used car, but w...",1.859,"[{'iso_3166_1': 'US', 'name': 'United States o...",2003-01-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.5,27.0,0.0,Not Profitable,5905,16.178082,0.029721
4783,226458,Exeter,False,0.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...",en,"During an all-night, drug-fueled party at an a...",4.073,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-01-16,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.7,119.0,0.0,Not Profitable,1507,4.128767,0.371135
4784,24055,The Puffy Chair,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,Josh's life is pretty much in the toilet. He's...,1.083,[],2005-01-17,...,[],Released,False,6.1,21.0,0.0,Not Profitable,5158,14.131507,0.024835
4786,44990,Breaking Upwards,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en,"'Breaking Upwards' explores a young, real-life...",1.720,"[{'iso_3166_1': 'US', 'name': 'United States o...",2009-03-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.7,16.0,0.0,Not Profitable,3641,9.975342,0.025048
4787,86304,All Superheroes Must Die,False,0.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",en,"Masked vigilantes Charge (Jason Trost), Cutthr...",2.311,[],2011-10-26,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,3.9,18.0,0.0,Not Profitable,2685,7.356164,0.026145
4789,39851,Clean,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,"After losing her husband to a heroin overdose,...",2.636,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2004-09-01,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.8,26.0,0.0,Not Profitable,5296,14.509589,0.033384
4790,13898,The Circle,False,0.0,"[{'id': 18, 'name': 'Drama'}]",fa,Various women struggle to function in the oppr...,1.332,"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",2000-09-08,...,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,False,6.9,29.0,0.0,Not Profitable,6750,18.493151,0.029644
4793,182291,On The Downlow,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,Isaac and Angel are two young Latinos involved...,0.932,"[{'iso_3166_1': 'US', 'name': 'United States o...",2004-04-11,...,[],Released,False,5.3,3.0,0.0,Not Profitable,5439,14.901370,0.002923
4795,124606,Bang,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,A young woman in L.A. is having a bad day: she...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-09-09,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.0,1.0,0.0,Not Profitable,8576,23.495890,0.000700
4800,231617,"Signed, Sealed, Delivered",False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,A mix up on her first day of work sends Shane ...,2.659,"[{'iso_3166_1': 'US', 'name': 'United States o...",2013-10-12,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,11.0,0.0,Not Profitable,1968,5.391781,0.039126
4801,126186,纽约客@上海,False,0.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",zh,When ambitious New York attorney Sam is sent t...,1.506,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-05-03,...,"[{'iso_639_1': 'zh', 'name': '普通话'}, {'iso_639...",Released,False,6.0,12.0,0.0,Not Profitable,2495,6.835616,0.028858
4802,25975,My Date with Drew,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,Ever since the second grade when he first saw ...,1.453,"[{'iso_3166_1': 'US', 'name': 'United States o...",2005-08-05,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.1,22.0,0.0,Not Profitable,4958,13.583562,0.027067

In [39]:
movies_df["Budget"].max()

380000000.0

In [40]:
movies_df[movies_df["Budget"]==0]

,ID,Title,Adult,Budget,Genres,Language,Overview,Popularity,Production Countries,Release Date,...,Spoken Languages,Status,Video,Average Vote,Vote Count,Profit,Profitability,Days Out,Years Out,Critical Acclaim
359,258509,Alvin and the Chipmunks: The Road Chip,False,0.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",en,"Through a series of misunderstandings, Alvin, ...",11.281,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-12-17,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,806.0,233755553.0,Profitable,1172,3.210959,3.988737
409,16858,All That Jazz,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,"Joe Gideon is at the top of the heap, one of t...",6.283,"[{'iso_3166_1': 'US', 'name': 'United States o...",1979-12-20,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.4,144.0,37823676.0,Profitable,14318,39.227397,0.074424
463,161795,Déjà Vu,False,0.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",en,L.A. shop owner Dana and Englishman Sean meet ...,1.063,"[{'iso_3166_1': 'US', 'name': 'United States o...",1998-04-22,...,"[{'iso_639_1': 'hu', 'name': 'Magyar'}, {'iso_...",Released,False,6.5,4.0,0.0,Not Profitable,7620,20.876712,0.003412
474,330770,Evolution,False,0.0,"[{'id': 9648, 'name': 'Mystery'}, {'id': 18, '...",fr,11-year-old Nicolas lives with his mother in a...,4.418,"[{'iso_3166_1': 'BE', 'name': 'Belgium'}, {'is...",2015-09-14,...,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,False,6.3,72.0,0.0,Not Profitable,1266,3.468493,0.358294
475,9433,The Edge,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,The plane carrying wealthy Charles Morse crash...,8.246,"[{'iso_3166_1': 'US', 'name': 'United States o...",1997-09-06,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.7,548.0,43312294.0,Profitable,7848,21.501370,0.467839
489,36970,Oceans,False,0.0,"[{'id': 99, 'name': 'Documentary'}, {'id': 107...",en,"An ecological drama/documentary, filmed throug...",6.416,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",2009-10-17,...,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,False,7.2,161.0,19406406.0,Profitable,3424,9.380822,0.338551
542,25769,Carriers,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",en,Four friends fleeing a viral pandemic soon lea...,6.597,"[{'iso_3166_1': 'US', 'name': 'United States o...",2009-09-04,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,437.0,5802422.0,Profitable,3467,9.498630,0.731064
601,11535,Rollerball,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",en,"In this fast action-packed thriller, Jonathan,...",6.661,"[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",2002-02-08,...,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,False,3.8,198.0,0.0,Not Profitable,6232,17.073973,0.120732
691,11199,Wild Hogs,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,"Restless and ready for adventure, four suburba...",7.308,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-03-02,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,1141.0,253625427.0,Profitable,4384,12.010959,1.509535
721,10628,Kangaroo Jack,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 12, 'nam...",en,"Two childhood friends, a New York hairstylist ...",6.527,"[{'iso_3166_1': 'AU', 'name': 'Australia'}, {'...",2003-01-17,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.4,326.0,0.0,Not Profitable,5889,16.134247,0.243573
745,10040,Miss Congeniality 2: Armed and Fabulous,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",en,After her triumph at the Miss United States pa...,10.390,"[{'iso_3166_1': 'US', 'name': 'United States o...",2005-03-11,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.6,886.0,0.0,Not Profitable,5105,13.986301,0.971910
757,87825,Trouble with the Curve,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,"Slowed by age and failing eyesight, crack base...",7.735,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-09-21,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,575.0,0.0,Not Profitable,2354,6.449315,1.636576
847,13260,Semi-Pro,False,0.0,"[{'id': 35, 'name': 'Comedy'}]",en,"Jackie Moon is the owner, promoter, coach, and...",6.244,"[{'iso_3166_1': 'US', 'name': 'United States o...",2008-02-28,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.5,394.0,33472850.0,Profitable,4021,11.016438,0.538921
881,39437,Beloved,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",en,After Paul D. finds his old slave friend Sethe...,3.182,"[{'iso_3166_1': 'US', 'name': 'United States o...",1998-10-16,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.7,41.0,0.0,Not Profitable,7443,20.391781,0.031399
882,1950,Lucky You,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,A professional poker player whose astounding l...,5.411,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-05-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.5,135.0,5761917.0,Profitable,4324,11.846575,0.171716
915,9441,Stepmom,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,Jackie is a divorced mother of two. Isabel is ...,8.673,"[{'iso_3166_1': 'US', 'name': 'United States o...",1998-12-25,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,571.0,0.0,Not Profitable,7373,20.200000,0.542113
1007,96724,Anna Karenina,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,"Trapped in a loveless marriage, aristocrat Ann...",9.742,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",2012-09-06,...,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,False,6.6,1180.0,68929150.0,Profitable,2369,6.490411,3.287463
1011,53953,The Tooth Fairy,False,0.0,"[{'id': 27, 'name': 'Horror'}]",de,A woman and her daughter (Nicole Muñoz) encoun...,1.557,[],2006-08-08,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,4.2,18.0,0.0,Not Profitable,4590,12.575342,0.016471
1016,11232,Kate & Leopold,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",en,When her scientist ex-boyfriend discovers a po...,8.580,"[{'iso_3166_1': 'US', 'name': 'United States o...",2001-12-25,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.1,680.0,0.0,Not Profitable,6277,17.197260,0.660825
1023,7504,Earth,False,0.0,"[{'id': 18, 'name': 'Drama'}]",hi,It's 1947 and the borderlines between India an...,1.230,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1998-09-16,...,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,False,6.7,11.0,528972.0,Profitable,7473,20.473973,0.009862
1028,593,Solaris,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",ru,A psychologist is sent to a space station orbi...,7.934,"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1972-03-20,...,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",Released,False,7.9,619.0,0.0,Not Profitable,17149,46.983562,0.285154
1032,11467,America's Sweethearts,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en,In the midst of a nasty public breakup of marr...,7.374,"[{'iso_3166_1': 'US', 'name': 'United States o...",2001-07-17,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.6,426.0,138191428.0,Profitable,6438,17.638356,0.370550
1066,27983,"Yours, Mine and Ours",False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,When a widower with 10 children marries a wido...,4.827,"[{'iso_3166_1': 'US', 'name': 'United States o...",1968-04-24,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.6,51.0,0.0,Not Profitable,18575,50.890411,0.018121
1080,4688,Across the Universe,False,0.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",en,When young dockworker Jude leaves Liverpool to...,7.977,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-09-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.3,717.0,0.0,Not Profitable,4188,11.473973,1.249785
1126,87826,Here Comes the Boom,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",en,A high school biology teacher moonlights as a ...,7.529,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-10-11,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.1,781.0,73100172.0,Profitable,2334,6.394521,2.041174
1142,280391,Why I Did (Not) Eat My Father,False,0.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 35, '...",fr,Based on the novel 'Evolution Man' by Roy Lewi...,6.786,"[{'iso_3166_1': 'FR', 'name': 'France'}]",2015-04-08,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.3,221.0,0.0,Not Profitable,1425,3.904110,0.821965
1202,9930,Legal Eagles,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",en,District Attorney Tom Logan is set for higher ...,4.870,"[{'iso_3166_1': 'US', 'name': 'United States o...",1986-06-18,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.9,81.0,0.0,Not Profitable,11946,32.728767,0.040005
1206,71864,The Odd Life of Timothy Green,False,0.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",en,A childless couple bury a box in their backyar...,7.129,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-08-15,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.7,578.0,51854875.0,Profitable,2391,6.550685,1.619657
1225,10154,Mickey Blue Eyes,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",en,An English auctioneer proposes to the daughter...,7.179,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",1999-08-16,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.4,217.0,0.0,Not Profitable,7139,19.558904,0.164141
1248,15556,At First Sight,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,A blind man has an operation to regain his sig...,8.433,"[{'iso_3166_1': 'US', 'name': 'United States o...",1999-01-15,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.9,97.0,0.0,Not Profitable,7352,20.142466,0.077843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4747,139998,Supporting Characters,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,Two New York film editors balance their person...,1.103,[],2012-01-23,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,13.0,0.0,Not Profitable,2596,7.112329,0.033552
4749,16388,The Brothers McMullen,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,Deals with the lives of the three Irish Cathol...,1.978,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-08-09,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.0,37.0,0.0,Not Profitable,8607,23.580822,0.025793
4751,42109,Gabriela,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",pt,"In 1925, Gabriela, a poor, uneducated, yet cha...",1.400,"[{'iso_3166_1': 'BR', 'name': 'Brazil'}]",1983-03-24,...,"[{'iso_639_1': 'pt', 'name': 'Português'}]",Released,False,6.2,5.0,0.0,Not Profitable,13128,35.967123,0.002361
4754,84659,The Naked Ape,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,The Naked Ape is a coming-of-age film followin...,0.600,[],2006-09-16,...,[],Released,False,4.0,2.0,0.0,Not Profitable,4551,12.468493,0.001758
4757,174362,Bending Steel,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,"The Cyclone, The Freakshow, The Mermaid Parade...",0.627,[],2013-04-20,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.0,1.0,0.0,Not Profitable,2143,5.871233,0.002333
4760,158895,This Is Martin Bonner,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,"Two men, at opposite ends of the social spectr...",1.391,"[{'iso_3166_1': 'US', 'name': 'United States o...",2013-06-28,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,8.0,0.0,Not Profitable,2074,5.682192,0.022372
4761,222250,A True Story,False,0.0,"[{'id': 35, 'name': 'Comedy'}]",en,Mike and Matt own nothing and share everything...,0.600,[],2013-09-20,...,[],Released,False,6.2,3.0,0.0,Not Profitable,1990,5.452055,0.009347
4763,125537,Smiling Fish & Goat On Fire,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en,Two brothers share a house in LA's Fairfax dis...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",1999-09-16,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,2.0,0.0,Not Profitable,7108,19.473973,0.001970
4764,326576,Dawn of the Crescent Moon,False,0.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",en,A group of college students travel to a small ...,0.600,[],2014-04-05,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,2.0,1.0,0.0,Not Profitable,1793,4.912329,0.001115
4765,228550,Raymond Did It,False,0.0,"[{'id': 27, 'name': 'Horror'}]",en,Mentally challenged Raymond Rourke gets blamed...,0.600,[],2011-03-27,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,3.7,8.0,0.0,Not Profitable,2898,7.939726,0.010214
4766,13963,The Last Waltz,False,0.0,"[{'id': 99, 'name': 'Documentary'}, {'id': 104...",en,Martin Scorsese's documentary intertwines foot...,4.797,"[{'iso_3166_1': 'US', 'name': 'United States o...",1978-05-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.8,95.0,321952.0,Profitable,14916,40.865753,0.049678
4768,44770,The Exploding Girl,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,"On a summer break from college, Ivy, a young e...",1.756,[],2009-04-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.0,20.0,0.0,Not Profitable,3602,9.868493,0.033315
4769,69382,The Legend of God's Gun,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...",en,A gun-slinging preacher returns to the debauch...,0.600,[],2007-07-08,...,[],Released,False,2.0,1.0,0.0,Not Profitable,4256,11.660274,0.000470
4771,220490,Her Cry: La Llorona Investigation,False,0.0,"[{'id': 27, 'name': 'Horror'}]",en,"Crew of ""Paranormal Legends"" went to film thei...",0.657,[],2013-04-19,...,[],Released,False,5.0,2.0,0.0,Not Profitable,2144,5.873973,0.004664
4775,33693,Funny Ha Ha,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,"Unsure of what to do next, 23-year-old Marnie ...",1.405,"[{'iso_3166_1': 'US', 'name': 'United States o...",2002-09-20,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.2,12.0,76901.0,Profitable,6008,16.460274,0.012383
4776,14585,In the Company of Men,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,Two business executives--one an avowed misogyn...,3.320,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1997-03-28,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,59.0,0.0,Not Profitable,8010,21.945205,0.051561
4777,185465,Manito,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,"Fifteen years ago, their Washington Heights ne...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2002-01-15,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.3,4.0,0.0,Not Profitable,6256,17.139726,0.003389
4778,38780,Rampage,False,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",en,The boredom of small town life is eating Bill ...,6.141,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",2009-08-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.9,190.0,0.0,Not Profitable,3488,9.556164,0.321388
4782,17345,Flywheel,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",en,"Jay Austin wants to sell you a used car, but w...",1.859,"[{'iso_3166_1': 'US', 'name': 'United States o...",2003-01-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.5,27.0,0.0,Not Profitable,5905,16.178082,0.029721
4783,226458,Exeter,False,0.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...",en,"During an all-night, drug-fueled party at an a...",4.073,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-01-16,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.7,119.0,0.0,Not Profitable,1507,4.128767,0.371135
4784,24055,The Puffy Chair,False,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,Josh's life is pretty much in the toilet. He's...,1.083,[],2005-01-17,...,[],Released,False,6.1,21.0,0.0,Not Profitable,5158,14.131507,0.024835
4786,44990,Breaking Upwards,False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en,"'Breaking Upwards' explores a young, real-life...",1.720,"[{'iso_3166_1': 'US', 'name': 'United States o...",2009-03-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.7,16.0,0.0,Not Profitable,3641,9.975342,0.025048
4787,86304,All Superheroes Must Die,False,0.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",en,"Masked vigilantes Charge (Jason Trost), Cutthr...",2.311,[],2011-10-26,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,3.9,18.0,0.0,Not Profitable,2685,7.356164,0.026145
4789,39851,Clean,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,"After losing her husband to a heroin overdose,...",2.636,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2004-09-01,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.8,26.0,0.0,Not Profitable,5296,14.509589,0.033384
4790,13898,The Circle,False,0.0,"[{'id': 18, 'name': 'Drama'}]",fa,Various women struggle to function in the oppr...,1.332,"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",2000-09-08,...,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,False,6.9,29.0,0.0,Not Profitable,6750,18.493151,0.029644
4793,182291,On The Downlow,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,Isaac and Angel are two young Latinos involved...,0.932,"[{'iso_3166_1': 'US', 'name': 'United States o...",2004-04-11,...,[],Released,False,5.3,3.0,0.0,Not Profitable,5439,14.901370,0.002923
4795,124606,Bang,False,0.0,"[{'id': 18, 'name': 'Drama'}]",en,A young woman in L.A. is having a bad day: she...,0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-09-09,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.0,1.0,0.0,Not Profitable,8576,23.495890,0.000700
4800,231617,"Signed, Sealed, Delivered",False,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,A mix up on her first day of work sends Shane ...,2.659,"[{'iso_3166_1': 'US', 'name': 'United States o...",2013-10-12,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,11.0,0.0,Not Profitable,1968,5.391781,0.039126
4801,126186,纽约客@上海,False,0.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",zh,When ambitious New York attorney Sam is sent t...,1.506,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-05-03,...,"[{'iso_639_1': 'zh', 'name': '普通话'}, {'iso_639...",Released,False,6.0,12.0,0.0,Not Profitable,2495,6.835616,0.028858
4802,25975,My Date with Drew,False,0.0,"[{'id': 99, 'name': 'Documentary'}]",en,Ever since the second grade when he first saw ...,1.453,"[{'iso_3166_1': 'US', 'name': 'United States o...",2005-08-05,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.1,22.0,0.0,Not Profitable,4958,13.583562,0.027067

In [41]:
movies_df["Budget"].describe()

count    4.729000e+03
mean     2.977710e+07
std      4.075508e+07
min      0.000000e+00
25%      1.600000e+06
50%      1.500000e+07
75%      4.000000e+07
max      3.800000e+08
Name: Budget, dtype: float64

In [42]:
movies_df = movies_df[movies_df["Budget"]>=100000]

In [43]:
# movies are expensive. A movie like Tangerine is a critically acclaimed film, but was filmed on a $100k budget. To put this budget in perspective, the entire film was filmed on an iPhone.
# I am making the assumption that films below $100k budget probably aren't the types of films we'd want to compare in this analysis
movies_df.sort_values("Budget",ascending=True)

,ID,Title,Adult,Budget,Genres,Language,Overview,Popularity,Production Countries,Release Date,...,Spoken Languages,Status,Video,Average Vote,Vote Count,Profit,Profitability,Days Out,Years Out,Critical Acclaim
4138,115210,Stitches,False,100000.0,"[{'id': 27, 'name': 'Horror'}]",en,"The clumsy and unfunny clown Richard ""Stitches...",5.426,"[{'iso_3166_1': 'IE', 'name': 'Ireland'}]",2012-05-19,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.6,132.0,-5.000000e+03,Not Profitable,2479,6.791781,0.298185
4724,985,Eraserhead,False,100000.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 27, 'na...",en,Henry Spencer tries to survive his industrial ...,8.201,"[{'iso_3166_1': 'US', 'name': 'United States o...",1977-03-19,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.6,941.0,6.900000e+06,Profitable,15324,41.983562,0.466693
4723,299245,The Gallows,False,100000.0,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",en,20 years after a horrific accident during a sm...,6.167,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-07-10,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.8,561.0,4.256441e+07,Profitable,1332,3.649315,2.021622
4722,18925,Facing the Giants,False,100000.0,"[{'id': 18, 'name': 'Drama'}]",en,A losing coach with an underdog football team ...,7.013,"[{'iso_3166_1': 'US', 'name': 'United States o...",2006-09-29,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.9,127.0,1.007833e+07,Profitable,4538,12.432877,0.193103
4700,55420,Another Earth,False,100000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",en,On the night of the discovery of a duplicate E...,7.558,"[{'iso_3166_1': 'US', 'name': 'United States o...",2011-07-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,809.0,1.676935e+06,Profitable,2781,7.619178,1.949047
4668,70478,The Stewardesses,False,100000.0,"[{'id': 35, 'name': 'Comedy'}]",en,A single eventful night in the lives of a crew...,0.741,[],1969-07-25,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.3,5.0,2.690000e+07,Profitable,18118,49.638356,0.001187
3737,10331,Night of the Living Dead,False,114000.0,"[{'id': 27, 'name': 'Horror'}]",en,A group of people try to survive an attack of ...,12.267,"[{'iso_3166_1': 'US', 'name': 'United States o...",1968-10-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.7,979.0,2.988600e+07,Profitable,18415,50.452055,0.409357
4719,40652,The Married Woman,False,120000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",fr,A superficial woman has conflict between choos...,3.864,"[{'iso_3166_1': 'FR', 'name': 'France'}]",1964-12-04,...,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,False,7.4,37.0,-1.200000e+05,Not Profitable,19812,54.279452,0.013820
4718,18632,A Dog's Breakfast,False,120000.0,"[{'id': 35, 'name': 'Comedy'}]",en,If you've never been good at anything in your ...,2.132,"[{'iso_3166_1': 'CA', 'name': 'Canada'}]",2007-03-03,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.3,35.0,-1.200000e+05,Not Profitable,4383,12.008219,0.050308
4717,84355,Your Sister's Sister,False,125000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,Iris invites her friend Jack to stay at her fa...,5.686,"[{'iso_3166_1': 'US', 'name': 'United States o...",2011-09-11,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.6,186.0,3.075000e+06,Profitable,2730,7.479452,0.449670
4514,83,Open Water,False,130000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",en,Two divers are left out at sea without a boat....,6.929,"[{'iso_3166_1': 'US', 'name': 'United States o...",2003-12-29,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.4,543.0,5.453795e+07,Profitable,5543,15.186301,0.528992
3498,58882,Snow Flower and the Secret Fan,False,134005.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,A story set in 19th century China and centered...,2.246,"[{'iso_3166_1': 'CN', 'name': 'China'}]",2011-07-15,...,"[{'iso_639_1': 'zh', 'name': '普通话'}, {'iso_639...",Released,False,5.9,37.0,1.198226e+06,Profitable,2788,7.638356,0.078300
4703,39141,Tadpole,False,150000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,"Beautiful, sophisticated women are all over Os...",3.070,"[{'iso_3166_1': 'US', 'name': 'United States o...",2002-11-01,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.8,30.0,2.741288e+06,Profitable,5966,16.345205,0.029165
4701,5822,Sweet Sweetback's Baadasssss Song,False,150000.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",en,After saving a Black Panther from some racist ...,2.439,"[{'iso_3166_1': 'US', 'name': 'United States o...",1971-04-23,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.3,34.0,1.505000e+07,Profitable,17481,47.893151,0.010308
4704,5723,Once,False,160000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",en,A vacuum repairman moonlights as a street musi...,6.739,"[{'iso_3166_1': 'IE', 'name': 'Ireland'}]",2007-03-23,...,"[{'iso_639_1': 'cs', 'name': 'Český'}, {'iso_6...",Released,False,7.5,664.0,2.055051e+07,Profitable,4363,11.953425,1.141416
4713,1779,Roger & Me,False,160000.0,"[{'id': 99, 'name': 'Documentary'}, {'id': 36,...",en,A documentary about the closure of General Mot...,5.036,"[{'iso_3166_1': 'US', 'name': 'United States o...",1989-09-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.3,144.0,6.546368e+06,Profitable,10775,29.520548,0.097559
4695,21334,Children of Heaven,False,180000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",fa,Zohre's shoes are gone; her older brother Ali ...,5.664,"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",1997-08-01,...,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,False,7.9,199.0,7.454020e+05,Profitable,7884,21.600000,0.199404
4675,54897,The Grace Card,False,200000.0,"[{'id': 18, 'name': 'Drama'}]",en,Everything can change in an instant ... and ta...,1.740,"[{'iso_3166_1': 'US', 'name': 'United States o...",2011-02-25,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.4,17.0,2.095733e+06,Profitable,2928,8.021918,0.037158
4673,43595,She Done Him Wrong,False,200000.0,"[{'id': 35, 'name': 'Comedy'}]",en,New York singer and nightclub owner Lady Lou h...,1.768,"[{'iso_3166_1': 'US', 'name': 'United States o...",1933-02-09,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.7,36.0,2.000000e+06,Profitable,31433,86.117808,0.006528
4672,391,A Fistful of Dollars,False,200000.0,"[{'id': 37, 'name': 'Western'}]",it,The Man With No Name enters the Mexican villag...,16.027,"[{'iso_3166_1': 'IT', 'name': 'Italy'}, {'iso_...",1964-09-12,...,"[{'iso_639_1': 'it', 'name': 'Italiano'}, {'is...",Released,False,7.8,1658.0,1.430000e+07,Profitable,19895,54.506849,0.650033
4613,8942,Wendy and Lucy,False,200000.0,"[{'id': 18, 'name': 'Drama'}]",en,"Wendy, a near-penniless drifter, is traveling ...",5.133,"[{'iso_3166_1': 'US', 'name': 'United States o...",2008-05-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.6,109.0,-2.000000e+05,Not Profitable,3937,10.786301,0.182728
4671,10218,Swingers,False,200000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en,"This is a story about Mike, a guy who left his...",6.577,"[{'iso_3166_1': 'US', 'name': 'United States o...",1996-10-18,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.9,357.0,4.305922e+06,Profitable,8171,22.386301,0.301469
4678,40920,The Business of Fancydancing,False,200000.0,"[{'id': 10402, 'name': 'Music'}, {'id': 18, 'n...",en,"Seymour Polatkin is a successful, gay Indian p...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2002-01-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,3.0,-2.000000e+05,Not Profitable,6257,17.142466,0.003212
4669,35073,"The Beast from 20,000 Fathoms",False,210000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 27, '...",en,An atomic bomb test in the Arctic Circle unfre...,4.542,"[{'iso_3166_1': 'US', 'name': 'United States o...",1953-06-13,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.7,61.0,4.790000e+06,Profitable,24004,65.764384,0.017026
4798,9367,El Mariachi,False,220000.0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",es,El Mariachi just wants to play his guitar and ...,5.852,"[{'iso_3166_1': 'MX', 'name': 'Mexico'}, {'iso...",1992-09-04,...,"[{'iso_639_1': 'es', 'name': 'Español'}]",Released,False,6.6,407.0,1.820920e+06,Profitable,9676,26.509589,0.277615
4666,139948,Burn,False,225000.0,"[{'id': 99, 'name': 'Documentary'}]",en,"A character-driven, action-packed documentary ...",1.920,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-11-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.1,14.0,-1.137000e+05,Not Profitable,2313,6.336986,0.042974
4572,15389,Metropolitan,False,225000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,A radical student is adopted by a group of you...,2.608,"[{'iso_3166_1': 'US', 'name': 'United States o...",1990-08-03,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,57.0,-2.250000e+05,Not Profitable,10439,28.600000,0.036584
4664,18533,Bronson,False,230000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",en,A young man who was sentenced to 7 years in pr...,8.740,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2008-10-09,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,1257.0,2.030712e+06,Profitable,3797,10.402740,2.317356
4661,3060,The Big Parade,False,245000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,The story of an idle rich boy who joins the US...,3.648,"[{'iso_3166_1': 'US', 'name': 'United States o...",1925-11-05,...,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,False,7.5,39.0,2.175500e+07,Profitable,34086,93.386301,0.008581
4647,109729,The Canyons,False,250000.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",en,The discovery of an illicit love affair leads ...,5.181,"[{'iso_3166_1': 'US', 'name': 'United States o...",2013-07-29,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,4.3,126.0,-1.931750e+05,Not Profitable,2043,5.597260,0.265198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,49013,Cars 2,False,200000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",en,Star race car Lightning McQueen and his pal Ma...,16.886,"[{'iso_3166_1': 'US', 'name': 'United States o...",2011-06-11,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.9,3795.0,3.598524e+08,Profitable,2822,7.731507,7.934266
60,17979,A Christmas Carol,False,200000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 18, '...",en,Miser Ebenezer Scrooge is awakened on Christma...,19.041,"[{'iso_3166_1': 'US', 'name': 'United States o...",2009-11-04,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.8,2282.0,1.252339e+08,Profitable,3406,9.331507,4.555960
42,10193,Toy Story 3,False,200000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",en,"Woody, Buzz, and the rest of Andy's toys haven...",19.037,"[{'iso_3166_1': 'US', 'name': 'United States o...",2010-06-16,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.7,7875.0,8.669697e+08,Profitable,3182,8.717808,19.056411
24,254,King Kong,False,207000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",en,"In 1933 New York, an overly ambitious movie pr...",14.078,"[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",2005-12-12,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,4025.0,3.435174e+08,Profitable,4829,13.230137,5.584490
27,44833,Battleship,False,209000000.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",en,"When mankind beams a radio signal into space, ...",15.177,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-04-11,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.6,3103.0,9.402548e+07,Profitable,2517,6.895890,6.903774
36,91314,Transformers: Age of Extinction,False,210000000.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",en,"As humanity picks up the pieces, following the...",23.311,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-06-25,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,4589.0,8.814051e+08,Profitable,1712,4.690411,15.546846
33,36668,X-Men: The Last Stand,False,210000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",en,"When a cure is found to treat mutations, lines...",1.053,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",2006-05-24,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.4,5538.0,2.493596e+08,Profitable,4666,12.783562,7.596057
20,1930,The Amazing Spider-Man,False,215000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,Peter Parker is an outcast high schooler aband...,18.706,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-06-27,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.5,9917.0,5.372159e+08,Profitable,2440,6.684932,26.418238
16,24428,The Avengers,False,220000000.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",en,When an unexpected enemy emerges and threatens...,51.561,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-04-25,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.6,18215.0,1.299558e+09,Profitable,2503,6.857534,55.307231
14,49521,Man of Steel,False,225000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,A young boy learns that he has extraordinary p...,25.801,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2013-06-12,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.5,9355.0,4.430455e+08,Profitable,2090,5.726027,29.094498
15,2454,The Chronicles of Narnia: Prince Caspian,False,225000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",en,One year after their incredible adventures in ...,15.034,"[{'iso_3166_1': 'CZ', 'name': 'Czech Republic'...",2008-05-15,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.5,3291.0,1.946514e+08,Profitable,3944,10.805479,5.423808
18,41154,Men in Black 3,False,225000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",en,Agents J and K are back...in time. J has seen ...,15.290,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-05-23,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.4,6101.0,3.990268e+08,Profitable,2475,6.780822,15.776323
0,19995,Avatar,False,237000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,"In the 22nd century, a paraplegic Marine is di...",30.906,"[{'iso_3166_1': 'US', 'name': 'United States o...",2009-12-10,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.4,17835.0,2.550965e+09,Profitable,3370,9.232877,39.162908
26,271110,Captain America: Civil War,False,240000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",en,"Following the events of Age of Ultron, the col...",35.385,"[{'iso_3166_1': 'US', 'name': 'United States o...",2016-04-27,...,"[{'iso_639_1': 'ro', 'name': 'Română'}, {'iso_...",Released,False,7.3,12900.0,9.133045e+08,Profitable,1040,2.849315,90.548077
2,206647,Spectre,False,245000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,A cryptic message from Bond’s past sends him o...,22.830,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2015-10-26,...,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,False,6.4,6465.0,6.356746e+08,Profitable,1224,3.353425,33.803922
19,122917,The Hobbit: The Battle of the Five Armies,False,250000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,Immediately after the events of The Desolation...,44.423,"[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",2014-12-10,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.2,7917.0,7.060198e+08,Profitable,1544,4.230137,36.918653
3,49026,The Dark Knight Rises,False,250000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",en,Following the death of District Attorney Harve...,28.266,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-07-16,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.7,13306.0,8.349391e+08,Profitable,2421,6.632877,42.319785
4,49529,John Carter,False,250000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,"John Carter is a war-weary, former military ca...",13.317,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-03-07,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.1,3171.0,3.413910e+07,Profitable,2552,6.991781,7.579585
8,767,Harry Potter and the Half-Blood Prince,False,250000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,"As Harry begins his sixth year at Hogwarts, he...",25.651,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2009-07-07,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.6,9878.0,6.839592e+08,Profitable,3526,9.660274,21.291208
46,127585,X-Men: Days of Future Past,False,250000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,The ultimate X-Men ensemble fights a war for t...,32.319,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2014-05-15,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.5,9549.0,4.978628e+08,Profitable,1753,4.802740,40.854250
98,49051,The Hobbit: An Unexpected Journey,False,250000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,"Bilbo Baggins, a hobbit enjoying his quiet lif...",31.965,"[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",2012-11-26,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.2,11595.0,7.711036e+08,Profitable,2288,6.268493,36.487762
22,57158,The Hobbit: The Desolation of Smaug,False,250000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,"The Dwarves, Bilbo and Gandalf have successful...",28.168,"[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",2013-12-11,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.6,7309.0,7.084000e+08,Profitable,1908,5.227397,29.113417
9,209112,Batman v Superman: Dawn of Justice,False,250000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,Fearing the actions of a god-like Super Hero l...,29.778,"[{'iso_3166_1': 'US', 'name': 'United States o...",2016-03-23,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,11461.0,6.232602e+08,Profitable,1075,2.945205,61.836093
13,57201,The Lone Ranger,False,255000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,The Texas Rangers chase down a gang of outlaws...,11.435,"[{'iso_3166_1': 'US', 'name': 'United States o...",2013-07-03,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.0,3616.0,-1.657101e+08,Not Profitable,2069,5.668493,10.486225
5,559,Spider-Man 3,False,258000000.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",en,The seemingly invincible Spider-Man goes up ag...,15.965,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-05-01,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.1,6629.0,6.328716e+08,Profitable,4324,11.846575,9.351735
6,38757,Tangled,False,260000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",en,When the kingdom's most wanted-and most charmi...,20.071,"[{'iso_3166_1': 'US', 'name': 'United States o...",2010-02-03,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.5,5986.0,3.317949e+08,Profitable,3315,9.082192,13.542986
10,1452,Superman Returns,False,270000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,Superman returns to discover his 5-year absenc...,14.957,"[{'iso_3166_1': 'US', 'name': 'United States o...",2006-06-28,...,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,False,5.5,2219.0,1.210812e+08,Profitable,4631,12.687671,2.635392
7,99861,Avengers: Age of Ultron,False,280000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,When Tony Stark tries to jumpstart a dormant p...,42.434,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-04-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.3,12233.0,1.125404e+09,Profitable,1411,3.865753,63.289086

In [44]:
# a lot of the high budget films are really successful that I think we should include in this analysis
movies_df.sort_values("Budget",ascending=False)

,ID,Title,Adult,Budget,Genres,Language,Overview,Popularity,Production Countries,Release Date,...,Spoken Languages,Status,Video,Average Vote,Vote Count,Profit,Profitability,Days Out,Years Out,Critical Acclaim
17,1865,Pirates of the Caribbean: On Stranger Tides,False,380000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",en,Captain Jack Sparrow crosses paths with a woma...,21.644,"[{'iso_3166_1': 'US', 'name': 'United States o...",2011-05-14,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.4,8123.0,6.657138e+08,Profitable,2850,7.808219,18.241123
1,285,Pirates of the Caribbean: At World's End,False,300000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,"Captain Barbossa, long believed to be dead, ha...",20.818,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-05-19,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.1,7879.0,6.610000e+08,Profitable,4306,11.797260,12.991384
7,99861,Avengers: Age of Ultron,False,280000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,When Tony Stark tries to jumpstart a dormant p...,42.434,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-04-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.3,12233.0,1.125404e+09,Profitable,1411,3.865753,63.289086
10,1452,Superman Returns,False,270000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,Superman returns to discover his 5-year absenc...,14.957,"[{'iso_3166_1': 'US', 'name': 'United States o...",2006-06-28,...,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,False,5.5,2219.0,1.210812e+08,Profitable,4631,12.687671,2.635392
6,38757,Tangled,False,260000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",en,When the kingdom's most wanted-and most charmi...,20.071,"[{'iso_3166_1': 'US', 'name': 'United States o...",2010-02-03,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.5,5986.0,3.317949e+08,Profitable,3315,9.082192,13.542986
5,559,Spider-Man 3,False,258000000.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",en,The seemingly invincible Spider-Man goes up ag...,15.965,"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-05-01,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.1,6629.0,6.328716e+08,Profitable,4324,11.846575,9.351735
13,57201,The Lone Ranger,False,255000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,The Texas Rangers chase down a gang of outlaws...,11.435,"[{'iso_3166_1': 'US', 'name': 'United States o...",2013-07-03,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.0,3616.0,-1.657101e+08,Not Profitable,2069,5.668493,10.486225
22,57158,The Hobbit: The Desolation of Smaug,False,250000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,"The Dwarves, Bilbo and Gandalf have successful...",28.168,"[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",2013-12-11,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.6,7309.0,7.084000e+08,Profitable,1908,5.227397,29.113417
98,49051,The Hobbit: An Unexpected Journey,False,250000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,"Bilbo Baggins, a hobbit enjoying his quiet lif...",31.965,"[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",2012-11-26,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.2,11595.0,7.711036e+08,Profitable,2288,6.268493,36.487762
46,127585,X-Men: Days of Future Past,False,250000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,The ultimate X-Men ensemble fights a war for t...,32.319,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2014-05-15,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.5,9549.0,4.978628e+08,Profitable,1753,4.802740,40.854250
9,209112,Batman v Superman: Dawn of Justice,False,250000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,Fearing the actions of a god-like Super Hero l...,29.778,"[{'iso_3166_1': 'US', 'name': 'United States o...",2016-03-23,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,11461.0,6.232602e+08,Profitable,1075,2.945205,61.836093
19,122917,The Hobbit: The Battle of the Five Armies,False,250000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,Immediately after the events of The Desolation...,44.423,"[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",2014-12-10,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.2,7917.0,7.060198e+08,Profitable,1544,4.230137,36.918653
8,767,Harry Potter and the Half-Blood Prince,False,250000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,"As Harry begins his sixth year at Hogwarts, he...",25.651,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2009-07-07,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.6,9878.0,6.839592e+08,Profitable,3526,9.660274,21.291208
4,49529,John Carter,False,250000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,"John Carter is a war-weary, former military ca...",13.317,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-03-07,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.1,3171.0,3.413910e+07,Profitable,2552,6.991781,7.579585
3,49026,The Dark Knight Rises,False,250000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",en,Following the death of District Attorney Harve...,28.266,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-07-16,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.7,13306.0,8.349391e+08,Profitable,2421,6.632877,42.319785
2,206647,Spectre,False,245000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,A cryptic message from Bond’s past sends him o...,22.830,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2015-10-26,...,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,False,6.4,6465.0,6.356746e+08,Profitable,1224,3.353425,33.803922
26,271110,Captain America: Civil War,False,240000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",en,"Following the events of Age of Ultron, the col...",35.385,"[{'iso_3166_1': 'US', 'name': 'United States o...",2016-04-27,...,"[{'iso_639_1': 'ro', 'name': 'Română'}, {'iso_...",Released,False,7.3,12900.0,9.133045e+08,Profitable,1040,2.849315,90.548077
0,19995,Avatar,False,237000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,"In the 22nd century, a paraplegic Marine is di...",30.906,"[{'iso_3166_1': 'US', 'name': 'United States o...",2009-12-10,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.4,17835.0,2.550965e+09,Profitable,3370,9.232877,39.162908
18,41154,Men in Black 3,False,225000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",en,Agents J and K are back...in time. J has seen ...,15.290,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-05-23,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.4,6101.0,3.990268e+08,Profitable,2475,6.780822,15.776323
15,2454,The Chronicles of Narnia: Prince Caspian,False,225000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",en,One year after their incredible adventures in ...,15.034,"[{'iso_3166_1': 'CZ', 'name': 'Czech Republic'...",2008-05-15,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.5,3291.0,1.946514e+08,Profitable,3944,10.805479,5.423808
14,49521,Man of Steel,False,225000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,A young boy learns that he has extraordinary p...,25.801,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2013-06-12,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.5,9355.0,4.430455e+08,Profitable,2090,5.726027,29.094498
16,24428,The Avengers,False,220000000.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",en,When an unexpected enemy emerges and threatens...,51.561,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-04-25,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,7.6,18215.0,1.299558e+09,Profitable,2503,6.857534,55.307231
20,1930,The Amazing Spider-Man,False,215000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,Peter Parker is an outcast high schooler aband...,18.706,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-06-27,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.5,9917.0,5.372159e+08,Profitable,2440,6.684932,26.418238
36,91314,Transformers: Age of Extinction,False,210000000.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",en,"As humanity picks up the pieces, following the...",23.311,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-06-25,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.8,4589.0,8.814051e+08,Profitable,1712,4.690411,15.546846
33,36668,X-Men: The Last Stand,False,210000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",en,"When a cure is found to treat mutations, lines...",1.053,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",2006-05-24,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.4,5538.0,2.493596e+08,Profitable,4666,12.783562,7.596057
27,44833,Battleship,False,209000000.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",en,"When mankind beams a radio signal into space, ...",15.177,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-04-11,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.6,3103.0,9.402548e+07,Profitable,2517,6.895890,6.903774
24,254,King Kong,False,207000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",en,"In 1933 New York, an overly ambitious movie pr...",14.078,"[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",2005-12-12,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,4025.0,3.435174e+08,Profitable,4829,13.230137,5.584490
41,44912,Green Lantern,False,200000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",en,"For centuries, a small but powerful force of w...",14.695,"[{'iso_3166_1': 'US', 'name': 'United States o...",2011-06-16,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.1,4054.0,1.985117e+07,Profitable,2817,7.717808,7.339510
38,102382,The Amazing Spider-Man 2,False,200000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,"For Peter Parker, life is busy. Between taking...",20.269,"[{'iso_3166_1': 'US', 'name': 'United States o...",2014-04-16,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.4,6801.0,5.057174e+08,Profitable,1782,4.882192,24.425589
93,296,Terminator 3: Rise of the Machines,False,200000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",en,It's been 10 years since John Connor saved Ear...,14.129,"[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",2003-07-02,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.0,3337.0,2.350000e+08,Profitable,5723,15.679452,3.498515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4639,431,Cube,False,250000.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 878, '...",en,Seven strangers are taken out of their daily l...,11.347,"[{'iso_3166_1': 'CA', 'name': 'Canada'}]",1997-09-09,...,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,False,6.9,1996.0,2.518180e+05,Profitable,7845,21.493151,1.755564
4661,3060,The Big Parade,False,245000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,The story of an idle rich boy who joins the US...,3.648,"[{'iso_3166_1': 'US', 'name': 'United States o...",1925-11-05,...,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,False,7.5,39.0,2.175500e+07,Profitable,34086,93.386301,0.008581
4664,18533,Bronson,False,230000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",en,A young man who was sentenced to 7 years in pr...,8.740,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2008-10-09,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.0,1257.0,2.030712e+06,Profitable,3797,10.402740,2.317356
4666,139948,Burn,False,225000.0,"[{'id': 99, 'name': 'Documentary'}]",en,"A character-driven, action-packed documentary ...",1.920,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-11-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.1,14.0,-1.137000e+05,Not Profitable,2313,6.336986,0.042974
4572,15389,Metropolitan,False,225000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,A radical student is adopted by a group of you...,2.608,"[{'iso_3166_1': 'US', 'name': 'United States o...",1990-08-03,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,57.0,-2.250000e+05,Not Profitable,10439,28.600000,0.036584
4798,9367,El Mariachi,False,220000.0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",es,El Mariachi just wants to play his guitar and ...,5.852,"[{'iso_3166_1': 'MX', 'name': 'Mexico'}, {'iso...",1992-09-04,...,"[{'iso_639_1': 'es', 'name': 'Español'}]",Released,False,6.6,407.0,1.820920e+06,Profitable,9676,26.509589,0.277615
4669,35073,"The Beast from 20,000 Fathoms",False,210000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 27, '...",en,An atomic bomb test in the Arctic Circle unfre...,4.542,"[{'iso_3166_1': 'US', 'name': 'United States o...",1953-06-13,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,6.7,61.0,4.790000e+06,Profitable,24004,65.764384,0.017026
4671,10218,Swingers,False,200000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en,"This is a story about Mike, a guy who left his...",6.577,"[{'iso_3166_1': 'US', 'name': 'United States o...",1996-10-18,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.9,357.0,4.305922e+06,Profitable,8171,22.386301,0.301469
4672,391,A Fistful of Dollars,False,200000.0,"[{'id': 37, 'name': 'Western'}]",it,The Man With No Name enters the Mexican villag...,16.027,"[{'iso_3166_1': 'IT', 'name': 'Italy'}, {'iso_...",1964-09-12,...,"[{'iso_639_1': 'it', 'name': 'Italiano'}, {'is...",Released,False,7.8,1658.0,1.430000e+07,Profitable,19895,54.506849,0.650033
4673,43595,She Done Him Wrong,False,200000.0,"[{'id': 35, 'name': 'Comedy'}]",en,New York singer and nightclub owner Lady Lou h...,1.768,"[{'iso_3166_1': 'US', 'name': 'United States o...",1933-02-09,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.7,36.0,2.000000e+06,Profitable,31433,86.117808,0.006528
4675,54897,The Grace Card,False,200000.0,"[{'id': 18, 'name': 'Drama'}]",en,Everything can change in an instant ... and ta...,1.740,"[{'iso_3166_1': 'US', 'name': 'United States o...",2011-02-25,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.4,17.0,2.095733e+06,Profitable,2928,8.021918,0.037158
4613,8942,Wendy and Lucy,False,200000.0,"[{'id': 18, 'name': 'Drama'}]",en,"Wendy, a near-penniless drifter, is traveling ...",5.133,"[{'iso_3166_1': 'US', 'name': 'United States o...",2008-05-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.6,109.0,-2.000000e+05,Not Profitable,3937,10.786301,0.182728
4678,40920,The Business of Fancydancing,False,200000.0,"[{'id': 10402, 'name': 'Music'}, {'id': 18, 'n...",en,"Seymour Polatkin is a successful, gay Indian p...",0.600,"[{'iso_3166_1': 'US', 'name': 'United States o...",2002-01-14,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,3.0,-2.000000e+05,Not Profitable,6257,17.142466,0.003212
4695,21334,Children of Heaven,False,180000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",fa,Zohre's shoes are gone; her older brother Ali ...,5.664,"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",1997-08-01,...,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,False,7.9,199.0,7.454020e+05,Profitable,7884,21.600000,0.199404
4713,1779,Roger & Me,False,160000.0,"[{'id': 99, 'name': 'Documentary'}, {'id': 36,...",en,A documentary about the closure of General Mot...,5.036,"[{'iso_3166_1': 'US', 'name': 'United States o...",1989-09-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.3,144.0,6.546368e+06,Profitable,10775,29.520548,0.097559
4704,5723,Once,False,160000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",en,A vacuum repairman moonlights as a street musi...,6.739,"[{'iso_3166_1': 'IE', 'name': 'Ireland'}]",2007-03-23,...,"[{'iso_639_1': 'cs', 'name': 'Český'}, {'iso_6...",Released,False,7.5,664.0,2.055051e+07,Profitable,4363,11.953425,1.141416
4701,5822,Sweet Sweetback's Baadasssss Song,False,150000.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",en,After saving a Black Panther from some racist ...,2.439,"[{'iso_3166_1': 'US', 'name': 'United States o...",1971-04-23,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.3,34.0,1.505000e+07,Profitable,17481,47.893151,0.010308
4703,39141,Tadpole,False,150000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,"Beautiful, sophisticated women are all over Os...",3.070,"[{'iso_3166_1': 'US', 'name': 'United States o...",2002-11-01,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,False,5.8,30.0,2.741288e+06,Profitable,5966,16.345205,0.029165
3498,58882,Snow Flower and the Secret Fan,False,134005.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",en,A story set in 19th century China and centered...,2.246,"[{'iso_3166_1': 'CN', 'name': 'China'}]",2011-07-15,...,"[{'iso_639_1': 'zh', 'name': '普通话'}, {'iso_639...",Released,False,5.9,37.0,1.198226e+06,Profitable,2788,7.638356,0.078300
4514,83,Open Water,False,130000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",en,Two divers are left out at sea without a boat....,6.929,"[{'iso_3166_1': 'US', 'name': 'United States o...",2003-12-29,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.4,543.0,5.453795e+07,Profitable,5543,15.186301,0.528992
4717,84355,Your Sister's Sister,False,125000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",en,Iris invites her friend Jack to stay at her fa...,5.686,"[{'iso_3166_1': 'US', 'name': 'United States o...",2011-09-11,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.6,186.0,3.075000e+06,Profitable,2730,7.479452,0.449670
4718,18632,A Dog's Breakfast,False,120000.0,"[{'id': 35, 'name': 'Comedy'}]",en,If you've never been good at anything in your ...,2.132,"[{'iso_3166_1': 'CA', 'name': 'Canada'}]",2007-03-03,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.3,35.0,-1.200000e+05,Not Profitable,4383,12.008219,0.050308
4719,40652,The Married Woman,False,120000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",fr,A superficial woman has conflict between choos...,3.864,"[{'iso_3166_1': 'FR', 'name': 'France'}]",1964-12-04,...,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,False,7.4,37.0,-1.200000e+05,Not Profitable,19812,54.279452,0.013820
3737,10331,Night of the Living Dead,False,114000.0,"[{'id': 27, 'name': 'Horror'}]",en,A group of people try to survive an attack of ...,12.267,"[{'iso_3166_1': 'US', 'name': 'United States o...",1968-10-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,7.7,979.0,2.988600e+07,Profitable,18415,50.452055,0.409357
4700,55420,Another Earth,False,100000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",en,On the night of the discovery of a duplicate E...,7.558,"[{'iso_3166_1': 'US', 'name': 'United States o...",2011-07-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.7,809.0,1.676935e+06,Profitable,2781,7.619178,1.949047
4138,115210,Stitches,False,100000.0,"[{'id': 27, 'name': 'Horror'}]",en,"The clumsy and unfunny clown Richard ""Stitches...",5.426,"[{'iso_3166_1': 'IE', 'name': 'Ireland'}]",2012-05-19,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,5.6,132.0,-5.000000e+03,Not Profitable,2479,6.791781,0.298185
4722,18925,Facing the Giants,False,100000.0,"[{'id': 18, 'name': 'Drama'}]",en,A losing coach with an underdog football team ...,7.013,"[{'iso_3166_1': 'US', 'name': 'United States o...",2006-09-29,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,False,6.9,127.0,1.007833e+07,Profitable,4538,12.432877,0.193103

In [45]:
movies_df["Budget"].describe()

count    3.794000e+03
mean     3.711514e+07
std      4.240286e+07
min      1.000000e+05
25%      9.000000e+06
50%      2.300000e+07
75%      5.000000e+07
max      3.800000e+08
Name: Budget, dtype: float64

In [46]:
# since a lot of our analysis studies ratings and reviews, I am concerned that older films might not fare well under this metric. Therefore, I am excluding all films not

In [47]:
movies_df["Status"].describe()

count         3794
unique           1
top       Released
freq          3794
Name: Status, dtype: object

In [48]:
movies_df["log Budget"] = np.log(movies_df["Budget"])
movies_df["log Critical Acclaim"] = np.log(movies_df["Critical Acclaim"])

In [49]:
# I think it's important to exclude older films because I think they could be too different. For example, older films might have fewer reviews since they're pre-internet. Also, it's important not to have any effects due to inflation (movies made a long time ago have lower budgets, but at the time may have not been considered "low-budget" films)
new_movies_df = movies_df[movies_df["Release Date"]>="2006-01-01"]

In [50]:
new_movies_df["ID"].count()

1827

In [51]:
new_movies_df.count()

ID                      1827
Title                   1827
Adult                   1827
Budget                  1827
Genres                  1827
Language                1827
Overview                1827
Popularity              1827
Production Countries    1827
Release Date            1827
Revenue                 1827
Runtime                 1827
Spoken Languages        1827
Status                  1827
Video                   1827
Average Vote            1827
Vote Count              1827
Profit                  1827
Profitability           1827
Days Out                1827
Years Out               1827
Critical Acclaim        1827
log Budget              1827
log Critical Acclaim    1827
dtype: int64

In [52]:
# export dataframe to CSV
new_movies_df.to_csv("Output/new_movie_df_cleaned.csv")